### ISSUE TITLE
Consider having more mana recover on a long rest and half as much on a short rest

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#125]
This would still give us short rest based classes, but would be a bit more logical and allow players to not feel quite as constrained by using all their mana on a short rest.

Apply to maneuvers and concoctions as well.

**Comment by DalenWBrauner** [comment]
I think most players would feel **more** restrained, as they have to be much more with their conservative with their castings throughout a day. It doesn't really feel like your mana has "gone to waste" when you always have a steady supply. 

The only scenario I could see a player feeling that way would be is if they didn't have that supply- say, that if they had already spent all their short rests for the day and knew they had upcoming encounters. Under those circumstances it would definitely be reasonable for someone to kick themselves for "wasting" that mana they didn't need to recover.

But I'd argue that this is interesting! Players should be rationing when they should rest. I think that's more entertaining than rationing when they should spend their mana; otherwise you have scenarios where players hold back from doing cool, fun, useful or engaging things in the name of conserving their mana.

**Comment by Marcloure** [comment]
I think what Mark means with making players not feel quite constricted is that casters would have more mana at hand between rests without increasing their overall mana. 

So, for instance, a level 5 Wizard has 5 mana per short rest, or 15 on a long day. If the Wizard casts a 2 mana utility spell, they have burned a large amount of their 5 mana, which means they will probably have to make a short rest before joining combat.

Now, if the Wizard starts the day with 7 mana and gains 4 mana each rest, it doesn't cost that much to cast a 2 mana spell. They won't feel like they need to make a short rest soon enough.

Actually, that is partially how the PHB Wizard works with its Arcane Recovery feature, but in a much smaller scale.

**Comment by mlenser** [comment]
> If the Wizard casts a 2 mana utility spell, they have burned a large amount of their 5 mana, which means they will probably have to make a short rest before joining combat.
> Now, if the Wizard starts the day with 7 mana and gains 4 mana each rest, it doesn't cost that much to cast a 2 mana spell. They won't feel like they need to make a short rest soon enough.

Exactly, well put. Currently, and especially in the 5 mana system it can feel like you need to constantly short rest. This can allow for the same amount of total resources, but spread a bit more across the day so a character can not worry about always "saving a little for the boss".

**Comment by itamarcu** [comment]
Perhaps a cleaner system would be to have a Second Wind style ability to regain resources once between long rests?

> As an action, you can restore an amount of mana/psi/concoctions equal to half your level (rounded up). You must complete a long rest before you can use this feature again.

**Comment by mlenser** [comment]
Short rests do that, but have flavor. Regaining spells as an action doesn't have much thematic basis.

**Comment by DalenWBrauner** [comment]
Okay, so you're suggesting to increase the amount of maximum mana a caster would have at each level, in exchange for the les gained per short rest? I see how that helps the issue now, that's a good idea.

I was very confused by the "more per long rest" part, because long rests already restore _all_ of your mana.

**Comment by mlenser** [comment]
> so you're suggesting to increase the amount of maximum mana a caster would have at each level, in exchange for the les gained per short rest?

correct

**Comment by mlenser** [comment]
This is done:

![image](https://user-images.githubusercontent.com/235857/80979362-88e81000-8e27-11ea-8bb6-28060a164162.png)
![image](https://user-images.githubusercontent.com/235857/80979508-b765eb00-8e27-11ea-901f-36b3dfb65ee0.png)
![image](https://user-images.githubusercontent.com/235857/80979347-82f22f00-8e27-11ea-9ded-1d7d9f216d24.png)
![image](https://user-images.githubusercontent.com/235857/80979379-90a7b480-8e27-11ea-88b8-e23f87474dea.png)
![image](https://user-images.githubusercontent.com/235857/80979474-ad43ec80-8e27-11ea-9d74-f66b0eb586bb.png)
![image](https://user-images.githubusercontent.com/235857/80979410-97cec280-8e27-11ea-8928-9a2dc9e556ba.png)
![image](https://user-images.githubusercontent.com/235857/80979449-a4ebb180-8e27-11ea-956c-31ed81ee144f.png)
