### ISSUE TITLE
Companion damage calculation

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#131]
So, I think I found two issues with the companion damage calculations on the spreadsheet for 5 mana.

First, 1 mana considers that the companion has multiattack, but a resource 1 companion doesn't have it.

Secondly, it considers that the companion has the same to hit chance than the caster, which is not true. A 3 mana companion (9th level caster) has a +6 to hit, while its caster may have +8 to+9.

**Comment by Marcloure** [comment]
It seems the companion's abilities were not updated.

A 3 mana Allosaurus has 17 STR in the 10 mana system, and also 17 STR in the 5 mana system. It should have the abilities of an 6 mana Allosaurus from the 10 mana system.

That is, a 5 mana Companion should have the abilities of a 10 mana Companion. A 3 mana Companion should have the abilities of a 6 mana Companion.

**Comment by mlenser** [comment]
1 mana was meant to have multiattack. It's been fixed now.

> Secondly, it considers that the companion has the same to hit chance than the caster, which is not true. A 3 mana companion (9th level caster) has a +6 to hit, while its caster may have +8 to+9.

Yes, and there isn't really a good way for my sheet to handle this.

> It seems the companion's abilities were not updated.

fixed the points at which abilities increase.

**Comment by mlenser** [comment]
> Secondly, it considers that the companion has the same to hit chance than the caster, which is not true. A 3 mana companion (9th level caster) has a +6 to hit, while its caster may have +8 to+9.

I'm not even sure the sheet should calculate this. 1 resource should not do more damage later in the game because its attack is lower. If you want higher to-hit then usem ore resources. Each is balanced against their tier of usage so I think this is good.

The same "problem" exists for summoning spells that use companion stats. If we want to change things here that'd be outside this issue. But I think it's all good based on the above.

**Comment by Marcloure** [comment]
Ok, that makes sense
