### ISSUE TITLE
Balance of features that scale with mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#132]
Power Surge, Psychic Redoubt, and other features that scale with mana need to be rebalanced for the 5 mana system.

**Comment by Marcloure** [comment]
Wild Surge feat also needs an update

**Comment by mlenser** [comment]
## Power Surge
I think 2 damage to 3 nearby creatures is a nice little feature. It's not huge damage, but it adds up. I wouldn't want to increase from 6 to 12 extra damage per spell. I believe this is balanced as is.

## Psychic Redoubt
This feature gives a 3rd level soulknife ~4-6 extra hp per day. So the equivalent of having 1 higher hit dice. Should it really be 2 higher? Psionicists ability to use psi for both mana and stamina dice is a big feature. Psychic Focus and Strength of Mind are also good features. I think the equivalent of 1 extra HD is strong and 2 would be too much. If we think the psionicist is lacking I'd rather boost it in other areas.

## Wild Surge
Updated from a d12 to a d6:
- 1 mana: 16.6%, used to be ~8.3-16.6% for 1/2 mana
- 2 mana: 33%, used to be ~25-33% for 3/4 mana
- 3 mana: 50%, used to be ~41.6-50% for 1/2 mana
- 4 mana: 66%, used to be ~58-66.6% for 1/2 mana
- 5 mana: 83%, used to be ~75-83% for 1/2 mana

**Comment by Marcloure** [comment]
I think it is ok as is a well. Just wanted to be sure that the conversion won't affect them inadvertedly

**Comment by itamarcu** [comment]
Continuing #293 - Psychic Redoubt gives you an amount of temporary hit points equal to the amount of psi/mana expended. Compare that to [Magical Ward](https://www.kryxrpg.com/themes/feats/magical-ward) which does something very similar, except instead of granting temporary hit points it restores hit points to the ward. furthermore, the ward can protect other creatures and not just yourself.

Both of these spells give you one hit point per mana spent, but Magical Ward is much stronger, because it "stacks" (if it's missing 10 hit points, casting 2-mana spells five time will make it full again) and because it can be "spent" much more easily (absorbing other people's damage with it).

Psychic Redoubt, on the other hand, works by granting you temporary hit points. This means it does not stack at all - casting 2-mana spells five times will leave you with only 2 temporary hit points. To use it most efficiently, you want to take damage every single round, to yourself specifically. That's much harder than Magical Ward's requirements, so functionally it's much weaker.

**Comment by mlenser** [comment]
Two different features with two totally different flavors. That should remain. Though I do think Magical Ward should be limited to level + spellcasting. That way it still stacks, but can't be stacked as high. So it promotes continuous use. I'll make that change now.

Psychic Redoubt: I'd actually rather replace the feature, tbh. It comes from the Mystic:
![image](https://user-images.githubusercontent.com/235857/82985046-9c843200-9ff3-11ea-941d-a3c65db63127.png)

I don't think it fits the Psionicist flavor so well and would prefer another feature in its place.
