### ISSUE TITLE
Feat Suggestion: Minor Shapeshifting

### ISSUE THREAD

**Issue by eunomicZenith** [mlenser/kryx-rpg-issues#152]
**Minor Shapeshifting** (Alteration theme, 2nd level(?))
> You're capable of performing minor alterations to your body, whether thanks to magic you possess or shapeshifting being in your blood and ancestry. As a bonus action, you can change your hair and eye color, make your skin tone a few shades lighter or darker than your normal skin tone, make yourself weigh up to a tenth less or more compared to your normal weight, grow or shrink by up to a tenth compared to your normal height, tweak your facial features, and perform other similarly minor changes. This can be used as a replacement for a disguise kit on yourself. You're considered to have expertise when doing so for the purposes of not being recognized. You're considered capable for the purposes of passing yourself as someone else.

**Comment by mlenser** [comment]
Feats are intended to give benefits that are generally persistant and always there (or in niche cases). Options that you activate are intended to be concoctions, maneuvers, or spells.

I would say this is covered by [Alter Self](https://5mana.kryxrpg.com/themes/spells/alter-self) and [Disguise](https://5mana.kryxrpg.com/themes/spells/disguise).
There could be a cantrip option for a much more minor version of alter-self, if you think that is desired. I expect the desired outcome is too strong for a cantrip though.

**Comment by itamarcu** [comment]
This is different - it's meant to basically be very partial changeling-ism. Like the Harry Potter "Metamorphmagi" people, for example.

The purpose is primarily fluff - letting you change your hair color, eye color, gender expression, facial hair, et cetera - depending on your mood, which season it is, which people you're talking to, and such. I think this is really cool, and a cantrip could serve a similar purpose, though this is not really meant to be a counterable or dispellable ability.

The mechanical benefit is meant to give you the ability to not be recognized (as you can change your main features easily), assuming your clothes aren't very distinct. Pretending to be someone else specifically should still be much tougher, and should be left for Disguise and Alter Self (spells that are temporary, and also alter your clothes). If you think the current idea is overpowered, perhaps the mechanical benefit should be replaced with "You're considered to have proficiency when doing so for the purposes of not being recognized", and no benefit for pretending to be other people.

Hiding yourself in a crowd or pretending not to know a person looking for you are uncommon situations (which are usually less useful, when you're in a party of other recognizable individuals), so I don't really think this is nearly as useful as disguise magic.

**Comment by mlenser** [comment]
Disguise:
> The spell disguises physical appearance as well as clothing, armor, weapons, and equipment. You can make each creature seem 1 foot shorter or taller and appear thin, fat, or in between. You can’t change a target’s body type, so you must choose a form that has the same basic arrangement of limbs.

The suggested wording above does similar things, but at a much lower cost. 1/10 of your height is at least half of a foot for tall races.

This part is especially problematic:

> You're considered to have expertise when doing so for the purposes of not being recognized. You're considered capable for the purposes of passing yourself as someone else.

**Comment by mlenser** [comment]
But even then, this should not exist as a feat:

> Feats are intended to give benefits that are generally persistant and always there (or in niche cases). Options that you activate are intended to be concoctions, maneuvers, or spells.

This is quite clearly a magical ability to alter yourself, much like Alter Self and Disguise, but lesser. The only design room for that is a cantrip.

**Comment by eunomicZenith** [comment]
Well, what would the cantrip do, mechanically?

**Comment by itamarcu** [comment]
**Minor Shapeshift** (0 mana, alteration)
> As a bonus action, you perform minor aesthetic alterations to your body. You can change your hair and eye color, make your skin tone a few shades lighter or darker than your normal skin tone, make yourself weigh up to a tenth less or more compared to your normal weight, grow or shrink by up to a tenth compared to your normal height, tweak your facial features, and perform other similarly minor changes. You cannot replicate a specific face, but you can change your features in a way that makes it hard to recognize you.

**Comment by mlenser** [comment]
While I kinda like the cantrip, use it 2-10 times and you basically have the exact same behavior of a 1 mana spell. I'm wary of that.

If it was 1 thing changed per tier and there was concentration then it'd be much better.

**Comment by DalenWBrauner** [comment]
I think there's still room for a Feat here, but as a companion to the Cantrip. Something like:
> Improved Shapeshifting:
> When casting Minor Shapeshifting, the effects last for a longer period of time.

Some potential compromises for the cantrip:
- Longer time to cast (1 minute or 1 action, rather than a Bonus Action)
- Requires Concentration
- If this is purely for getting others off your scent, then maybe you have little control over the changes- they're just enough to make you appear differently.
- If we're concerned about imitation, or whether this should be a "perfect" disguise, maybe limitations such as "it cannot change the shape of your face" or "it can change your hair color or length, but not both".
- Perhaps, like Prestidigitation, you can conjure one individual effect (hair color change, adding a scar, etc) with each casting, and up to 3 or so effects at a time. That might be the most balanced, and requires a bit of player creativity.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/81113231-30486e00-8f20-11ea-8bf7-7fe9edde4b1c.png)

**Comment by DalenWBrauner** [comment]
Alternative name:
> Alter Appearance
Text tweak:
>As an action, you can change your appearance

And lastly, with just how minor those changes are (I see that this cantrip would work well _with_ a disguise kit, not to replace it), I think you should start out with 2 changes instead of 1, gaining 1 more as you described.

**Comment by DalenWBrauner** [comment]
I'm also still in favor of a Feat to enhance the duration, but that brings up another question.

What happens when the duration ends? I could just recast the spell with the same alterations, right? As long as I'm not standing in front of the people I'm trying to hide from as I do so...

**Comment by itamarcu** [comment]
I don't get why this has a duration or a limit on the ways to alter yourself - why not allow permanent changes? if someone wants to have their character switch hair color every day or change their hair often, why not just allow them to do that?

> use it 2-10 times and you basically have the exact same behavior of a 1 mana spell. I'm wary of that.

This is really not the intention of the spell/feat - the most it can do is prevent you from being recognized, and that's something you can already do with a disguise kit and a passable roll. It doesn't even change your clothes or weapons, which definitely identify you in many situations. The Disguise spell, however, not only lets you instantly don any disguise you'd like (including costume changes), it also lets you look exactly like someone else - the prison guard, the mage's apprentice, a poor beggar, or a king.

If you're still worried about this being used in emergencies (emergencies in which the character has time to change their outfit but not put on a disguise), you could change the casting time to 10 minutes, going down when you increase in level to become 1 minute, 1 action, bonus action, free action.

**Comment by DalenWBrauner** [comment]
> I don't get why this has a duration or a limit on the ways to alter yourself - why not allow permanent changes? if someone wants to have their character switch hair color every day or change their hair often, why not just allow them to do that?

They can! This is something Changelings can do by default, and theirs is arguably more powerful than anything we've discussed here so far.
https://www.kryxrpg.com/character/races/changeling#change-appearance

I have a lot of different ideas and thoughts on this, but rather than a text dump: is there something here that isn't already covered by the Changeling's racial ability? Depending on the setting and flexibility of the DM, it could be easy to flavortext the character's actual race as something else entirely. My group does this all the time- allowing players to use the Dwarf racial stats, despite being biologically Human (as Dwarves don't exist in that universe), etc.

**Comment by mlenser** [comment]
> I don't get why this has a duration or a limit on the ways to alter yourself - why not allow permanent changes?

You want permanent changes!?!? Not even Alter Self can do that.

This issue feels all over the place in terms of power level. What you're after is definitely not a cantrip or a low level feat.

**Comment by itamarcu** [comment]
> You want permanent changes!?!?

Yeah, permanent aesthetic changes. Just because Alter Self cannot do that doesn't mean that no ability ever should be able to do that...

The power level of these things is miniscule. Moreover, many of these changes can be permanently done simply by spending an hour at a barbershop, changing your makeup, getting tanned, going on a bit of a diet, or - in our modern world - getting minor plastic surgery.

It's not like I'm suggesting an ability that permanently turns your head invisible. It's more like I'm suggesting a feat that permanently makes your sword smell like strawberries. Just because the word "permanent" is there and it's a magical change does not mean that this is of high power level; The cantrip Mending permanently fixes a broken item but that doesn't mean it's a powerful ability.

**Comment by Marcloure** [comment]
I believe itamarcu's suggestion is for minor cosmetic changes, just like Thaumaturgy and Prestidigitation can make small effects, but to cut your hair, paint your lip and fingernails, clear your skin and clothes, remove spots of rust, so on.

**Comment by mlenser** [comment]
> I believe itamarcu's suggestion is for minor cosmetic changes, just like Thaumaturgy and Prestidigitation can make small effects

The massive difference between this and those spells is this would stack. Use it several times (for free) and it's far better than Alter Self. Sure, it's not instant, but the balance of that is not ok compared to a 1 mana spell.

Whatever this is must have a cost, or the changes have to be temporary and not allow multiple. It can't have no cost, permanent changes, and unlimited amounts.

**Comment by DalenWBrauner** [comment]
Unless it has drawbacks. Like your character cannot mimic someone else. Or that, with a strong enough a check, someone may always be able to recognize you because you can't change your facial structure.

It's absolutely possible to create a version that's intended for purely cosmetic changes for flavor purposes without impacting gameplay. We just need to find it, not dismiss it out of hand.

**Comment by mlenser** [comment]
Alter Self creates purely cosmetic changes.

Purely cosmetic changes impact social situations.

**Comment by DalenWBrauner** [comment]
That's true, but this is just someone's biological appearance. Can it be used in cool and impactful ways? Absolutely. So can a disguise kit.

The disguise kit is an excellent foil to this ability- why not an ability that is, mechanically speaking, a bioloical disguise kit? If we're concerned about time, it could only be performed during short rests. That would make it weaker than a disguise kit, for the trade-off that these changes are "biological" (the 'disguise' cannot be removed) and "permanent" (it wouldn't wear off after some period of time- but disguises can always be maintained and reapplied anyway).

If the "permanent" aspect is still a concern, then perhaps it _requires_ the user to be conscious in order to re-apply the changes each rest. I **dislike** this idea, however, as it implies there is always a "true original form" which feels a tad antithesis to the flavor. The "biological" component could be solved similarly, as I said earlier with checks and facial structure, but this also feels antithesis to the intent.

I suggest we continue brainstorming drawbacks. For flavor reasons, I can understand the desire of this being a 2nd level feat, but I'm not going to deny that it has strength in social situations.

And while I like the cantrip Kryx proposed, it doesn't satisfy the original intent. I think a feat makes more sense, and to address the mechanical concerns, it should absolutely take time (hence the short rest suggestion).

**Comment by mlenser** [comment]
If you think of how to fit the intent, but still remain balanced let me know.

The only thing I can come up with is a power that works on a long rest to change some features like hair color. It still would be very effective in social situations, but if you limit it to a long "cast" like a long rest which is also 1/day then I think you can accomplish balanced permanent alterations.

**Comment by itamarcu** [comment]
Yeah, that could work too. How about this?

** Minor Shapeshifting** (2nd level feat)
> You're capable of performing minor alterations to your body, whether thanks to magic you possess or shapeshifting being in your blood and ancestry. At the end of a long rest, you may make a minor aesthetic change to your body, such as...
> * Changing the color of your hair, eyes, or skin, by a few shades
> * Making your hair (or facial hair) a bit shorter or longer
> * Altering your height or apparent weight by a few percents
> * Slightly shrinking or enlarging your nose, ears, or eyes
> * Making similar minor aesthetic alterations to your body
>
> The GM may decide that some changes require several days (such as changing your skin tone from very pale to very dark, or growing long hair from a previously bald head), or simply impossible (such as growing more than 20% higher than your original height). These changes cannot imitate any particular person.

**Comment by mlenser** [comment]
Minor Alteration added as a 2nd level feat
