### ISSUE TITLE
Consider moving manuevers from "catch-all" themes like Skirmish to more apt themes

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#156]
Skirmish maneuvers for example could move to Air.
Guardian theme could maybe be in Earth, Ice, Water?

Don't force it, but see what fits.
As always, maneuvers will remain mundane and not magical.

**Comment by Lamorak11** [comment]
I don't know about this. Ive got to say I prefer the maneuvers being in sensible nonmagical themes. Totally mundane actions being in fundamentally magical themes just doesn't sit right with me. If themes like skirmish and vanguard are too "catch-all", then I think it makes more sense to introduce more specialised martial themes than to cram them awkwardly into an element.

I don't think think any vanguard maneuvers make sense in fire. It's too much of a stretch, and as others have pointed out it starts to feel like wuxia even if that isn't the intention. It starts to feel like a different game, and I'll point out that when a new player is picking their themes and maneuvers they are going to understand vanguard and skirmish and protection, but picking from fire and air and earth is so much more abstract and really doesn't give the impression of martial skill, but of elemental might.

**Comment by mlenser** [comment]
> magical themes

They aren't magical themes. Earth for example has plenty of manuevers that fit the domain of strength, toughness, and overwhelming force.

Tome of Battle was a massively respected product in 3.5 and there you'll see themes that play off elemental themes.

**Comment by Lamorak11** [comment]
Tome of battle was awesome, but many of the maneuvers were outright magical in nature, and to my understanding you are avoiding that in your system, so I don't see the comparison. 

I do understand earth as a martial theme, even if its not immediately obvious at first glance that it isn't referring purely to elemental earth. But then we start running into problems with the other elements.

Air could be about nimble/fast movement, but then couldn't storm also be about speed (lightning). 

Couldn't a thunderstorm also fit the ideals of overwhelming force that stone does? Same for fire. 

Ice can be as hard and tough as stone, so ice and earth now share that trait.

So with just those examples, earth shares its domains with storm, fire and ice, and storm shares with air and fire. 

Its just too abstract for me. The elements aren't clear-cut enough in what martial traits they could signify, and there is too much overlap.

I think this elemental thing needs to be reconsidered.

**Comment by mlenser** [comment]
> Air could be about nimble/fast movement, but then couldn't storm also be about speed (lightning).

And Storm should have speed! Haste exists in storm as Galvanize. Those that choose the storm theme should have relevant manuevers to pick as well.

I'm limiting this issue to Air only. Will hold off on the others.

**Comment by mlenser** [comment]
I think you've misunderstood my intentions here as I have not been fully explicit with them.

Earth is defined as "Maneuvers from the Earth theme focus on strength and power."
Air is very easily defined as "Maneuvers from the air theme focus on quick movement, darting in and out of battle to strike at the opportune time."

That is 100% the theme of skirmish which makes them the same and saves us an extra theme. If the storm theme share similarities then those maneuvers should also be added to Storm. For example the Storm theme has the Galvanize spell. It should also have maneuvers about speed, I agree.

I agree that elements like Fire are less clearly defined and that is why I put a questionmark above. That was a discussion point.

**Comment by mlenser** [comment]
That said, I think the Skirmish name is much more explicit than "Air" for martials. Though if that's a dealbreaker I'd rather have a theme have a martial name and a spell name or a name that works for both than 2 themes that have the same content.

**Comment by Lamorak11** [comment]
OK, I follow you a little better.

Is it your intention therefore to completely phase-out the vanguard/skirmish/etc themes by moving their content to other themes?

If so, what about the feats and maneuvers that don't fit? 

For example I don't particularly see the dual wielder feat fitting into one of those themes, so what happens to it? Would it become a general martial feat not tied to theme? (which actually sounds completely reasonable to me as is).

**Comment by DalenWBrauner** [comment]
I very much like the concept of magic-heavy Themes having unique maneuvers, but I don't think that maneuver-focused Themes are a bad thing. Marksmanship makes a lot of sense on its own, and having it helps define a character. Protection is largely the same. I feel that Vanguard and Skirmish themselves are more nebulous, but that's mostly because the Maneuvers in them don't seem to reinforce each Theme's flavor especially well. I'm not sure the solution is to put its Maneuvers in other Themes- maybe just rework those two to have a more distinct flavor. Vanguard maneuvers can focus more on heavier weapons and deflecting blows, Skirmish can focus more on hack-and-slash or hit-and-run tactics (without bleeding into Deceit).

**Comment by itamarcu** [comment]
Why not simply keep the skirmish theme and have many of its maneuvers/feats belong to both Skirmish and Air?

One of them will be "airbending magic", one of them will be "being mobile in combat", and they just share everything that can be done by a person who knows one of them.

**Comment by Lamorak11** [comment]
> That said, I think the Skirmish name is much more explicit than "Air" for martials. Though if that's a dealbreaker I'd rather have a theme have a martial name and a spell name or a name that works for both than 2 themes that have the same content.

You could follow tome of battle's example and make new evocative names for the martial portion of the theme. Air // Darting Wind or Earth // Patient Mountain for example.

**Comment by DalenWBrauner** [comment]
Actually I apologize, I think the maneuvers in Vanguard and Skirmish do fit the flavor well. There are maybe only one or two that seem odd and maybe need to be swapped imo.

**Comment by mlenser** [comment]
> Is it your intention therefore to completely phase-out the vanguard/skirmish/etc themes by moving their content to other themes?

I believe catch-all themes are mostly unhealthy for the design of the game. Themes should be focused on their design space, and not become a "warrior" theme. An earlier theme, Warfare, was destroyed for that reason. I've had similar goals with other martial themes over the last while. I tried doing this a long time ago and you even commented on that one: https://bitbucket.org/mlenser/tabletop-homebrew/issues/516/consider-combining-protection-with. I had an issue for Vanguard as well at some point.

Themes should be narrow in focus. Ideally excess themes should be trimmed and removed, where possible.

> Marksmanship makes a lot of sense on its own, and having it helps define a character. Protection is largely the same.

Protection is a good concept, though Marksmanship rubs me the wrong way. It feels too focused on a specific weapon whereas themes like Protection/Vanguard/Skirmish, while focused on a certain style of play, have other elements mixed in as well.

> Why not simply keep the skirmish theme and have many of its maneuvers/feats belong to both Skirmish and Air?

Then there is no reason to have the Skirmish theme. Air becomes the superior mehcnaical choice. Themes should not be mirror images of eachother. They should have their own niche that they claim the vast majority of.

**Comment by Lamorak11** [comment]
> Marksmanship rubs me the wrong way. It feels too focused on a specific weapon whereas themes like Protection/Vanguard/Skirmish, while focused on a certain style of play, have other elements mixed in as well.

Perhaps Marksmanship could be turned into something that includes marksmanship but also includes all forms of highly accurate combat - call it the Precision Theme, perhaps, and add feats and manuevers that are based on precise, exacting combat and perfect timing.

**Comment by itamarcu** [comment]
> highly accurate combat

Ah, yes, because [yeeting fifteen daggers simultaneously and hoping some of them hit](https://www.kryxrpg.com/themes/maneuvers/volley) requires such precision :P

**Comment by Lamorak11** [comment]
> Ah, yes, because yeeting fifteen daggers simultaneously and hoping some of them hit requires such precision :P
Hey! I'd like to you hit even one guy with the business-end of 15 simultaneously thrown daggers! 🗡️ :D

**Comment by Lamorak11** [comment]
Ok, I'm not sure about this, but I tried to move the contents of the skirmish and vanguard themes to other themes, and if unable to, given my reasons and thoughts. Hopefully it is useful in some way.

Firstly, feats:

Skirmish
- Dual Wielder: Nope, will likely need to go into a general martial theme or the general feat section.
- Mobile: Storm (Rename "Greased Lightening"😄) and Air.
- Slip: Air, Water, (Sand? - hard to catch, slips through the fingers)
- Fleet of Foot: Air, (Storm?)
- Fluid Footwork: Air, (Water? a bit punny, but could fit)
- Rapid Strike: Air, Storm, (Fire?)
- Evasion: Air, Divination(in the vein of danger sense), (Sand? - hard to catch), (Shadow? - hard to catch)

Vanguard
- Born to the saddle: nope, should be general
- Cleave: None seem right, perhaps a small generalist martial theme, or general feats.
- Heavy Armour Master: Protection theme, or general theme/ general feats
- Mounted Combat: Is fairly general. Could be beast but that doesn't seem right, as knights wouldn't want to take beast.
- Polearm Master: General
- Pugilist: General, or earth?
- Savage Attacker: Again fairly general. Maybe Beast or Fire?
- Defensive tactics: super general fighty stuff
- Sharpen the blade: weird and general, i guess? To be honest I'm not sure what this feat is meant to be doing, in-game - not sure how you sharpen your blade to the point of being psuedo-magical in the space of a bonus action. Makes no sense.
- Unerring Accuracy: Could go to some hypothetical precision theme that includes marksmanship, but again is pretty general. Not sure if any of the elements speak to me as particularly accurate more than any other.

A few notes: I made a couple recommendations for fire, with the idea that fire could be about aggression and offensiveness. Its a bit of a stretch though. Lots of the Vanguard feats seem to want to either be in some super generalist martial theme (which, they are), or in no theme at all. 

I'll continue to the maneuvers tomorrow, but its late here, so that will do tomorrow.

**Comment by DalenWBrauner** [comment]
...yeah, I think you highlighted a lot of the problems with this approach
both here in #174.

I'm not going to say we _shouldn't_ do this, because I think changing how
we organize these is going to help inspire better ideas, but I'm going to
throw in a general vote for keeping some kind of Martial-focused themes.

**Comment by Marcloure** [comment]
I also believe we can have purely martial themes the same way we can have purely magical themes

**Comment by mlenser** [comment]
Goals:
- All feats should be in a theme. General feats should be moved into appropriate themes.
- All themes should be thematic and focus on a specific playstyle. No general themes.
  - Vanguard for example focuses on front-line combat. Brute force and a bit of recklessness are its thematics.
  - Protection focuses on defensive options for you are your allies.
  - Skirmish focuses on mobility, dashing in and out. The quick fighter, if you will.
- All themes should elicit significant control over their thematics. For example there is a little crossover between Air and Storm, but they are 95% different themes and it is very easy to discern which theme would be appropriate for which spell.

The three themes listed above are thematic. Where they fall short is that there are also other themes that can focus on that style. Skirmish for example can easily fit into Air and Storm. I tried it and it felt quite good besides the name Air/Storm instead of Skirmish. Other themes it wouldn't be as clear.

Marksmanship is a pure weapon focused theme and really should be something different.

I could share some maneuvers between themes and will do so. But, where possible, it's best to have each theme control its thematics.

**Comment by itamarcu** [comment]
Regarding [Skirmish](https://www.kryxrpg.com/themes/skirmish) - I actually think its abilities are fitting not only to Air , but also Water. And never Storm.

> Water is one of the prime elements; it is shapeless, flowing, and crushing. The Water theme focuses on movement control, protection and utility, with some bludgeoning damage.

> Air is one of the prime elements; it is light, shapeless and agile. The Air theme focuses on a variety of utility, movement control, protection, and bludgeoning damage.

> Storms are turbulent, violent, and destructive. The Storm theme focuses on lightning and thunder damage, stuns and staggers, and some protection.

From these descriptions, my take is...

* Water is about flowing and potentially heavy movements; leans a bit more to reactive, defense
* Air is about fast and light movements; leans a bit more to active, offense
* Storm is about stunning/staggering the opponent

How I'd move the feats, with this in mind:

* Dual Wielder: Air & Water. It's about both light, fast attacks and flowing with your weapons in battle.
* Mobile: Air (and actually there's already "Aerodynamic" in Air which could just be removed).
* Slip: Water. It's about avoiding opportunity attacks.
* Fleet of Foot: Air. It's about going fast.
* Fluid Footwork: Water. It's about avoid difficult terrain (very watery!).
* Rapid Strike: Air. Hitting fast.
* Evasion: Water, and potentially also Air. Liquid being hard to hit is supremely thematic, and air allowing you to dodge easier also makes sense (the enemy only manages to "hit air", whiffing).

And the maneuvers:

* Bait and Switch: Water.
* Fan of Blades: Air (and not just for the "fan" pun).
* Nimble: Water.
* Nimble Defense: Water.
* Nimble Dodge: Water.
* Patient Defense: Water.
* Positioning Strike: Air, and potentially Water too. It's about pushing an enemy.
* Spring Attack: Air.
* Step of the Wind: Air :)
* Vault: Water.
* Slashing Blades: Air, potentially Water; doesn't really let you slip but "dancing around an enemy" is a bit thematic for water too.
* Swift Strike: Air.

And there you have it!

**Comment by Lamorak11** [comment]
Skirmish Maneuvers:

- Bait and Switch: Water. Could also be deciet. 
- Fan of Blades: Air
- Nimble: I'd say Air more than Water
- Nimble Defense: again, I'd say air
- Nimble Dodge: air
- Patient Defense: Water.
- Positioning Strike: Air and Water work.
- Spring Attack: Air.
- Step of the Wind: Air
- Vault: Air or water. 
- Slashing Blades: Air
- Swift Strike: Air.

Vanguard. Here's where stuff gets difficult. 

- Disorient: already in earth, it's a blunt-trauma thing
- glancing blow: already in earth, it's pretty generalist
- hamstring: very technique-based. Quite brutal/cruel. No suggestion. 
- impale: could go into my hypothetical presicion theme, could be seen as a brutal/ cruel maneuver. 
- knockback: air, water, earth
- lunge: air/ water, maybe even fire
- parry: technique-based. Could go into water, maybe?
- precision: precision-based (duh), technique based, no elemental suggestion. 
- slice through: air, fire?
- trip: air, water? 
- whirling blade: air, fire? 
- brace: technique-based, maybe earth or protection (due to patience and defensiveness)
- frenzy: vanguard or fire (if we attribute aggression/ recklessness to fire)
- riposte: air or water?
- staggering strike: earth already
- swift strike: air
- throw: water?

**Comment by mlenser** [comment]
Closing this for now as I'm not sure this is the best way forward.

**Comment by mlenser** [comment]
I want to explore this a bit once again.
