### ISSUE TITLE
Increase AOE of utility spells

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#163]
With the reduction of area in the 5 mana system, damaging spells can be rebalanced (and I prefer them like so), but some utility spells took a heavy hit and weren't changed.

Making them as the smoke bomb would be desirable:  "smoke spreads to fill a sphere twice as big as normal for the duration", or just make them of fixed size.

Some examples of utility spells that were hit:
- Beacon of Hope
- Spike Growth
- Wrath of Nature (arguably)
- Ice Slick/Grease spells
- Holy Circle
- Hallow
- Holy Aura
- Incite Panic
- Fear
- Actually, most AOE spells from Fear and Charm
- Most Walls?

**Comment by Paulorpribeiro** [comment]
Walls were already larger than in RAW for some reason if cast with minimum mana (on 10 mama system). I didn't calculate how they look after the 5mana conversion, but if they are back at RAW dimensions, I don't see a problem. The others I agree with you

**Comment by Marcloure** [comment]
Damaging walls are fine being smaller but dealing more damage. Other walls like Wind Wall and Sand Wall lost quite of its utility by being shorter

**Comment by mlenser** [comment]
> Spike Growth

This spell can be insanely strong. It's a damage spell and shouldn't be treated like the others.

**Comment by mlenser** [comment]
Wall of Sand is fine, at least at the lower mana usages, which is the most important:
![image](https://user-images.githubusercontent.com/235857/81263707-73016780-9040-11ea-978a-6990116641db.png)

**Comment by mlenser** [comment]
- **Creation**
    - Grease and Grease Vial changed to spheres that are twice as big as normal spheres [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Earth**
    - Wall of Stone is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Fear**
    - Fear is a cone that is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Holy**
    - Hallow is a cylinder that is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
    - Holy Circle is a sphere that is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
    - Holy Aura is a sphere that is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Ice**
    - Ice Slick and Ice Slick Vial changed to spheres that are twice as big as normal spheres [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Life**
    - Beacon of Hope is a sphere that is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Plants**
    - Wrath of Nature sphere is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Spirit**
    - Wrath of Nature sphere is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Telekinesis**
    - Inertial Wall is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)
  - **Unholy**
    - Hallow is a cylinder that is twice as big as normal [#163](https://github.com/mlenser/kryx-rpg-issues/issues/163)

Incite Panic I'll need to evaluate further. Let me know of other ones you think need to be adjusted.

**Comment by itamarcu** [comment]
> Spike Growth can be insanely strong

Um. I disagree?

Currently this spell seems incredibly underpowered:

[Spike Growth](https://www.kryxrpg.com/themes/spells/spike-growth) costs 2 mana to create a 3-meter radius sphere (slightly smaller than 4x4 squares on a grid). Creatures that move within it take... 1d4 per 1.5 meters, and it's difficult terrain, and potentially invisible the first time you cast it. So, if you get very lucky and somehow manage to put it in a hallway between yourself and a dozen goblins who now have no choice if they're chasing you and must pass through the spikes, they take... 4d4 damage each, as they pass through the spikes. that's really minor.

Sure, the spell has the technical potential to cause stupid amounts of damage if you somehow grapple the creature and drag it back and forth through the spikes while also not stepping on them yourself and keeping in mind that it's difficult terrain (so even forcing the creature to use its movement to walk through the spikes is only 3d4 damage).... this is a *very* situational combo and the damage does not justify its high mana cost and tiny area of effect, if you ask me. If you're concerned about some odd combo that lets this generate 50 damage per turn, I'd rather you just buff the spell again and nerf that particular interaction, such as putting a limit on the amount of times a creature can get hit by the spikes in a single turn.

Furthermore, this spell doesn't do any instant damage - and if you put it under an enemy, you're actually losing out on potential damage, as they need to cross less spikes to reach you. *Furthermore*, this just changes the floor - it doesn't affect flying creatures, hovering creatures, jumping creatures, etc.

I'm pretty sure you'd rather have a Wall of Fire almost always, as it deals more damage (4d6, save for half), deals it instantly when you cast it, can't be jumped above, deals a damage type that is more resisted than standard piercing damage, and can block a longer section between two places (since if you can't even block the whole path to you, enemies will just walk around the spell). IF you really want to slow down your enemies with difficult terrain, use Erupting Earth for 5d6 instant damage, or use Fissures for the very big area and the potential to knock people prone (to slow them further), both of which don't require your valuable Concentration.

**Comment by mlenser** [comment]
> Um. I disagree?

Please open a new issue when discussing a specific spell in depth.

**Comment by mlenser** [comment]
@Marcloure can you let me know if there are other spells to adjust here?

**Comment by Marcloure** [comment]
I'll be skipping AOE that I think are still powerful and that its effect is more important than affecting multiple creatures, like Archon's Trumpet which stuns creatures in a cone. 

- Affinity Field (seems fine to me, what do you think?)
- Aura of Vitality
- Aura of Purity
- Battle Leader
- Beastial Spirits
- Calm Emotions
- Charming Presence
- Create/Destroy/Purify Water (purify specifically; not that it isn't already enough, I think)
- Extort Truth: Zone of Truth augment
- Faerie Fire
- Glyph of Warding (I'm not sure the damage was updated, 5d6 as a 2 mana spell seems low?)
- Grove
- Hypnotic Pattern
- Incite Panic (which you said you need to evaluate further)
- Maelstrom (its damage increase from 1d4 to 1d6, but the thing of this spell was the massive area)
- Magic Circle
- Move Earth
- Purify Food and Drink (same as Create/Destroy/Purify)
- Putrefy Food and Drink 
- Pyrotechnics
- Reverse Gravity
- Sleep
- Slipsand
- Snowstorm
- Stinking Cloud
- Symbol of Death/Pain; Fear/Discord; Insanity; Sleep; Stunning
- Transmute Rock
- Transmute Sand
- Wall of Force
- Wall of Terror
- Web (although it already has RAW size)
- Whirlwind (same as Maelstrom)
- Wild Magic Sphere

I think that is all, but more may be reported as we encounter them in game

**Comment by mlenser** [comment]
Thanks for the super detailed list. That made it much easier!

I modified all on the list above.

- Faerie Fire changed to a sphere instead of a cube
- Glyph of Warding damage increased
- Hypnotic Pattern changed to a sphere instead of a cube
- Incite Panic is fine I believe
- Slipsand changed to a sphere instead of a cube

Added:
- Disable (same as Sleep)
- Inertial Wall
- Wall of stone
