### ISSUE TITLE
Adapt 5mana augments for multiple targets?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#171]
It looks like the [10mana version of Levitate](https://10mana.kryxrpg.com/themes/spells/levitate) had an augment for adding one additional person per mana spent. The new [5mana version](https://www.kryxrpg.com/themes/spells/levitate) of the spell, however, has the exact same augment price, costing effectively twice as much per person.

Was that intentional? Does this bring it more in-line with RAW? Was this shrunk to better match the AoE reductions? Or does this warrant discussion? I saw this concern only briefly mentioned in #87.

**Comment by mlenser** [comment]
> It looks like the 10mana version [...] costing effectively twice as much per person.

A change in system is an opportunity to see things in new lights. We should seize that opportunity, and not just compare to what came before.

A more applicable viewpoint could be: "Levitate targets 1 additional person when augmented to 2 mana, is it worth 2 mana for two people to levitate? How does that compare to other 2 mana spells?"

**Comment by itamarcu** [comment]
A bit off-topic, but I have some complaints about the Levitate spell.

* Why does Levitate force you to target yourself with it (i.e. has a range of self instead of touch, basically)? Levitating an archer is indeed useful, but to levitate one archer you'd have to spend 2 mana, because one of them would go to you, and you aren't necessarily another archer. Similarly, if you want to target an enemy with this, you gotta spend 2 mana and also affect yourself with the spell, an odd side-effect that I don't think makes sense. Why not just let you target any willing target you're touching when cast at 1 mana, and when augmented, allow both adding targets and better targeting (including monsters, and with increased range)?

* When you cast the spell on yourself, you get to immediately rise vertically up to 9 meters. However, the spell doesn't mention levitating other targets this way; this means you'll have to wait until your next turn to actually get them off of the ground. That's pretty weird, and weak, too.

* As an action, you can alter the altitude of a target within 18 meters by 9 meters. why can't you alter your own altitude, then, when this spell is cast at its baseline form? Furthermore, why not allow you to alter the altitude of all targets simultaneously with the same action?

**Comment by mlenser** [comment]
> A bit off-topic, but I have some complaints about the Levitate spell.

Please open a new issue

**Comment by mlenser** [comment]
@DalenWBrauner let me know how to proceed.

**Comment by DalenWBrauner** [comment]
I'm not sure, which is part of the reason I opened the issue. I agree that, during combat, this can be used very effectively, and it may be sufficient as-is. I would probably have come at this with the "navigating dungeon space as a party" perspective, in which I'd rather have 2 additional party members per mana so that a party of 5 can be lifted with only 2 augments.

> A change in system is an opportunity to see things in new lights. We should seize that opportunity, and not just compare to what came before.
Agreed. I think we can come back to this when we have more playtesting.

**Comment by mlenser** [comment]
Closing this until more feedback.
