### ISSUE TITLE
Psychic Retribution feat: Magical?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#178]
I think most of the Mind feats are fine for noncasters to have, but there's one that particularly blurs the line:

> 2nd Level Mind Feat
>Whenever a creature causes you to make a Will saving throw, that creature takes psychic damage equal to half your level.

I think this one needs to require spellcasting. I'm not sure how a warrior or alchemist can achieve this without magic (unlike, say, Labyrinthine Mind).

**Comment by itamarcu** [comment]
I dunno, I think it could work without magic. You can flavor this as having an alien way of thought due to being an exotic race, or as screeching at anyone who's trying to affect your brain, or as being the int-dumping half-orc barbarian who's "so dumb it causes physical pain to whoever reads his mind".

**Comment by mlenser** [comment]
Those are quite the stretch. I agree with Dalen and will fix.

**Comment by DalenWBrauner** [comment]
> I dunno, I think it could work without magic. You can flavor this as...

I thought so at first too, but this is _any_ Will Save. That's why I compared it to Labrynthine Mind, which is more inline with what you're proposing.
