### ISSUE TITLE
Phantom Steed in... Deceit?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#191]
This seems a bit strange, as it's one of the few spells in Deceit that creates a real object that is tangible enough to carry things and people. It's flavor of a quasi-real, Phantasmal status lends itself better to something you'd experience from a Ghost or the Ethereal Plane. It's not an "illusory" steed, and it seems odd that an "illusory" steed could carry real objects anyway.

I'd recommend moving this to the Spirit theme, or at least having it in both (but that still seems a bit strange).

**Comment by mlenser** [comment]
It's an Illusion spell in RAW :wink:

**Comment by DalenWBrauner** [comment]
😓 ...of course it is.

...so how many votes do I need to dump RAW? 😁
(Or at least _also_ put it in Spirit)

**Comment by mlenser** [comment]
Small correction: the spell is called Phantom Steed, not Phantasmal Steed. Small, but meaningful difference for the theme discussion.

**Comment by mlenser** [comment]
Phantom Steed surely belongs in Deceit due to its flavor.

What is the flavor for a Spirit based horse-creature? Because Faithful Hound?

**Comment by itamarcu** [comment]
Find Steed is Holy/Unholy - as paladins are meant to use it. Personally, I'd rename it to "Divine Steed".

Call Steed is Beast. You literally get a beast friend to ride.

Phantom Steed is Deceit and this doesn't make much sense. Who are you deceiving, when you're making a magic horse? No one at all. I think this is in Deceit just because of the weird "all illusion spells are in Deceit" interaction, but honestly, this spell doesn't make sense as lllusion, either, because it's clearly some creation of magic that can affect the environment and is not meant to trick anyone.

I think the spell should be in Force, Spirit, Creation, or a combination of these.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/81534572-8ece7b80-9368-11ea-9e64-af3cb6779db0.png)

It would be in evocation or something else by RAW if it weren't meant to be illusion.

All Illusion spells belong in the Deceit theme, the same as all fire spells belong in the Fire theme.

![image](https://user-images.githubusercontent.com/235857/81534767-df45d900-9368-11ea-80b5-9a28511dcb52.png)
exists so illusion can be made quasi-real.


I'm going to close this issue as Phantom Steed, based on the RAW flavor belongs in Deceit. If there is a clear desire to change the flavor or add new steed spells, feel free to open a new issue.
