### ISSUE TITLE
Spell strikes: should they be before you hit or after?

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#199]
RAW spell strikes must be cast before you hit. 

## Cons
- You may not hit
- Concentration
- Possible lack of thematics: It can be flavored like channeling a spell into your weapon and it stays there until it hits

## Pros
- Simplicity: There is no need for an extra save in between the attack as this can't be used in response to rolling a crit
- Possible thematics: It can be flavored like channeling a spell into your weapon and it stays there until it hits

If we have the spells be uused before then I'd use the wording of RAW smite spells: `The next time you hit a creature with a melee weapon attack during the spell’s duration`.

## Complications:
- This should apply to all spells. Five Shadow Strike, for example, is very maneuver-like in that it should be used when you hit, not before.
- AoE type spells would have an attack + a save (only against the main target) whereas single target spells would just have an attack. We could have them go off automatically, maybe...
- Creatures that get advantage on saving throws against poison wouldn't get that benefit as there would be no save. But I guess they'd still have resistance to poison damage. And the Dwarf doesn't get that benefit in my system.
- Spells lose their flavor by trading a save for an attack. [Bleed](https://www.kryxrpg.com/themes/spells/bleed), for example, is now just an attack, not a fortitude. This is further complicated by spells like [Dark Delirium](https://www.kryxrpg.com/themes/spells/dark-delirium), or really any will save spell. Suddenly these spells wouldn't have a save? Feels wrong.

**Comment by DalenWBrauner** [comment]
I prefer cast-before-hit. Standard spells are cast before they land (obviously), and I think it makes sense to keep that for spellstrikes. You cast a spell and then make the swing- if you hit, you get the full effect. If you miss, you miss. No additional saving throw required; that's my preference.

One thing interesting about AoE spell strikes though is that they could still go off even if you miss your attack. Anything that shoots out around your target in a cone or a sphere might miss your target if you don't hit their AC, but the surrounding creatures could still make saves.

**Comment by DalenWBrauner** [comment]
Another potential discussion is that, should you miss a spell strike with the first attack in a multiattack, whether or not your second strike could also trigger the effect.  It could be worded as "the next attack you land before the end of your turn", in case we want to account for all weird scenarios.

Not sure how I feel about it, though. Spells don't normally get a 'second chance'.

**Comment by mlenser** [comment]
Smite spells have `The next time you hit a creature with a melee weapon attack during the spell’s duration` and that'd be how I'd handle it.

But looking through the spells I don't think this should apply to all spells. Five Shadow Strike, for example, is very maneuver-like in that it should be used when you hit, not before. Though most spell strikes could be before.

**Comment by mlenser** [comment]
Complication:
AoE type spells would have an attack + a save (only against the main target) whereas single target spells would just have an attack. We could have them go off automatically like you suggest..

**Comment by mlenser** [comment]
Further complication:
Creatures that get advantage on saving throws against poison wouldn't get that benefit ass there would be no save. But I guess they'd still have resistance to poison damage. And the Dwarf doesn't get that benefit in my system..

**Comment by DalenWBrauner** [comment]
> Creatures that get advantage on saving throws against poison

Crap, or Danger Sense, which iirc gives advantage to reflex saves on spell effects you can see. Autohit would blatantly ignore this.

**Comment by DalenWBrauner** [comment]
That could be for the best, though. It makes flavorful sense to me that you can try dodging out of the way of a spell's lightning bolt, but dodging out of the way of a sword charged with lightning is very different.

**Comment by mlenser** [comment]
It works fine for Reflex saves being replaced by the attack, but I don't think it works well for Fort or Will. I updated the OP:

> Spells lose their flavor by trading a save for an attack. Bleed, for example, is now just an attack, not a fortitude. That feels.. wrong. This is further complicated by spells like [Dark Delirium](https://www.kryxrpg.com/themes/spells/dark-delirium), or really any will save spell. Suddenly these spells wouldn't have a save? Feels wrong.

**Comment by itamarcu** [comment]
I admit that it's unrealistic and pretty gamey that you choose to cast the spell only after you hit, but I think this is much cleaner, much more elegant, feels better for the players, avoids major frustrations, and avoids the need to add or change a lot of rules (e.g. to prevent several strikes from being used, to rebalance everything, to consider which of them should be stronger when they crit (as a spell strike that does pure damage is buffed more from the crit than a spell strike that deals both damage and a status effect), and a lot of headaches that aren't actually making the game better.

**Comment by Paulorpribeiro** [comment]
At first I was a little bit concerned about maneuvers activating after a successful attack, this reminds me of the reliable powers from 4th edition, where you only spend the energy after you know it hits, therefore never wastes it. This is a mechanical difference between spells and maneuvers: spells are a gamble, you spend the energy and hopes the enemy fails the save for max damage, if they fail they still take half damage (usually); while maneuvers only deplete resources if they are 100% effective.
I would prefer to maintain this mechanical difference, it helps makes maneuvers and spells unique.
But spell strikes break that "rule" in that they look like maneuvers  (regarding being reliable) but still keep spell damage (roughly triple that of maneuvers). This always bothered me. Now that I was made aware of the crit fishing nature of spell strikes (which I hate in paladins in 5e), I'm even more inclined to ban spell strikes altogether. But it is better to fix them.
I think they should be cast before hit, and work like in 5e, on the first person hit. I would add that if all attacks in the round you cast the spell miss, the caster can concentrate to maintain the spell charged on the weapon for 1 min/mana. Otherwise the spell is wasted. This keeps the "gamble" part of spell casting

**Comment by Paulorpribeiro** [comment]
Before someone say that it takes your concentration slot: I phrased it specifically so it does not require concentration. The caster can have a concentration spell and cast the spell strike. If he misses with all attacks, the spell strike fails unless he chooses to use his concentration to maintain the spell charged (for up to 1 min/mana).

**Comment by mlenser** [comment]
> crit fishing nature of spell strikes (which I hate in paladins in 5e), I'm even more inclined to ban spell strikes altogethe

None of my spell strikes have crit fishing (if any do it's a mistake that should be fixed).

**Comment by Paulorpribeiro** [comment]
Crit fishing in this case (If I understand correctly) is holding the spell to cast only after you roll a natural 20. In this system is not as bad since you can at most make 2 attacks per round, maybe 3 with 2 weapon fighting or feats, but in 5e you can action surge and deliver 6+ attacks and wait to divine smite only when you crit.
In this system, even of it is not as bad as 5e, you can still hold you spell to cast it only when you crit.

**Comment by mlenser** [comment]
You can't crit fish with my system as there is a save inbetween the attack and the damage. So even if you crit on an attack the save is not doubled.
Crit fishing exists when the choice to use the ability is made after the attack and there is no saving throw.

**Comment by Paulorpribeiro** [comment]
What about the mechanical distinction between reliable maneuvers, gamble spells and spell strike being a hibrid (spell damage but reliable as a maneuver)?
What do you think about my proposal to change to bonus action to charge, release at first target hit?

**Comment by itamarcu** [comment]
Currently, spell strikes all follow this template:
* bonus action to cast when you hit with an attack
* targets makes a save. on a failed save they take damage and an effect, on a successful save they take half damage. (obviously not exactly the same, as some spells have more targets or no damage or no effect, but it's very close to this)

This specific pattern being also the pattern of many Maneuvers seems very reasonable to me. This way players never feel like they wasted an ability, but also never want to hold onto their mana until they have a crit or even just advantage for additional chance on a crit.

If you make it "bonus action to charge weapon with spell, release on first hit" - then you create multiple issues:
* People will prefer to never charge up their attacks when they have disadvantage, and try to always charge up their attacks when they have advantage. This is because if you miss with your attacks you gotta pay a steeper price (concentration, or waste of mana) and if you have advantage you have double the chance of critically hitting (and of hitting, in general). A change like this will discourage people from just using their spell strikes consistently.
* If you can keep concentrating on a strike after your turn, what's stopping you from also casting an additional strike on the next turn, and hitting with one attack that's affected by two different spell strikes? or a spell strike and a maneuver?
* Are you going to change all spell strike saves to attack rolls? only some of them? this requires a lot of work and things might get out of balance without you noticing. You might need to start balancing for crits of spells that until now could not crit.
* What if you're using ranged attacks, e.g. if you're throwing daggers? if you enchant your dagger to be burning and then throw it and miss, it doesn't make sense that your next dagger will also be burning, but once one of them hits the rest will no longer burn. The current system might be a bit acausal, depending on your interpretation of when a spell is cast, but I think it makes more sense to just say that you retroactively cast the spell just before throwing and hitting with the dagger than to find an explanation for this other option.

I agree that maneuvers and spell strikes don't have enough mechanical distinctions, but this doesn't look like a great one to add.

**Comment by Paulorpribeiro** [comment]
Let's separate things. First it was said, maybe not in this thread, that spell strikes don't crit because they allow saves before the damage (and that was a smart move), so crit is a non issue for the currenr spell strikes and the proposed change.
 
Now to your points:

> People will prefer to never charge up their attacks when they have disadvantage, and try to always charge up their attacks when they have advantage...
Well this is either metagaming, or just a tactical decision. People also don't use maneuvers when they are at disadvantage when they actually need to choose (charge for example, or dive). On the other hand if they land a lucky shot while prone under the Dragon, they just choose to deliver a devastating 5 stamina staggering strike. If I charge the weapon, I have to make a tactical decision, if I use a maneuver, well, it will depend where the dice lands. Instead of crit-fishing you are effectively hit-fishing.

> If you can keep concentrating on a strike after your turn, what's stopping you from also casting an additional strike on the next turn...

Well, to keep people from double spell striking just a clear rule forbidding it will be enough. It is kinda ridiculous to charge your weapon twice, and should be forbidden if this rule is implemented. To put a maneuver on top of a spellstrike, maybe it could be done, I'm not sure it will be broken, but we could discuss it. I think it is ok. The difference would be just flavour anyway.

> Are you going to change all spell strike saves to attack rolls? only some of them?
No need to.change anything in my opinion, since they don't interact with crits. If they were originally attacks, then maybe we could delete the spell strike version. Save spells need a target, and you have the target right there when you hit it.

> What if you're using ranged attacks, e.g. if you're throwing daggers?
My interpretation is that if you are using ranged attacks, the spell charge is on your hands (or your bow) and you imbue the weapon when you draw it, discharging the spell when you hit or charging another dagger if you miss. Maybe it's also A stretch, but I think it is still  more believable than saying "oh, did I hit? Wait I have casted a 3 mana shock on my sword before I hit it".

Not intend to sound confronting or anything, just discussing some changes here...

**Comment by mlenser** [comment]
> My interpretation is that if you are using ranged attacks, the spell charge is on your hands (or your bow) and you imbue the weapon when you draw it, discharging the spell when you hit or charging another dagger if you miss

The spell, thematically, should 100% be in the projectile/thrown weapon. What's suggested here is really not believable. Thematics first, always.

That said, there is a thematic problem of how the system is currently set up. You decide to cast the spell on a ranged attack only when it hits? That's super weird and very non-thematic.

I think spells should be case beforehand. The main issue for me is the one I outlined in the OP:
>  Spells lose their flavor by trading a save for an attack. [Bleed](https://www.kryxrpg.com/themes/spells/bleed), for example, is now just an attack, not a fortitude. This is further complicated by spells like [Dark Delirium](https://www.kryxrpg.com/themes/spells/dark-delirium), or really any will save spell. Suddenly these spells wouldn't have a save? Feels wrong.

**Comment by mlenser** [comment]
Current thought process:

- Nearly all spell strike variants should be precast (exceptions: Five Shadow Strike)
- Convert all Reflex saves to be part of the attack.
- Keep all Fort/Will saves.

**Comment by Marcloure** [comment]
I don't know if I have much to add, but I'm in line with your thought. It surely will suck to miss an augmented spell strike, but also very powerful on a hit. Crits in this model would have a very high peak tough, a paralyzed foe or a character with Assassinate would reach some pretty high numbers.

**Comment by Paulorpribeiro** [comment]
I also think these 3 points is a nice start, I think they are ready to be implemented, but I raise two more (not exactly new, but just to organize our though process)

* how do we explain (flavorwise, because the mechanics should be the same, for the sake of balance) ranged spell strikes?

*if we convert reflex saves spell strikes to be part of the attack (which I agree by the way) they will be much stronger than Fort and Will spell strikes, how do we balance that?

I expand on that last one: 
(former) reflex saves spell strikes will be stronger because they will add their damage to the attack without any other save (guaranteed extra damage) and they will be able to crit on a nat 20 on the attack (unlike the  other spell strikes, that have a save). They will be favored by all gishes and will have to be balanced (reduced damage maybe?) To be in line.

**Comment by Paulorpribeiro** [comment]
My opinion on those 2 points

1. If there is a weapon involved (a bow, a sling, a crossbow) it is much simpler, the weapon is temporarily enchanted until a successful blow, much like a meele weapon, but thrown weapons is the hard part. I don't have an answer, but I dislike the retrofit solution of "I had cast a spell strike before I hit".

2. I think we just decrease the damage a little bit to compensate and make them balanced (auto hit tag on former Reflex save spell strikes on the spreadsheet should do the trick?). We could also impose disadvantage on the save (in the case of Fort or Will based spell strikes) if the attack was a crit. I would think both (reduced damage and disadv. on a crit) are enough.

Thoughts?

**Comment by mlenser** [comment]
> how do we explain (flavorwise, because the mechanics should be the same, for the sake of balance) ranged spell strikes?
> If there is a weapon involved (a bow, a sling, a crossbow) it is much simpler, the weapon is temporarily enchanted until a successful blow, much like a meele weapon

I don't see how that works. The bow is enchanted, sure, but then it passes the magic on to the projectile. The magic doesn't fling back from the projectile to the weapon when it misses.
Ranged attacks, thematically, must be a 1 shot option.
It's a lesser option than melee, but the same should be true for ranged maneuvers. It doesn't make sense for the decision to use the maneuver to occur when a ranged attack hits.
Thematics first, always.

> if we convert reflex saves spell strikes to be part of the attack (which I agree by the way) they will be much stronger than Fort and Will spell strikes, how do we balance that?

Reflex is avoidance that is similar enough to AC vs an attack so it can be converted. When converted the damage is just reduced a bit.

**Comment by mlenser** [comment]
Some examples:

## Attack Spells
![image](https://user-images.githubusercontent.com/235857/81786253-b441bd80-94ff-11ea-8835-6f2b047634a8.png)

## Reflex Save
These can be treated very similarly to attack spells
![image](https://user-images.githubusercontent.com/235857/81788021-2adfba80-9502-11ea-8760-cb47d66160de.png)

## Will Save
![image](https://user-images.githubusercontent.com/235857/81786808-73967400-9500-11ea-960a-2777871c9dfb.png)
Mind Spiking Strike already has a save for half built in so having this spell last until you hit is as equally balanced as the other options.

## AoE Spells
These can go off on any attack
![image](https://user-images.githubusercontent.com/235857/81786284-bc016200-94ff-11ea-9c67-71172dc77c2a.png)
![image](https://user-images.githubusercontent.com/235857/81786469-ff5bd080-94ff-11ea-86ba-c403c646f467.png)
Very little changed for Acid Bringing Strike
![image](https://user-images.githubusercontent.com/235857/81786546-1c909f00-9500-11ea-8bd0-94055f077dd2.png)
Very little changed for Vitriolic Strike

## Ongoing Spells
![image](https://user-images.githubusercontent.com/235857/81786319-c3287000-94ff-11ea-9a64-668d32d6aed9.png)
Corrosive Consumption already has a save for half built into the repeating condition so having this spell last until you hit is as equally balanced as the other options.
![image](https://user-images.githubusercontent.com/235857/81787215-00413200-9501-11ea-87c2-7b7ed80f7a69.png)
Searing Strike doesn't have concentration so we can add wording like this.


## General rule
We'll need a general rule that you can't channel more than 1 spell into your weapon at a time.

**Comment by Paulorpribeiro** [comment]
I agree with all spell modifications, specially hungry lightning, even if you miss, a lightning bolt jumps from your weapon to shock your enemy, nice changes! 
But if you are using a thrown weapon with a spell like immolation (with no effect on a miss), they just lost the spell. 
It appears that this change won't favor thrown weapons. I don't see a way around this, unfortunately

**Comment by mlenser** [comment]
> It appears that this change won't favor thrown weapons. I don't see a way around this, unfortunately

It won't favor ranged weapons of any kind as the magic on a weapon with projectiles would also be lost.

But what we have now is madness: deciding to use the ability after its hit the target 60 feet away and if not then it goes on the next projectile.

I think that's largely ok as well. Ranged weapons have the advantage of range. If they want a reliable spell strike then melee is their best option. Some spells like [Ensnare](https://www.kryxrpg.com/themes/spells/ensnare) are much stronger on a ranged attack then a melee. Restraining a creature is far more valuable as a ranged attacker.

**Comment by Marcloure** [comment]
> It won't favor ranged weapons of any kind as the magic on a weapon with projectiles would also be lost

That isn't quite what is written, nothing says that the magic is in the projectile, while it is in a thrown weapon. The magic still persists on a bow or crossbow if you miss.

**Comment by mlenser** [comment]
Yas, I'll have to clean up the wording on spells that are "next hit" or "save until next hit" to specify that the magic transfers to the projectile, hit or miss.

**Comment by Paulorpribeiro** [comment]
I agree with Marcloure, the way I interpret it, the "...hit with a weapon or projectile from it..." part means any projectile fired from that weapon before you next turn.
If the intention is to cast the spell in one piece of ammunition or thrown weapon, it should be phrased differently. Sugestion:
"As a bonus action you can channel this spell into your weapon or prepared (or loaded?) Piece of ammunition.

Returning magic daggers and boomerangs will be the name of the game

**Comment by itamarcu** [comment]
I see two problems with this.

1. Spell strikes can now crit if they're based on reflex save spells, but still can't crit if they're based on will or fortitude saves. Why that discrepancy? are the damage numbers balanced around this? (as this increases expected damage by 5%, I'd think)

2. Spell strikes based on reflex or attack rolls only need the attack to hit, but spell strikes based on will and fort need both the attack and the save to land. That's weird.

3. Some of the spells you wrote have it hit on the first attack that hits until the end of turn, some of them are on the first attack that hits within the next minute, and some are for the first attack that hits during the duration (and higher mana increases duration). That's quite inconsistent and seems needlessly confusing.

I'm guessing that you might have made all the attack and reflex based strikes "until end of turn" and everything else until 1+ minutes as an attempt to balance them against problem 2? If so, it feels pretty ugly to me. I'd rather just add reflex saves to all the saveless attacks and keep their duration to the first attack you hit during the next minute. (I also think having this duration extend with mana is too minor to care about, because nobody misses their attack for a whole minute)

**Comment by Marcloure** [comment]
> Spell strikes can now crit if they're based on reflex save spells, but still can't crit if they're based on will or fortitude saves. Why that discrepancy? are the damage numbers balanced around this? (as this increases expected damage by 5%, I'd think)

Crit chance is taken into account when balancing damage.

> Spell strikes based on reflex or attack rolls only need the attack to hit, but spell strikes based on will and fort need both the attack and the save to land. That's weird.

AC kinda already includes your evasion and skill to dodge, but doesn't include your mental or corporal resilience. Also:

> Spells lose their flavor by trading a save for an attack. Bleed, for example, is now just an attack, not a fortitude. This is further complicated by spells like Dark Delirium, or really any will save spell. Suddenly these spells wouldn't have a save? Feels wrong.

**Comment by mlenser** [comment]
> are the damage numbers balanced around this

Please look at the damage spreadsheet. You often have questions how things are calculated. I'd suggest you familiarize yourself with it. https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=1121938024

> Spell strikes can now crit if they're based on reflex save spells, but still can't crit if they're based on will or fortitude saves. Why that discrepancy?
> Spell strikes based on reflex or attack rolls only need the attack to hit, but spell strikes based on will and fort need both the attack and the save to land. That's weird.

Spell strikes of spells with Reflex will be converted to just be automatic effect as part of the attack. I wrote why above:

> Reflex is avoidance that is similar enough to AC vs an attack so it can be converted. When converted the damage is just reduced a bit.

Fort/Will have been covered several times in this issue. Please refer to the explanations above.

Again, I think you've oversimplified things. There are a few cases and the cases aren't always clear:

One attack saves:
- Attack and condition are simple and not based on Will or Fort

Two attacks/saves:
- Attack + auto condition, but condition has a save on each turn
- Attack + condition behind a save.

> Some of the spells you wrote have it hit on the first attack that hits until the end of turn, some of them are on the first attack that hits within the next minute, and some are for the first attack that hits during the duration (and higher mana increases duration). That's quite inconsistent and seems needlessly confusing.

They're all different cases
- AoE: Can go off instantly, great!
- Attacks spells/Reflex saves: These can do damage or half if they miss (when it makes sense like acid or lightning, I'll have to experiment with other cases)
- Fort/Will saves: There is no way to give half effect on a condition. I understand how spells work in that they are lost if the creature saves, but the same is true here. The difference is that there is an attack in between. If we made a spell lost when the attack is missed then the spell has a ~30% chance of going off, which is way worse than normal spells.
- Ongoing spells: See above about fort/will saves. They already have a save on each turn so that is covered.

**Comment by mlenser** [comment]
This wording is slightly tricky, but after trying a few versions I think this is pretty clear:

![image](https://user-images.githubusercontent.com/235857/81811303-b5391600-9524-11ea-9650-6ccf89eab882.png)
`The weapon retains the magic whether it hits or misses.` is implied, but maybe best to be explicit about it?
This would allow thrown weapons/projectiles with concentration to be picked up and used again (probably not too common, but maybe worth it in some cases), or the caster could drop concentration as normal and the spell ends. Its either this or the concentration is lost immediately.

Searing Strike can actually be really simplified:
![image](https://user-images.githubusercontent.com/235857/81811186-8458e100-9524-11ea-866a-2f15051ff5f0.png)
It already has a fortitude on the burning condition so the fire damage can happen automatically. I'll need to recalculate the burning chance to be atk+fort, but that'll just bump up the initial damage by ~1d6 probably.

**Comment by mlenser** [comment]
Ok so I looked up magical arrows as an example and there are a few cases:
- Arrow of Slaying: Does not lose its effect until a creature takes damage from it
- Magical ammunition retains its magic until it hits a creature

So I think our spells cast on a weapon/projectile should persist for the same condition.

**Comment by itamarcu** [comment]
Do we make a decision about combining this with maneuvers? A character could cast a strike as a bonus action, then wait until their next turn to use the strike in combination with a maneuver.

Until now it wasn't possible because maneuvers cost bonus actions as well. Is there any maneuver-spell combination that could be exploited this way, and is too effective?

**Comment by mlenser** [comment]
All aoe versions done.

Still todo:
- Single target spell strikes
- Spell Strike as an augment

**Comment by mlenser** [comment]
Ok, I believe spell strikes are done. I may have missed some things as this was one of the biggest issues that I've done in a while, touching 181 files.

**Comment by mlenser** [comment]
End result:

- All AoE spells (Cones, Lines, Spheres, Cylinders, etc) go off on the first attack
- All other spells go off on the first hit before the end of your turn, are lost on a projectile or if you do not hit on your turn. (Hit+save has ~5% less chance of happening than a normal save)
