### ISSUE TITLE
Implement a Weather system

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#208]
https://old.reddit.com/r/dndnext/comments/ghn4ik/reasonable_weather_effects_an_easy_way_to

**Comment by Marcloure** [comment]
For my desert capaign, as most weather conditions don't apply, I went and made my own tables for 5 levels of wind;
- Normal
- Windy
- Sandy Winds
- Sandstorm
- Furia (basically the sandstorm from Mad Max : Fury Road)

Some are a bit simpler than the table from Reddit in the sense that it either gives full disadvantage or nothing, instead of -2. A reason is that here disadvantages stack, while in 5e it doesn't. Other weather conditions have more effects, especially Furia.

Also, I really liked the Strange Phenomena part, some really cool ideas there!

**Comment by eunomicZenith** [comment]
I'm a big fan of the idea of having a weather system based on the rules described in that document.

**Comment by itamarcu** [comment]
I like that document but I don't see how it's related to Kryx's RPG.

Maybe you could add a page in the adventuring section that just has all of these rules, and add one or two spells that can create/affect this weather?

**Comment by mlenser** [comment]
Weather now recommends using real historical data as that will be much easier and realistic than rolling.
