### ISSUE TITLE
2 maneuvers/spells in one attack.

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#214]
It's about time we talk about this.

We already have the possibility of using a spell strike in combination with a bonus action maneuver, and now I figure the possibility of using aim with another maneuver (ambush comes to mind) for a prepared alpha strike.

Is 2 spells/maneuvers in one attack fair game or too OP?

At 2nd level, an assassin can use ambush and aim to throw a dagger at an unsuspecting fool for an additional +3d8 (1d8 aim,1d8 ambush, 1d8 sneak attack) with advantage . At 4th level and tge assassinate feat, this is a guaranteed crit for double weapon damage +6d8. At 5th level it could be 12d8.
This is a very specific scenario, and maybe not op at all (our character is specialized in assassination), but I just wanted to start the discussion

**Comment by Paulorpribeiro** [comment]
You could also use a spell strike on top of it all, if you could somehow cast it unnoticed, but I'm not into min-maxing that much

**Comment by mlenser** [comment]
> Is 2 spells/maneuvers in one attack fair game or too OP?

It should not be allowed, no. Too much alpha striking. It was one of the reasons I didn't have action maneuvers before.

**Comment by itamarcu** [comment]
Just as a note - Assassinate already grants you advantage on that attack, so the usage of Aim here is really just to spend a turn and a stamina die to add 1d8 to your next attack.

Also, you could make this same combo with Distant Shot or Blood in the Water, used in the turn before the attack. BitW only works on melee against a wounded enemy, but still technically allows such a combined strke.

**Comment by Paulorpribeiro** [comment]
> It should not be allowed, no
I agree, maybe we should write up a rule stating that only one spell strike or maneuver can affect a particular attack.

> Just as a note - Assassinate already grants you advantage on that attack, so the usage of Aim here is really just to spend a turn and a stamina die to add 1d8 to your next attack.
But I don't agree with that reading. The general rule states that if multiple situations affect a roll and each one grants advantage or imposes disadvantage they stack or cancel each other. This is clearly 2 separate situations affecting the role (one from a feat, situational and one from a maneuver, intrinsic to its use). They should stack as per.he general rule.
We could argue if double advantage in this case is too strong, and if it should have stricter rules on stacking advantages, but this is a perfect example of how the stacking advantage rule should be applied, as written.

**Comment by mlenser** [comment]
> I agree, maybe we should write up a rule stating that only one spell strike or maneuver can affect a particular attack.

It's not so clear-cut. Blood in the Water is not intended to have restrictions.

Casting a spell strike and then also using a maneuver is not intended, but this shouldn't be possible with the current spell strikes or the new spell strikes as part of #199 so we're ok there.

Ambush and maybe a few other maneuvers can add damage to the next attack. The max stacking we can get here is 2x stamina limit. So we're ok here.
The only exception is Aim. Because its an action we could have a bonus action from last turn, Aim, and then another maneuver. I think it makes sense that Aim can't be combined with another maneuver.

For the rest I think this is a non-issue, as long as the new spell strikes don't allow for more than we currently do.

_______________________

Re Assassinate: I think its has the potential to be strong. I've opened https://github.com/mlenser/kryx-rpg-issues/issues/221 to look at it closer.

**Comment by mlenser** [comment]
Handled aim as part of #190. I believe doubling up on maneuvers isn't possible otherwise (besides the Blood in the Water-type cases) so closing this issue.
