### ISSUE TITLE
(Minstrel) Performance - Antecedent Elegy 

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#228]
**Antecedent Elegy**
_Prerequisites: Divination theme_
You play an elegy which conjures ghostly historical illusions linked to a location or object. You can cast _past impressions_ without spending mana, but the visions and impressions are indistinct mist-like illusions visible to other creatures.

**Comment by mlenser** [comment]
The `illusions` wording should be something else as this is not a Deceit option.

This feels a bit like a Spirit version of Past Impressions. Prehaps create that first and then have this performance use it?

**Comment by itamarcu** [comment]
I think the word "illusions" is fine, though you can also use the word "images" or "figments". It's clearly just casting Past Impressions except with the augment of sharing it with other people - it's just that instead of doing it by putting the images in their heads one by one, you do it by putting the images in the physical world, for everyone to see (potentially including not-allies, though!).

Yes, it technically conjures figments that are visible but not real, but they're not illusions meant to trick or deceive anyone. The core of this spell is Divination, or perhaps Spirit.

(As a note, by the way - Past Impressions should definitely be a Spirit spell as well as Divination. The description of Spirit literally mentions "witness ghostly impressions of the past", but has no such spell.)

**Comment by mlenser** [comment]
> I think the word "illusions" is fine, though you can also use the word "images" or "figments"

Those are all the same thing: Deceit theme.

______________________

> It's clearly just casting Past Impressions except with the augment of sharing it with other people

The how is very important.

**Comment by itamarcu** [comment]
I think this is just mirroring our disagreement about what Deceit is about, just like #191 (Phantom Steed). I think the theme is clearly about deceiving people, and illusions are just the preferred method of doing it. When you're making a horse to ride on or when you're creating indistinct mist-like ghostly illusions of a historical event, you're not trying to deceive anyone, you're just using magic that makes a picture.

Past Impression itself says:

> The vision of the event is dreamlike and shadowy

But nobody is suggesting that the spell should be in the Deceit ("dreamlike") or Shadow ("shadowy") themes. Just like people aren't suggesting that Goodberry be in the Life theme.

**Comment by mlenser** [comment]
I want to state this as clearly as possible: All illusions belong in the Deceit theme. No ifs and or buts about it. This is the same as all water spells being in Water and all cold spells being in Cold. There is no discussion here, please drop it.

**Comment by mlenser** [comment]
Past impressions can actually already be shared as an augment:
![image](https://user-images.githubusercontent.com/235857/82117220-16542a00-976f-11ea-96c7-6be5ca36b2c6.png)

I don't see it fitting a performance though so I'll close this. Feel free to comment if there is a refined direction.
