### ISSUE TITLE
Distant Teleport should be at 3 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#244]
In #87 I said:

> I believe we can use PHB as a guideline for utility spells. Distant Teleport, for instance, probably should be available at 3 mana with an augment to bring allies at 4 mana

Distant teleport is a 7th level spell in RAW, so it's available at 13th level. Here we can make it available at 9th level as a self-only spell, and at 13th level to bring allies. Also, I believe being able to go anywhere in the world isn't something a 5th level character should be able to do.

**Comment by mlenser** [comment]
RAW Distant Teleport is a 7th level spell that targets you +8 people or an object.
This Distant Teleport is a self-only spell. Quite different power in these spells so we can't say "it was 7th, so should be 3/4"

But we can say "I believe being able to go anywhere in the world isn't something a 5th level character should be able to do."

**Comment by Marcloure** [comment]
> This Distant Teleport is a self-only spell. Quite different power in these spells so we can't say "it was 7th, so should be 3/4"

Well, as a self-only it should be a 3 mana (9th level), and to target 5 people it should requires 4 mana (13th level), which is closer to RAW expectations. But I agree that comparison with RAW is a minor argument.

**Comment by itamarcu** [comment]
I'd like to know why Distant Teleport costs 2 mana while Teleportation Circle costs 3 mana.

Distant Teleport takes an action to go to nearly any place you'd want to go to, and with an augment, you can bring your party (5 people in total) along.

Teleportation Circle takes **1 minute** and **costs 50 gp** and **can only lead you to permanent teleportation circles**. The only benefit it gives is the ability to transfer a bit more people/objects - instead of "five total people or objects" it's "as many as can go through the circle in the span of 6 seconds", which is not a big difference.

Creating a permanent teleportation circle, by the way, is ridiculously expensive - costing almost 20,000 sp.

I think it would be quite reasonable to switch the costs of these two spells - making Distant Teleport 3-mana (maybe increasing the augment to +8 people though) and Teleportation Circle 2-mana.

I would also rather have the permanent teleportation circle cheaper - I'm in favor of requiring you to cast it 50 times in total in the same place, at whatever speed you'd like, so it would be roughly once a week and cost 2500 sp (more reasonable).

I'd also really like an option to teleport to another "temporary" teleportation circle, functionally creating a two-way gate that exists only for a few seconds, but only if you've planned ahead and agreed with a second spellcaster to both cast this spell exactly at the same time and with the same sigils.

**Comment by mlenser** [comment]
> I'd like to know why Distant Teleport costs 2 mana while Teleportation Circle costs 3 mana.

It doesn't anymore.
