### ISSUE TITLE
Deluge Aura

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#257]
Expanding from #248 

**Deluge Aura / Tempest Aura / Hailstorm **
_concentration, 1 minute/mana_

As an action, water wracks around you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you. The crashing waves turn the aura into difficult terrain.

Whenever a creature _(enemy?)_ enters the area for the first time on a turn or starts its turn there, it must make a Reflex saving throw.

On a failed save, the creature takes 2d4 bludgeoning damage and is knocked prone. _(Note: damage is estimated)_

On a successful save, the creature takes half as much damage.

In addition, for the duration, you gain the ability to walk on water. If you are standing on a body of water at least 10 feet deep, creatures have disadvantage on the saving throw against this spell. _(Note: others effects could be used, like increasing area or something else, or nothing)_

**Augment**
You can increase the damage by 2d4 for each additional mana expended.

**Comment by itamarcu** [comment]
I really like this, especially the extra flavor of what happens when you're walking on water.

I suggest that you keep the name "Deluge Aura", as this is a water theme spell. "Torrent Aura" if you're worried about the word. The ice aura would be a different spell (I vote for "Aura Borealis"!)

I'd also suggest making the water give you light or heavy obscurement, but that might be too much for one spell!

**Comment by mlenser** [comment]
> In addition, for the duration, you gain the ability to walk on water.

Water Walk is already a 2 mana spell so this spell shouldn't have this part.

____________________

I think there is a lot we could do with the flavor of waves. Tidal Wave has this wording
> wave that surges forth and then retreats to you like the rising tide

We can use this flavor to let the waves surge out or surge in (user's choice).

**Comment by Marcloure** [comment]
> Water Walk is already a 2 mana spell so this spell shouldn't have this part.

I didn't really target these spells to be all at 2 mana, but wherever they would be at.

> We can use this flavor to let the waves surge out or surge in

An aura that pushes or pull? Yeah, I can see that

**Comment by itamarcu** [comment]
Water Walk is a 2 mana spell, but it also lasts for 1 hour without concentration, can be cast on allies, works on any liquid, lets the creature float up if submerged, and can be cast as a ritual.

I think granting the minor ability to walk only on water just for the caster and only for 2 minutes might be alright. It's not like anyone would be using this spell to cross a body of water or escape from a sinking ship - this is just meant to give you a little bonus if you're using the tides of water around you instead of creating water from thin air.

**Comment by mlenser** [comment]
A few weeks ago we added spells that can do multiple things to several themes. I then removed those spells because the original spells were basically pointless when you have the amalgam spell.

The case isn't the same here, but an aura that causes waves should not cause you to be able to walk on water. Walking on water is powerful benefit that is its own spell.

**Comment by Marcloure** [comment]
Sure, walking on water may make this spell overloaded. I would suggest changing the last paragraph to:

> In addition, if a body of water at least 10 feet deep is within the aura, creatures have disadvantage on the saving throw against this spell. _(Note: others effects could be used, like increasing area or something else, or nothing)_

**Comment by mlenser** [comment]
Tidal Surge added as 1 mana spell with an augment to cause it to continuously occur

**Comment by Marcloure** [comment]
Tidal Surge is already the name of a existing spell

**Comment by mlenser** [comment]
I know, I renamed it to Tidal Breaker.

**Comment by mlenser** [comment]
Check out https://www.kryxrpg.com/themes/spells/tidal-surge. I really like the spell. I don't think additional options like disadvantage on the save would be beneficial for it.

**Comment by mlenser** [comment]
On the next push it'll end the burning condition.

**Comment by Marcloure** [comment]
Also, remove the concentration from the base spell.

**Comment by mlenser** [comment]
I forgot the size restrictions too, will fix.

**Comment by Marcloure** [comment]
Hm, I liked that it could interact with the environment, specially being a water spell, but it's ok.

**Comment by mlenser** [comment]
How would you like it to interact with the environment?
