### ISSUE TITLE
Spell strikes rework: global rule for half damage and disadvantage on the save

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#260]
## Idea
Remove all damage based spell strikes and add a general rule that you can channel the spell into a weapon to deal half damage, but the creature you hit has disadvantage on the saving throw.

______
I'd have to fiddle with it fully, but at a glance it seems pretty good.
It borrows from the Eldritch Strike features from Eldritch Knight (the disadvantage)

### Advantages
- (Playing) The strike is unique from the spell. It does half as much damage, but is much more likely to go off if it hits.
- (Playing/Design) Far fewer spells to remember. Fireball does X damage or half that, not X damage for X-2 damage.

________________

I could expand on this more, but will think this through.

Other spell strikes I'd try to find a solution for as well. I think the Variant system is really bloated. It somewhat works, but always feels a bit weird.

**Comment by itamarcu** [comment]
I like this simplification, assuming we can figure out how to handle this for all or most spells.

Could we also make this happen for non-damage spells, such as Disable? It won't deal half the effect and the creature won't have disadvantage on the saving throw, but the entire thing is riskier because you could lose the spell if you miss your attack. Maybe you could even halve the duration for some of these spells.

The biggest issue I'm imagining with this is that balancing spell strikes (and therefore, spells) will be much more difficult, because you have less parts to play with during the design process. It could be that Immolate is too weak for a single mana spell but "Immolating Strike" (half of immolate plus an attack) is too strong, and then you can't really tweak the damage numbers on just one half of the spell to fix this.

**Comment by mlenser** [comment]
Ok I've calculated this out and it works quite well. The damage is half the normal spell.

## Single Target
The spells can last for the turn so it's effectively attacking with advantage and then the other part. 

### Fort is fort disadvantage
![image](https://user-images.githubusercontent.com/235857/82555686-86e0b980-9b68-11ea-8d2a-8c2403c819d4.png)

### Ref turns into an auto hit
![image](https://user-images.githubusercontent.com/235857/82555732-9c55e380-9b68-11ea-8292-39cc5a762a31.png)

### Will is will disadvantage
![image](https://user-images.githubusercontent.com/235857/82555807-c6a7a100-9b68-11ea-967b-c4e1c581db19.png)

### Attack spells
Acid Arrow is problematic, but I think I can fix that.
I don't have a range 120 attack spell, but if I did it would be like
![image](https://user-images.githubusercontent.com/235857/82555931-0c646980-9b69-11ea-971f-e9f9e736f271.png)


## AoE
Spheres and other AoEs go off automatically. A save is disadvantage against the initial target and then normal against other targets

### Cone
![image](https://user-images.githubusercontent.com/235857/82556828-ce684500-9b6a-11ea-9485-e7d8b69f2049.png)
![image](https://user-images.githubusercontent.com/235857/82556970-12f3e080-9b6b-11ea-9a8f-5edb03b3c852.png)

### Sphere (same as Cylinder)
![image](https://user-images.githubusercontent.com/235857/82555658-7597ad00-9b68-11ea-8bf1-3205623b0b36.png)

**Comment by itamarcu** [comment]
Some exceptions that should be handled:

- Psychic Crush - it's a pretty standard spell, will save or 4d6 damage and stun. it should be spellstrikable under these rules. however, this spell specifically has an augment to make it a spell strike, which costs 1 more mana. might want to add some bit to the War Magic feature that says you can't do this if the spell has an augment to channel the spell? (there's more spells like this, e.g. Mental Prison)
- Sandy Grasp - should potentially not be allowed to be a spell strike.
- We should probably keep the strike options for Bane, Color Spray, Disable, etc as variants, unless we can think of a way to write a generic rule for these too.
- For spells such as Earthbind, Hideous Laughter, Sand Cloud, etc - they currently have this: "You can expend 1 additional mana to channel this spell into your weapon as a bonus action. The weapon transfers the spell to a projectile fired from it. The next time you hit a creature with the weapon, or a projectile fired from it, before the end of your turn, the spell affects the creature you hit.". If we're adding a marker for channelable spells, we could take this opportunity to also add a marker for channelable-by-spending-one-extra-mana spells.
- Dissonant Whispering Strike and Life Drain currently have spell strikes that deal almost the same amount of damage as the spell itself. If this is intentional, their new spell strikes will be bad. If this was unintentional... well, good, because this will fix it.

**Comment by mlenser** [comment]
No miss damage spells like force

**Comment by mlenser** [comment]
Abandoning this option in favor of #264
