### ISSUE TITLE
Companions with Pack Tactics

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#272]
Discussion on Discord:

> Companions that have pack tactics are quite superior combat-wise than the ones that don't, since their damage per attack is the same

> Lowering damage isn't the case for normal 5e monsters that have Pack Tactics

> My two druid players specifically searched for a beast with pack tactics that they had seen as a priority form for combat

> Pack Tactics: Monsters that have it thematically should probably have it as companions. Else they lose a lot of flavor

How could we make the other options more attractive? Or at least, what could be made for people to use the forms most flavorful for them?

**Comment by NyusSong** [comment]
I think the biggest issue here is the presence of Pack Tactics itself. It provides a significant advantage in combat and I think it makes sense that players choose it because it's likely the best for that level. I also think that players should be able to choose whatever they want. Having some forms better than others is going to happen whenever forms are not the same, one of them will provide an advantage and in this case is the Blood Hawk. 

I think we can't make players choose the coolest forms if they think there are other forms that are simply better. In my opinion it has more to do with the type of player you have in your game. Maybe you have a player that chooses the coolest form for them and maybe you have one that decides that being able to survive and fight in the best way possible is a priority.

The problem is that if we eliminate Pack Tactics, the creatures start becoming more the same and lose any kind of difference they may have. However it also happens that creatures with Pack Tactics are statistically better in combat.

**Comment by Marcloure** [comment]
> In my opinion it has more to do with the type of player you have in your game.

There is a saying in the game dev community that states "given the opportunity, players will optimize the fun out of a game", by a designer of Civilization IV. If there is an option that feels better or more reliable, the great majority will prioritize it even if it means sacrificing their fun. Those who don't are the exceptions. You just need to look at Find Familiars and see how common picking owl is just because it's that strictly better.

**Comment by DalenWBrauner** [comment]
I think a lot of this question centers around their CR. While it's fair to say that RAW CR calculations are not known for their consistency, I think we can more accurately calculate them today. One of my fellow Players/DMs actually believes the majority of Kryx's monsters are due for a CR recalculation.

I say this because if we agree Pack Tactics is powerful, then beasts with it need to have a CR to that reflects that. I don't think creatures should be balanced around Pack Tactics, but rather balanced around their CR. All creatures at CR 2 should be as equally appealing choices as we can make them. Same with CR 3, CR 1/2, etc.

If all of a Druid's options are properly calculated, then all we have to do is ask "How many CR 1/2 creatures are available? Do we need to create more CR 2 options?"

**Comment by mlenser** [comment]
> There is a saying in the game dev community that states "given the opportunity, players will optimize the fun out of a game", by a designer of Civilization IV. If there is an option that feels better or more reliable, the great majority will prioritize it even if it means sacrificing their fun. Those who don't are the exceptions.

> majority of Kryx's monsters are due for a CR recalculation.

https://github.com/mlenser/kryx-rpg-issues/issues/3 will look to do that, eventually...

The system that companions use is what I'll extend to build that, eventually. So we should figure out how to balance this trait in this system.

Also: you can ignore monsters as all the abilities like Wild Shape or Call Beast use the companion rules.

**Comment by mlenser** [comment]
I think we have to find ways to make pack tactics compete with the other options. Reducing its damage/to hit is a rudamentary way, but would work.

**Comment by DalenWBrauner** [comment]
I guess my question is then: What is it's "damage value"? What is it
"worth"? If we did decide to reduce damage to compensate, by how much would
be appropriate?

**Comment by mlenser** [comment]
An amount that makes the overall DPR the same, given that Pack Tactics occurs in about ~50-75% of turns.

Pack Tactics turns a ~60% chance to ~83%  chance. So fairly decent damage decrease is one option.

**Comment by mlenser** [comment]
Pretty simple solution: lower the main stat (Str or Dex) by 1 of any companion with Pack Tactics.

Result:
- They have 1 less to hit, but often attack with advantage
- They do 1 less damage per attack

![image](https://user-images.githubusercontent.com/235857/82839012-49fd2580-9ece-11ea-8d5a-fd0419418673.png)

Measurably higher than other companions at tier 4/5, but pack tactics won't apply all the time so it probably evens out.

Example: Blood Hawk has 2 str, 3 dex at 2 resources. It'd becomes 2/2. 2/4 becomes 2/3, 3/4 becomes 3/3 and 3/5 becomes 3/4.

This would work for all companions except the Lion and the Wolf.
The Lion has higher Str than Dex in RAW so that should be the case here.
The Wolf has higher Dex than Str in RAW so we can fix that too.

**Comment by Marcloure** [comment]
Just a note: if this change only impacts the main attribute, then creatures that attack with Str will end up with 1 more AC than those that attack with Dex.

**Comment by mlenser** [comment]
> Just a note: if this change only impacts the main attribute, then creatures that attack with Str will end up with 1 more AC than those that attack with Dex.

Wolf has 12 AC and Blood Hawk has 13. It's still a dex based companion.

**Comment by mlenser** [comment]
Companions with Pack Tactics have their strength or dexterity reduced

**Comment by mlenser** [comment]
Updated calculations:

![image](https://user-images.githubusercontent.com/235857/83345456-96ec5c00-a313-11ea-8d16-631388810a35.png)

**Comment by itamarcu** [comment]
I think crit calculations are missing from this - the empty cells say:

`=IF(OR(G442="atk", G442="atk adv"), 0.05, "")`

so they ignore the option of pack tactic attacks critting.

So, I think it should be:

`=IF(OR(G442="atk", G442="atk adv", G442="pack tactics"), 0.05, "")`

Though, I think it's actually more accurate to have it be:

`=IF(G442="atk", 0.05, IF(G442="atk adv", 0.0975, IF(G442="pack tactics", 0.07375, "")))`

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/83347661-b80a7800-a326-11ea-8f95-293b887bba94.png)
difference is a bit more than before, but still minimal
