### ISSUE TITLE
Replace the Great Weapon Master feat

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#276]
> Great Weapon Master
> You’ve learned to put the weight of a weapon to your advantage, letting its momentum empower your strikes. Once on your turn, when you score a critical hit with a heavy melee weapon you wield in two hands or reduce a creature to 0 hit points with one, you can immediately make one melee weapon attack without using your action.

This is a very risky playstyle. It generally averages going off about 35-40% of the time, but that number could be way higher if you target low HP creatures or your party sets you up for kills. It could also be way lower if you only fight a boss.
I think this playstyle isn't great and we should find another option.

### With feats
- TWF: 29.6 DPR
- GWF: 34.4 DPR
- Polearm: 31.0 DPR

### Without feats
- TWF: 26.0 DPR
- GWF: 29.6 DPR
- Polearm: 26.9 DPR

So we should see if we can lower GWM overall and make a feat similar in power to Polearm/TWF. ~3-4 DPR.

**Comment by itamarcu** [comment]
Can you give some guidelines about what this feat should look like?

**Comment by mlenser** [comment]
- ~3-4 DPR at 5th level see TWF and Polearm Master for similar options for different weapons
- Only usable by the same weapons as cleave
- Consistent damage boost instead of inconsistent high damage
- Thematic

**Comment by itamarcu** [comment]
Ideas...

1. When you hit a creature with a heavy two-handed weapon attack, the creature takes an extra 1d6 damage. You can deal this extra damage only once per turn.

This is straightforward, kind of a copy of the Colossus Slayer feature.

2. When you miss a creature with a heavy two-handed weapon attack, you gain advantage on the next attack you make against the same target with the same weapon before the end of your next turn.

The concept here is that when you miss with your heavy attack you still do something; either you keep your momentum, spinning around for another attack afterwards - or the first attack hits the enemy's shield or armor, winding them, with you then following up on the attack. It is limited to attacking the same creature for this same reason, and mechanically, this prevents cheesiness of missing your friends on purpose and slightly incentivizes the warrior to focus on a single target (which feels thematically good for great weapon fighting).

As for mechanical impact - this ability basically does nothing if you hit with both of your attacks. (41% chance), and there's also a 5% chance that it will make you miss both of your attacks and gain no benefit from it, but usually it will be quite helpful. When you miss with your first attack (36% chance), your next attack's hit chance will increase from 64% to 87%, which is +23%. So, I'm roughly estimating this as a 36%*23% = 8% damage increase. With DPR being around 30 before feats, this should increase it by about 3, which seems good to me.

Note - This can also trigger with the last attack you make on one turn and the first attack you make on your next turn, and even with opportunity attacks.

I ran a quick test in python to calculate how much this improves your total hit rate (ignoring crits), and it looks like this:

```
CHANCE = 0.67
...total_hits = 0
...adv = False
...for _ in range(100000):
...    attack = random.random()
...    if attack < CHANCE or (adv and random.random() < CHANCE):
...        total_hits += 1
...        adv = False
...    else:
...        adv = True
...print("with feat:", total_hits / 100000)
...total_hits = 0
...for _ in range(100000):
...    attack = random.random()
...    if attack < CHANCE:
...        total_hits += 1
...print("without it:", total_hits / 100000)

with feat: 0.73132
without it: 0.6707
```

So, basically, this increases expected hit rate by 6%, a bit less than my estimate. We should also take into account the slightly higher crit chance, and the fact that starting every combat without the potential chance to have advantage from a missed attack of the previous turn, and the fact that you lose this benefit if you switch to attack a different target or if you choose to do something other than attack during your turn, or many other minor formula pieces.

Still, this feels to me like a fun idea that makes sense flavorfully ("your greataxe slams into the hobgoblin's shield, rattling his muscles, and as he struggles to keep hold of it, you step to the side and cut deeply into his arm!"), mechanically (see calculations above), and, uh, game-ily (it's just fun for players to feel good about their misses, as a failure right now means a higher chance to show off later). The only thing that slightly concerns me is keeping track of the fact that you missed your last attack, but since this is just one bit of information, I'm sure that it's not a real issue players would have with this.

**Comment by mlenser** [comment]
[Dual-Handed Assault](https://2e.aonprd.com/Feats.aspx?ID=371) is fairly generic, but I think we need something generic here.

**Comment by Marcloure** [comment]
How would that work here? Heavy weapons (d10/d12) add +1 to damage?

**Comment by mlenser** [comment]
Adding 1.5x your strength to damage would be fairly balanced:
![image](https://user-images.githubusercontent.com/235857/85231089-a9c6ed80-b3f4-11ea-9cdd-f04d1b2d81c6.png)

I'm surprised by the lack of two-handed feats in PF2e.

**Comment by itamarcu** [comment]
Would it be something like this..?

> **Heavy Hitter**, 4th level feat, vanguard
> You’ve learned to put the weight of a weapon to your advantage, letting its momentum empower your strikes. When you deal damage with a heavy melee weapon you wield in two hands, you can add half your Strength to the damage roll.

(or it could be "add +2 to the damage. This increases to +3 at level 11."; levels and bonuses subject to change of course)

**Comment by mlenser** [comment]
Ya, that's what I mapped out above. It's boring and generic, but is balanced.

**Comment by mlenser** [comment]
Great Weapon Master now uses your Strength and a half instead of your strength for melee weapons that you are wielding in two hands
