### ISSUE TITLE
Aura of Vitality out of combat

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#283]
Aura of Vitality is broken in game. One of my players figured he can use it out of combat as a 2 mana spell to heal around 270 hp (3d8 per turn for 20 turns) for the party. It doesn't seem correct that the player can reset all damage taken by the whole team by casting a single spell, in such a way that it's often better to save mana and take hits now, and then expend 2 mana after the battle

If the spell duration doesn't scale with mana, I think may be good enough. This one is similar to the healing spirit issue in RAW: has to be a good as a heal per turn in combat, but not broken out of combat

**Comment by mlenser** [comment]
Removing augments won't help us here. At 2 mana it does 2d8(9) x 20 = 180 healing.

It looks like any out of combat healing (any continuous healing) should probably be removed as there is no way to say "this can be used in combat only".

**Comment by itamarcu** [comment]
How much do we want to limit out-of-combat healing?

The spell [Catnap](https://www.kryxrpg.com/themes/spells/catnap) lets creatures take a short rest in the span of 1 minute, and that's even more valuable than merely healing your party.

I think it's fine to have one spell that is not that good during combat but is excellent outside combat (like Prayer of Healing was supposed to be, in 5e, I hoped). However, if we want Aura of Vitality to be healing during combat, I suggest reducing the duration to "up to 1 minute" or even to a number of rounds equal to the mana cost (and increasing the heal per bonus action, or allowing healing multiple different creatures with one bonus action).

**Comment by mlenser** [comment]
> The spell Catnap lets creatures take a short rest in the span of 1 minute, and that's even more valuable than merely healing your party.

No, it's not. Catnap uses a party's normal resources.

> I think it's fine

180 healing from 2 mana is not fine. This system cares about balance. Options that are that far out of balance definitely need to be brought in line.

> reducing the duration to "up to 1 minute"

All spells above cantrips have durations defined by their mana cost. Please adhere to system design. Additionally, 90 healing from 1 mana is still problematic.

> to a number of rounds equal to the mana cost

This will still result in healing far beyond what is expected for the mana cost.

**Comment by Marcloure** [comment]
I suggest fixing the duration at "up to 1 minute" is good. It would heal 3d8*10 = 135 hp divided between allies (not to each, as was healing spirit).

**Comment by Marcloure** [comment]
I think we can get away with a spell that heals out of combat, but not this much more. Maybe up to 20% above a normal healing

**Comment by mlenser** [comment]
> I think we can get away with a spell that heals out of combat, but not this much more. Maybe up to 20% above a normal healing

💯 agreed.

Though I don't see a way for a continuous spell to do that unless we add some flavor limits to bind it to combat like "While enemy creatures are within 120 feet, the X heals you", but that's problematic as why wouldn't they heal you when there are no enemies?

**Comment by Marcloure** [comment]
A spell with a big casting time is probably what would work, which means it's restricted to out of combat.

But actually, I think I don't like the idea of having variations of a spell for in and out of combat, I don't see need for that.

**Comment by mlenser** [comment]
Some other continuous healing spells:
- Major Regeneration, while powerful, costs 3 mana and only heals 1 creature. Sure it's 150 plus some extra health at 3 mana, but no character has that many points so it's mostly overheal unless you're in combat. Power Word Heal can full heal at 4 mana as an action, so this is ok.
- Major Regeneration + Mass Regeneration is problematic. I'll solve that.

**Comment by mlenser** [comment]
> But actually, I think I don't like the idea of having variations of a spell for in and out of combat, I don't see need for that. Like, if you are in combat, cast Heal, if you are out of combat, cast Prayer of Healing. It isn't actually a choice.

Agreed, which is why I think having it as an option is problematic.

**Comment by itamarcu** [comment]
Continuous spell out of combat:

How about a "Prayer of Healing" spell that simply says

> **Prayer of Healing** - 1 mana - *Concentration, until you stop chanting*
> After every minute that passes while you are continuously chanting, every creature within 30 feet of you regains 5 hit points.

(number can be tweaked, could restrict you to be unable to move, etc)

---

Continuous spell during combat:

- You could have the spell grant temporary hit points
- You could limit the spell to be castable only on creatures that lost at least X hp during the last round
- You could make it give you reactions (or just passive effects) that heal creatures right as they're injured, and can't heal above what they had before injury
- You could say that this spell "feeds" on the damage taken by your friends or your enemies, somehow, mechanically (difficult)
- You could make the spell very loud or attention-grabbing or something that leaves a lot of evidence behind
- You could add a costly material component, even a very cheap one

**Comment by mlenser** [comment]
> Continuous spell out of combat:

See above:

> But actually, I think I don't like the idea of having variations of a spell for in and out of combat, I don't see need for that. Like, if you are in combat, cast Heal, if you are out of combat, cast Prayer of Healing. It isn't actually a choice.

**Comment by mlenser** [comment]
One option: Maximum amount used. Healing Spirit does this.
> The spirit can heal a number of times equal to 1 + your spellcasting ability modifier (minimum twice).

2 mana Heal heals for 31.5. 1.25*31.5=~39-40
This heals for 9 each time it is used, so we could allow for it to be used 4-5 times.

I feel like this is still an out of combat spell. I think it's better to remove than keep out of combat healing spells.

**Comment by itamarcu** [comment]
> I think I don't like the idea of having variations of a spell for in and out of combat

> I think it's better to remove than keep out of combat healing spells.

It doesn't have to be variations of a spell, it can be two spells, like stated there. But just because it isn't a choice out of combat doesn't mean it isn't a choice during combat!

"I could cast Aura of Vitality to heal my two injured friends right now for fifty hit points.... *or....* I could take the risk of not doing that, keeping them injured, so that after the combat is done, we could heal more efficiently with our mana".

It is risk-reward - heal fast vs heal efficiently. Isn't that good game design?

**Comment by mlenser** [comment]
> It is risk-reward - heal fast vs heal efficiently. Isn't that good game design?

You're presenting a false choice. No one should choose Healing Word in combat and no one should choose Heal out of combat. It's an uninteresting choice.

### 2 mana
- Heal heals for 31.5
- Healing Word heals for 9. It takes 3.5 turns for Healing Word to even be equal and if you're waiting that long then it should heal for me.

### Heal vs Regrowth: an actually interesting choice
Now, Heal (31.5 at 2) vs Regrowth (24.5 and 12.25 next turn) where the choice is a bit more over 2 turns or all of it now is an interesting choice. Both are usable in combat and Regrowth is only a bit better out of combat (31.5 vs 36.75) that it isn't necessary to use it instead.

**Comment by itamarcu** [comment]
> You're presenting a false choice. No one should choose Healing Word in combat and no one should choose Heal out of combat. It's an uninteresting choice.

So make them the same spell but with a variant that can only be cast outside combat and is more efficient, if you're worried about the choice of which one to pick. Or add a rule that says "all healing spells can be cast outside combat for 1 minute longer to heal for their maximum amount instead of rolling".

The actual choice during combat is "do I use my 1 resource to immediately heal for 50 hp, or do I keep it for later, because later I will be able to use my 1 resource to heal for 100 hp?". If you change the spells and make all healing outside combat just as effective as healing during combat, you remove this choice, thereby making resource management less interesting. Healing outside combat might need to be only 20% more effective and not 100% more effective - I'll leave the actual numbers out of it, as they're tweakable - but it's gotta be better than healing during combat, otherwise it removes some strategy from the game.

> <comparing Heal and Healing Word>

This is just a different resolution of the same problem - Healing Word's power is in being very fast, letting you heal as a bonus action while still using your main action for something else. Of course it's going to heal worst than Heal, which takes your entire action - it's less efficient in healing power because it's more efficient in action usage.

(Heal and Regrowth are indeed similar, and that's a good comparison! Both of these are intended to be used during combat and not outside it, so both of these are viable choices in combat. One of them is a bit better outside combat, and that's fine - players aren't going to always pick Regrowth over Heal because of it, since out-of-combat healing just doesn't solve the same problems that in-combat healing does.)

My point is - healing outside combat *should* be better. We could argue by how much (my intuition says it should be about 50%-100% stronger, and people should just be able to spend a bit of mana and an hour for a full party heal), or we could choose to limit which spells or augments or variants are meant for out-of-combat, but completely removing the benefit of waiting until after combat to heal is not a good choice.

As for the topic of Aura of Vitality -

> One option: Maximum amount used

I think that's a pretty good option. The spell is meant for combat and requires concentration, so it's likely already balanced around getting an average of ~3 uses (once per round) - putting a limit close to this number could work.

**Comment by Paulorpribeiro** [comment]
If you want to design a spell (or a variant) that can only be used out of combat, you could:
- require the caster to keep chanting, not concentration but actually keep casting the spell while it heals
- state the hit points are healed once every minute
That way you can design a spell that heals for 20% (or 50, or 100) more without fearing it will be too powerful on combat. They could still try to use it on combat, but with threat risk

**Comment by mlenser** [comment]
> If you want to design a spell (or a variant) that can only be used out of combat

The goal is the opposite, as written above a few times now:

> But actually, I think I don't like the idea of having variations of a spell for in and out of combat, I don't see need for that. Like, if you are in combat, cast Heal, if you are out of combat, cast Prayer of Healing. It isn't actually a choice.

**Comment by mlenser** [comment]
Let me expand on why out of combat healing can be a negative force for the game:

There is already pressure to not use healing in combat as using healing in combat means the enemies die slower which means you take more damage which means you need to heal more. It is more efficient to kill the monsters quickly and then heal after, even without superior out of combat healing options.

If out of combat healing options, which are superior to in combat healing options, exist then the pressure to not use in combat healing is even stronger. Now, not only is healing in combat less efficient in terms of damage and turns, but it's also less efficient in terms of resources. The resources are then optimally spent out of combat as you get more benefit.

The less pressure working against in combat healing, the better the system is designed, I believe.


________________

Therefore, I believe out of combat healing options shouldn't exist.

Heal is already healing for significantly more than Cure Wounds does by RAW so there shouldn't be any concern about healing efficiency in general.

**Comment by Paulorpribeiro** [comment]
First
> But actually, I think I don't like the idea of having variations of a spell for in and out of combat, I don't see need for that. Like, if you are in combat, cast Heal, if you are out of combat, cast Prayer of Healing. It isn't actually a choice.

That is why I said a new spell OR a variant, if you don't want either (no out of combat healing spell whatsoever) than it is a new design goal, and we can discuss it calmly.

I also don't think out of combat healing spell are necessary per se, it is flavourful an nice. It is far more common in movies and novels to see the wizard or shaman healing a fallen or wounded ally after the battle is done than healing him in the middle of a battle while swinging a sword (or staff) with a mere touch or powerfull prayer.

IF out of combat healing spell should exist, they should be more powerful "thematically" because the caster is out of danger and stress, and concentrate on the healing effect. Mechanically it might bot make perfect sense and discourage in combat Use, like you said, but in my opinion the incentive to use in combat healinghas always been the same: Urgency.
You don't heal an ally I'm combat because it is more or less action-efficient or more or less mana efficient. You do it because otherwise your ally will DIE.

**Comment by Marcloure** [comment]
If I recall correctly, healing already heals for 90% the damage of a spell. If we have an out of combat spell that heals more than that, than we have a situation where you can heal more than the damaeg you take per mana.

The only way this would work is if in combat healing were much weaker than it currently is (50-60% of damage), so that out of combat healing can heal for 90% of damage. That's closer to the healing values of RAW, which I'm not a big fan of, since I find healing there pretty bad.

**Comment by mlenser** [comment]
Based on what I wrote above, I believe out of combat healing options should not be more efficient than in combat healing options. Therefore they have no reason to exist.

I plan to remove Aura of Vitality today.

**Comment by mlenser** [comment]
Aura of Vitality removed see [why out of combat healing applies negative pressures](https://github.com/mlenser/kryx-rpg-issues/issues/283#issuecomment-633380914)
