### ISSUE TITLE
Wild Shape and other transformation spells are problematic

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#285]
I thought I had ironed all the kinks out of Wild Shape and similar transformation spells, but looking back now I think it's quite obvious that I haven't. These spells offer far too much. In order of Strength/problem:
1. **_Hit points._** This provides a huge buffer of hit points
2. **_Martial prowess._** The martial damage for a character link a Druid goes up quite substantially.
3. **_Utility._** You can acquire faster movement, flying speed, burrow speed, etc. You can also blend in with other beasts for scouting. All kind of utility here.
4. **_New Abilities._** You can gain new maneuvers/spells
5. Probably more that I haven't thought of.

### Wild Shape
- Fly 60 feet for 1 hour/mana
- +52 hit points for 1 hour/mana
- AC either the same or reduced by 1 or 2 if you have high AC (it's 14)
- 2 new maneuvers
- Pack Tactics
- 2 attacks that deal ~12 damage each
- Magic attacks
- Advantage on Perception that relies on sight

### Levitate (Fly)
- Fly 60 feet for 5 minutes/mana

### False Life
- ~45.5 temporary hit points for 1 hour/mana

## Onion Druid
> The Onion Druid is a reference to how Druid Wildshape works in 5th Edition. Basically, they have their own hp pool that is depleted, and if it all goes away the Druid is knocked back into human form at the hp they had when they wildshaped. They can then Wildshape again, meaning they have another form to burn through.
>
> This leads to battles where the Druids 'layers' are peeled, much like an onion, through the following process:
> - Druid shapes up
> - Enemy burns through the Druids animal hp
> - Druid turns back to normal
> - Druid shapes up
> - ad infinitum

The current version is the onion druid, but on steroids as Wild Shape can be used 8 times at 5th level, 14 at 9th level.

## Conclusions
- Hit points have to either go or be heavily changed
- Some other minor/medium power level stuff has to go.

**Comment by itamarcu** [comment]
(moving my comment from the previous thread)

Wild Shape should not be a self buff spell. It should be a "replacement"/"transformation" spell, where you **lose many of your primary capabilities** and gain new different ones. Half of this spell's usage is utility only: you want to become a giant spider to crawl where no one else can go, you want to become a fly on the wall that listens on conversations, you want to become an eel too slippery for the dragon to hold in its claws while flying with you.

The utility value of Wild Shape should not decrease. It's fine if every form only have one or two strong utility values (e.g. climbing speed and a web, or fast running speed and strong sense of smell). It's fine if utility forms have very low HP, AC, saves, or such.

(I'm talking about wild shape and druids here, but really this applies to all form spells. The elemental ones, though, are much weaker from a utility perspective, so I think it would be alright to make them a bit stronger or versatile in a single form (within guidelines) than wild shape is, during combat)

The combat usefulness of Wild Shape - I'm alright with it decreasing. I'd prefer to just make its unique weaknesses weaker over make simple boring changes like reducing HP and DPR, but the solution will probably be a combination of multiple changes.

I made lists of ways to fix this. I think we should mix and match several of the following (obviously not all options, and obviously none of these are final wordings. I'm just offering puzzle pieces):

### Boring ways to make the spell weaker
- Reduce all companion statistics to make this work (bad solution because Call Beast and Eidolon and other things all use the same statistics)
- When you enter your wild shape, you only gain half of the hit points of the creature
- When you deal damage as your wild shape, you only deal half as much damage
- Make wild shape require Concentration
- Make wild shape require something similar to concentration but not actually concentration (so that you can still concentrate on spells you cast as the new form)
- Wild shape gives you one less resource than the usual
- Wild shape has much worse AC and saves
- Wild shape can attack only once each turn

### Less boring ways to make the spell weaker
- Require the druid to augment the spell with additional mana to gain the benefits of one or multiple or all of the following (this augment is an *alternative* to adding "resources" and getting better stat blocks): 
- - The ability to use spells
- - The ability to use maneuvers
- - Special senses
- - Special features
- - Special attacks or multiple attacks
- - Attacks that deal magical damage
- - Not having to keep concentration (and add conc requirement)
- - Longer duration (and reduce normal duration to 1 or 5 minutes. this is good IMO, because there's a difference between long duration noncombative forms and short duration combative forms)
- - The ability to convert mana into hp
- - The ability to speak in animal form
- - The ability to retain your feats and features
- - The ability to retain your mental ability scores (including the ability to make intelligent choices)
- Change the wild shape forms so that they are all really specific in what they can do. A bear can maul and use maneuvers but is very easy to hit and has very bad saves. A wolf has pack tactics and smells and runs, but doesn't do much damage and doesn't have much hp. A bat has flight and blindsight and keen hearing, but can be dropped with one good hit.

**Comment by itamarcu** [comment]
As for the "Onion Druid" - that's indeed a problem. False Life can do the same thing, but that spell doesn't grant you any of the many other benefits that Wild shape does (damage, mobility, maneuvers, etc), and also doesn't allow easy "healing" of the false life hit points (unlike wild shapes that can be healed).

Beyond reducing the hit points, another option could be that when you take damage while wild shaped you also take some damage to your original druid form (perhaps only half of the damage, or just a fixed amount of damage dependent on the mana cost).

Another option would be to make wild shape turn you into a creature that is missing some or most of its hit points (and allowing spending mana to gain life immediately, or even granting natural hp regeneration of one hit die per minute). This way, you can still prepare for a fight by turning into a bear half an hour earlier and short-resting, but you can't do it over and over again during a fight.

**Comment by Marcloure** [comment]
So, my takes on this:

- Remove all but a few of the extra hp (~5/mana), just enough to compensante lack of armor and to increase the resilience of full casters that are going to be on the front line.
- Alternative: make the caster's hp equal to the current form's hp. If the form drops to 0 hp, the caster drops to 0 hp. If the caster reverts with 20 hp, it keeps at 20 hp.
- Limit creatures with powerful special movements to higher resource cost (this is tricky to do with the current system, since it doesn't consider flying creatures as more costly). This isn't _needed_, but is a solution to make this more equal to utility power expectations.
- Limiting spells won't resolve any balance issue IMO. So, for balance alone, I would say against it, but it still may be limited for thematic reasons.
- Reduce a bit the damage. A full caster doesn't need to deal as much damage as a martial in this form if it can also cast spells. It's tricky to change the companion's damage though, and also, gishes can use these spells as well.

Sincerely, I am kinda lost on how to make this work while being both balanced and strong enough to have characters maining the beast form.

**Comment by mlenser** [comment]
> Alternative: make the caster's hp equal to the current form's hp. If the form drops to 0 hp, the caster drops to 0 hp. If the caster reverts with 20 hp, it keeps at 20 hp.

This is super interesting. It keeps HP of companions important (which is great), but removes the massive pseudo temp-hp.

> Limit creatures with powerful special movements to higher resource cost

One approach that I've thought of since I started the companions is to scale the flying speed up. That doesn't model the low challenge monsters with high speed so well though.
If we don't solve this somehow then Wild Shape will always be better than Fly unless there are other serious drawbacks like no spells.

> Limiting spells won't resolve any balance issue IMO

It would make it different from other options like Fly, but I'm not convinced it's the way to go either.

> Reduce a bit the damage.

We can't do this as the forms are meant to emulate a challenge and are used by companions, call beast, and ideally monsters in the future. The only option here is to reduce the level you can transform into. So 2 mana for 1 resource. But I'm not convinced that's a good option as Call Beast is also getting a 2 resource companion on top of the stuff you do.

_____________

Overall I feel like the HP is the biggest issue. Lets start there and Pack Tactics and then recompare.

**Comment by DalenWBrauner** [comment]
A possible addition to the HP Onion solution:
When you Wild Shape into a creature, you choose some amount of HP to sacrifice, up to that creature's normal Max HP. This amount is now your new form's Current and Max HP. When reduced to 0, you return to your standard form as normal, and when you leave your form early, your standard form regains any HP your new form had remaining. (Observe: this can never be more than what you put into it.)

This means that you can still shapeshift into a spider with 2 HP, get stepped on, and immediately become yourself again with most of your hit points. (We can make it so damage overflow impacts the original form as well.)  It also means a squishy caster cannot shapeshift into a Whale and enjoy the benefits of their massive HP pool. _If_ this makes Bearshifting less viable than desired, this can be addressed by giving the new form some _low_ amount of Temp HP upon transformation, perhaps equivalent to their CON mod, their Hit Die, or both.

This also means the new form can be healed, but not beyond what the Druid already had as health. An injured Druid who shapeshifts to defend themselves into a rat with 2HP, cannot be healed until they shapeshift back. However, a Druid that pours 40HP into a bear and loses 30 of it in that form in combt, can be healed as normal.

The biggest reason I like this though is that it keeps the HP of the new form "seperate", so you can't play as a Spider with Human hitpoints. Being able to clock a Druid out of their weaker form is a trait worth keeping, imo.

**Comment by mlenser** [comment]
## HP comparison:

### Tier 2
Elf, 2 con

- Druid: ~33.5 hp
- Warden: ~43.5 hp
- Bear: 59 hp
- True challenge 4 monster: ~80+ hp

Druid absorbing hp would gain ~25.5 hp
Warden absorbing hp would gain ~15.5 hp
False life gives ~22.5 temporary hit points

### Tier 3
Elf, 3 con

- Druid: ~64.5 hp
- Warden: ~82.5 hp
- Bear: 76 hp
- True challenge 4 monster: ~120+ hp

Druid absorbing hp would gain ~11.5 hp
Warden absorbing hp would gain 0 hp
False life gives ~31.5 temporary hit points

### Tier 4
Elf, 3 con

- Druid: ~90.5 hp
- Warden: ~116.5 hp
- Bear: 115 hp
- True challenge 4 monster: ~150+ hp

Druid absorbing hp would gain ~24.5 hp
Warden absorbing hp would gain 0 hp
False life gives ~40.5 temporary hit points

## Conclusion
I'm not sure absorbing HP is the best method due to:
- Druid/casters gain far more than other archetypes/classes
- High HP characters gain nothing at later tiers
- The amount being higher than False Life at Tier 2

We need to tie hp into the character somehow, or options like Bear don't make much sense.

This isn't simple..

**Comment by DalenWBrauner** [comment]
> We need to tie hp into the character somehow, or options like Bear don't make much sense.

Well, part of the issue is that a Druid becomes Too Powerful (for the mana expended) when they can shapeshift into a Bear for melee combat. Why not lock the HP gain behind an augment or a feat? That way it's still an accessible option for shapeshifters that want to use their new forms for melee, but Wild Shape alone doesn't just hand you this power for "free". Example:

> Shape Strength
> x Level Beast Feat // x Mana Augment
> When you Wild Shape into the form of a creature that has a higher Strength, Constitution and Max HP than you, you can take on those statistics. In addition, you gain some amount of HP... (not sure how to calculate an appropriate amount or avoid onioning from here, outside of previous suggestions)

This would mean that by default, you can only ever have your values (or lower) for those stats, current HP included.

(I only threw Strength in there to help brainstorm for combat once we get there.)

**Comment by itamarcu** [comment]
How about:

> The beast has its own hit points and hit point maximum. When you assume the beast's form, it starts with a number of hit points equal to its Constitution multiplied by its Challenge Rating (minimum 1). As you transform, you may choose to transfer hit points from yourself to the beast form. You cannot increase the amount of hit points beyond the maximum.

**Comment by mlenser** [comment]
> Why not lock the HP gain behind an augment or a feat?

Because forms like the Bear have more HP at the cost of other abilities. That can't be lost for transforming into companions.

_____________
> When you assume the beast's form, it starts with a number of hit points equal to its Constitution multiplied by its Challenge Rating (minimum 1). 

Very similar to False Life so that's problematic.

> as spiders with 1 resource have 22 hit points (and elephants have 26).

Go look at challenge 2 monsters on http://donjon.bin.sh/5e/monsters. You won't find many with low hit points.

You're right though, the difference between monsters is currently in their constitution modifier. You can't make the difference substantial without making the damage substantially different.

There are basically a handful of starting abilities, most of which are Con 2, a few of which are Con 3.

**Comment by mlenser** [comment]
Summary of things to fix:
- Find a way to fix hp. ~half as much temp hp as false life could be an option, based on animal form. Maybe con x mana.
- Fix Pack Tactics (#272)
- Limit movement speeds in some way. Delaying until later doesn't truly solve the problem

I think that's all we need to fix regarding Wild Shape.

**Comment by itamarcu** [comment]
Yeah, I was just about to say that:

> Constitution multiplied by the amount of mana expended.

would be, for Bear:

2 - 8 hp (FL = 22.5)
3 - 12 hp (FL = 31.5)
4 - 20 hp (FL = 40.5)
5 - 25 hp (FL = 49.5)

By the way, do consider - False Life's scaling is *drastically* lower than the curve (3d8 and scales by 2d8, while Heal is 3d8 and scales by 4d8). If you cast the wild shape before combat, then yes, it is effectively like gaining temporary hit points. However, if you cast it during combat, it's really more equivalent to healing (and is the source of the "onion druid" troubles), so perhaps this should also be a comparison to keep in mind.

I'm not arguing that any of these should change necessarily - it's just something to keep in mind.

**Comment by mlenser** [comment]
> False Life's scaling is drastically lower than the curve

The issue isn't that the values are below the curve, but that the sheet can't really account for temporary hit points right now. I'd need to modify it to do so. But let's not go off topic with that discussion.

**Comment by mlenser** [comment]
All spells that let you change shape to a companion now give temporary hit points instead of taking the hit points and hit dice of the creature

**Comment by mlenser** [comment]
## New comparison at 2 mana

### Wild Shape (Blood Hawk)
- Fly 60 feet for 2 hours
- +12 temporary hit points for 2 hours
- AC either the same or reduced by 1 or 2 if you have high AC (it's 14)
- 2 new maneuvers
- Pack Tactics
- 2 attacks that deal ~12 damage each
- Advantage on Perception that relies on sight

### Levitate (Fly)
- Fly 60 feet for 10 minutes

### False Life
- ~22 temporary hit points for 2 hours

## TODO
- Fix Pack Tactics (#272)
- Limit movement speeds in some way.

**Comment by itamarcu** [comment]
I'd like to point out that while Fly only gives you 10 minutes and Blood Hawk gives you 2 hours... with Fly you can fly as your normal self, which means you can use ranged spells and attacks, to gain a huge tactical advantage. With a flying hawk, though, you don't have ranged attacks.

Still might need fixing, though, as some wild shapes could potentially carry other party members.

Here's my suggestion - change the Wild Shape's spell duration to 1 minute/mana instead of 1 hour/mana, and allow spending a resource to increase the duration to 1 hour/mana. This way, effective combat forms are only effective for the combat (as they should be), but effective utility forms (hawk, rat, spider, fish...) can still be used out of combat with almost no change at all.

**Comment by marcosPlayX** [comment]
> which means you can use ranged spells and attacks

That will depend on how spellcasting will work. And even if it doesn't work in animal form, Air Elemental would still be able to cast spells

**Comment by Marcloure** [comment]
> which means you can use ranged spells and attacks

That will depend on how spellcasting will work. And even if it doesn't work in animal form, Air Elemental would still be able to cast spells

**Comment by mlenser** [comment]
I believe transformation spells like Wild Shape have been Resolved with #272 and strong forms can be handled as part of #313
