### ISSUE TITLE
Dual wielding gish support (suggestion)

### ISSUE THREAD

**Issue by DiBastet** [mlenser/kryx-rpg-issues#318]
**Crossposted from the discord channel**

> Allow me to suggest / request something. There precious few abilities that benefit / interact with two weapon fighting, which we all know is kind of shafted anyway in 5e. More dual wielding "9-swords-Tiger-Claw-inspired" maneuvers and feats would be appreciated.
> 
> And one specific request I have, is related to a certain niche I found that isn't covered in any way by the rules: Dual wielding gishes.
> 
> There is currently no way (that I can easily find) to perform somatic components while wielding two weapons (or a weapon and shield). Something to fill this niche or warcaster would be nice.
> 
> And second, I request a quality of life feat for dual wielding gishes: there are multiple spells and abilities that allow you to "enchant" one weapon. One. Given that two weapon fighting is usually subpar anyway, and you can only make a single weapon attack with your offhand weapon, i think it's not unreasonable to exist a feat from the skirmish theme that reads something like this.
> 

### Suggestion for a skirmish feat to support dual wielding gishes

> _"Prerequisites: The ability to cast at least one spell
> You can perform the somatic components of spells even when you have weapons or a shield in one or both hands.
> When you cast a spell that targets only one weapon you touch, you can target a second weapon you touch."_

**Note:** An extra limitation could be added to the second bullet, if needed: "The spell ends on the second weapon if it leaves your hand / if another creature holds it". The specific limitations are **if** we want to allow this theorical dual-wielding gish the option to enchant the weapons of two different party members at the cost of a feat (even tho we know that if you're taking a feat from the skirmish tree you're more likely to be dual wielding it yourself, but I think one of the selling points of this system is the freedom to use your choices in different ways), and if we want to allow dual wielding throw weapon gishes (another underappreciated niche).

**Comment by Marcloure** [comment]
> perform somatic components while wielding two weapons

Somatic components (or any component that doesn't cost gold) aren't really covered by the rules at the moment, so they are virtually non existent except where said otherwise. You can find a lengthy discussion about them that went without a conclusion on #186

**Comment by itamarcu** [comment]
We discussed this for a while in the Discord server - a feat like this is very problematic (regarding the enchantment part) because
* It basically refers specifically to the "X Weapon" spells (e.g. Flaming Weapon) which add 1d6 damage to your weapon - it's a feat that is only applicable for a specific group of spells and it's inelegant to just mention them by name or to somehow find a way to mark them
* Functionally these spells are already well-balanced - they add 2d6 damage per turn, no matter which weapons you're using, because they just apply once on your normal attack and once on your extra attack. When augmented, they add another functional 2d6 damage.
* This suggestion would basically make these spells 50% better, increasing their effect to 3d6 damage per turn. This would make this particular strategy (dual wielding with weapon enchantments) ahead of the curve and we'll have a hard time designing for players who don't pick this feat.
* An alternative, adding an augment to add the damage to your offhand weapon, would be too weak (adds 1d6 per mana instead of 2d6). Making the offhand weapon deal +2d6 instead would be ugly and not elegant.

Generally, the need to wield two enchanted weapons is probably better solved by giving your character magical weapons, or adding a spell that specifically works better (and is balanced) for dual wielding.

**Comment by mlenser** [comment]
As discussed: Somatic components aren't part of the system. And if/when they're added they wouldn't restrict TWF.

The second part was discussed and there was no immediate suggestion. It could be worked on further if anyone is interested.
