### ISSUE TITLE
Storm Adept/Master

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#322]
If both feats in #320 and #321 are created, then I would also suggest changing the Storm Adept and Storm Mastery feats to only apply to Lightning damage. As-is, both grant bonuses to twice as many damage types as all of the other "___ Adept" and "___ Master" feats.

(The Storm theme should absolutely be able to deal some Thunder damage, but the Sound theme should be its mastery.)

**Comment by itamarcu** [comment]
I also think that it's quite odd that the Storm theme is about two damage types instead of one, and breaks symmetry with the others. The connection between thunder/sonic damage and thunders and storms is not strong enough to justify it, IMO. However, it might be better to discuss this more extensively on a new issue or in Discord?

**Comment by mlenser** [comment]
Sound theme is removed #327
