### ISSUE TITLE
New Suffused Mechanical Feature? --> Update of Power Surge

### ISSUE THREAD

**Issue by Euthrosyne** [mlenser/kryx-rpg-issues#343]
Thinking about a new mechanical feature for the Suffused: the notion of sorcery points rose to the surface, but acquired through casting spells/expending stamina. You could scale it to the amount of mana/stamina expended on a spell/maneuver. These points could be used to:

- regain mana/stamina at a loss, efficiency wise
- increase the casting limit of a spell/maneuver
- cast a spell/use a maneuver in place of mana/stamina
- augment the next use of a power surge in some form
- augment your appearance, i.e. as you cast spells associated with your theme, you acquire traits associated with that theme, i.e. as you cast fire spells, magical fire begins to writhe around your body
- for some other purpose not yet delineated

There could also be an active drawback with accumulating too many sorcery points as your body becomes unable to contain the burgeoning magical energies, creating a dichotomy where the Suffused wants to run hot and cast a flurry of spells, but not run too hot and potentially burn out.

Thematically, it represents the Suffused tapping deeper and deeper into its source and its source resonating with that usage of power and encouraging even more use of that power. As a Fire Suffused channels their magic more and more, it becomes easier to do so or has greater effects, but with greater and greater amounts of risk.

Thinking about this from a balance-perspective, I feel that the drawbacks would have to appear early on, but not be overly crippling until a character has truly gone overboard. This would compensate for the expanded capabilities of the class and create tension in how players handle their Suffused. As @mlenser noted, what will make or break the feature is probably how mechanically balanced it will be, however.

It could exist as a short-term feature a la a Limit Break where a Suffused could activate it and for the next minute, spells/maneuvers open the spigot of the origin a little more, allowing the Suffused enhanced capabilities, but at the risk of losing control as the spigot is opened more and more. Spells/maneuvers that cost more resources would open the spigot proportionally more.

It could also exist as a passive that the character has to modulate over the course of a day before short rests, i.e. spells/maneuvers used create another resource that itself can be used for other features, but using this resource does not deplete it, but instead increases it

There could (and I feel should) also be an option for a release valve of sorts, but one that sharply limits the Suffused for a short period of time to represent the Suffused stepping back from the edge and regaining control of themselves at the cost of needing to concentrate on calming their magic down, i.e. release/disperse all sorcery points, but cannot cast any spells except cantrips until the end of the next turn.

Per @DalenWBrauner :
> This to me is reminiscent of the Consumptive Power feat, but in a good way. I like the idea of a suffused tapping into or bringing out their innate magical energies in a way that other classes simply can't keep up with, but at some kind of physical cost or toll to the user. Or perhaps like irresponsibly opening the faucet a bit wider on the magic that flows through you.

> Some other potential drawbacks we could play with:

> - Exhaustion
> - Temporary decreases to Mana Limit
> - Will or Fortitude saves to prevent indescriminate Power Surges
> - Will or Fortitude saves to maintain control over your character

> I don't think the boons should necessarily be remenscent of Metamagic in terms of spellcasting finesse, but I like the idea of more "raw magic" bonuses like 'free' augments, etc.

**Comment by mlenser** [comment]
As discussed on discord:

We could refine the power surge feature to charge up, and then you can release it. We can have it automatically release after some time with a DC getting higher for how many levels you have. When you control burst it, you can target it toward a creature or creatures. If it bursts on its own, then its an area around you. Super flavorful and fun.

**Comment by itamarcu** [comment]
My mechanical concept suggestion (lacking any flavor text, and the name can change):
> - 2nd/3rd level feature
> - Whenever you expend mana or stamina dice, you gain an amount of raw energy equal to the number of stamina dice expended or twice the amount of mana expended. This raw energy can keep accumulating, though they reset to 0 when you finish a long rest.
> - Whenever you gain raw energy, make an ability check with your spellcasting ability, against a DC equal to the total amount of raw energy you now have. You succeed automatically if the DC is equal to or lower than your level, though you may choose to fail. On a failure, you must release the accumulated power in an uncontrolled way, as a 15-ft-radius sphere centered on you.
> - As a bonus action, you may choose to release the accumulated power in a controlled way, directing it in a 15 ft cone or 30 ft line, away from you. 
> - When you release the accumulating power, all creatures within the area take force damage equal to the amount of raw energy you accumulated, and you lose all of your raw energy.

This is the basic idea - you accumulate energy points when you use spells/maneuvers, you make checks, if you fail you make an explosion around you (that also harms you), if you succeed you keep the power and may release it in a better way as a bonus action.

(I chose to make it spellcasting ability check instead of fortitude save because I think controlling your power is about your mastery of your talent and not about how much you can withstand - also because I don't want to make Suffused too dependent on fortitude)

Now, we can add various ideas to this core, like.... (choose some subset of these, and add some of your own. I'm just throwing out cool ideas here)

> - At the end of your turn, if your amount of raw energy is 5 or more, you gain temporary hit points equal to that amount.
> - While your amount of raw energy is 10 or higher, whenever you deal damage with a spell or a maneuver you can deal additional damage equal to your spellcasting ability.
> - While your amount of raw energy is 10 or higher, you are hasted 1.
> - When you release 10 or more raw energy at once, the length or radius of the area is doubled, and you suffer a level of exhaustion.
> - When you release 20 or more raw energy at once, the length or radius of the area is doubled again, and your mana and stamina limits are reduced by 1 until you finish a long rest.
> - When you take damage you must make a check to see if you can hold onto that power (as if you just gained raw energy). (as usual, you auto-succeed if you have less raw energy than your level or your ability modifier, so this will only trigger when you have a lot of energy and get hit)
> - When you cast a spell with less mana than your mana limit or use a maneuver with less stamina dice than your dice limit, you don't have to make a check to maintain your control over the accumulating energy.
> - When you release the accumulated raw energy, you can choose to use the damage type of a spell you cast in the last minute, instead of force.
> - When you release the accumulated raw energy, you can choose to hold onto some of the power. If you do, you suffer a level of exhaustion, and you only release half of your accumulated raw energy (rounded down).

**Comment by Euthrosyne** [comment]
Here's what I was writing up last night, it's fairly similar to your suggestion, @itamarcu, except my suggestion has them start to make saves at a threshold as opposed to when they get a counter any time. 

Wellspring of Power: [2nd] [5th] [9th] [13th] [17th]

Magic lives and breathes in the veins of a Suffused, temperamental and wild, and control of that power is ever-illusive, for their magic is at once seductive and self-destructive. Every time they call upon their power, it becomes easier to channel, but at the risk of them losing control. To compensate, Suffused can vent off this power, unleashing their magic onto their surroundings.

As a Suffused expends mana or stamina to use a maneuver, it gains charge counters equal to the amount expended, and these charge counters have a multitude of effects.

-  If the Suffused so wishes to expend a counter, they do so as they cast a spell or use a maneuver, causing an eruption of magic that manifests itself in a way based on the theme of the spell cast or a chosen default theme. (It could also manifest based on the origin of the Suffused, but wording). This eruption can be directed and controlled towards other creatures, including the Suffused themselves. As the Suffused levels and grows more competent in controlling its magic, it can increase the efficacy of this surge by expending more counters.  

- In lieu of expending a counter, the Suffused can let them build up until reaching a threshold.This threshold grows every time your mana limit increases.  Once a Suffused reaches the threshold, each additional counter added introduces additional volatility, which is represented by a making an ability check with your spellcasting ability (This was a really nice touch, @itamarcu, I hope you don't mind me also using it) against a DC equal to the amount of counters you possess or 10, whichever is higher. 

Should they fail to save against this DC, they lose control of their magic, and an uncontrollable power surge centered on them in a 15 ft radius is released, affecting all creatures including the Suffused, and all charge counters stored to that point are lost. 

Option A

> For every three counters generated from mana or every two counters generated from stamina expended, the Suffused can reduce the cost of its next spell or maneuver, respectively, by one mana or stamina. Any spells or maneuver cast in this way, however, would add counters and thus trigger a check. As the Suffused becomes more proficient and able to handle more energy, it can expend more counters to reduce the cost of higher level spells/maneuvers.

Option B

> Once the Suffused has reached a threshold, they can either choose to expend all points to trigger a power surge with additional features/bonuses or instead continue to build up power. These features could include increasing the number of targets, increasing the amount of damage, adding effects to damage, granting self temporary hit points as an energy shield, etc, etc, etc

**Comment by Lamorak11** [comment]
Very cool ideas, although I would certainly advise keeping the number of checks/saving throws that a suffused character needs to make while using such an ability to a minimum, to avoid the twin horrors of over-the-top book-keeping and analysis paralysis. 

I think keeping things as simple as possible to run while maintaining the great thematics you have going here is important.

**Comment by itamarcu** [comment]
For my suggestion - this isn't written explicitly (for the sake of brevity and elegance), but this check is only really made when you go past your "threshold" - at high levels it's equal to your level, and at low levels it's equal to 1+spellcasting ability, so 4-6, because below that you'll always roll high enough. Even at 5th level, there's only a 5% chance you'll roll below a 7.
So, in low tiers, you'll only start risking it after expending about ~4 mana or 8 stamina and never releasing the energy. These rolls will only be made 1-2 times per round and probably only after the first fight of the day. I don't think it's too many rolls - it's comparable to concentration saves, especially since once you fail it, it will take some time before you charge up again for the risk to reappear.

It might be better to clearly call it a threshold (so that player swill use this term too) - maybe I can edit it to say that directly.

**Comment by Euthrosyne** [comment]
I think we both have some of the fundamental structure down: 

1. Every time a spell or maneuver is used, the Suffused gets a charge proportional to the cost of the ability.
2. These charges can be used to augment the Suffused in some way.
3. As the Suffused gets charges, there are needs to be a mechanism that provides both reward and risk and that the player can opt in to and opt out of this mechanism by modulating the amount of charges.

What other fundamentals need to be included?

One thought that came to mind is that the mechanism has to provide appropriate and meaningful risk at every level, but figuring out a threshold that applies as equally to a level 2 Suffused as it does to a level 20 is difficult.

**Comment by mlenser** [comment]
I think the "power up and then expend the energy or it bursts out" is more flavorful and mechanically easier to manage. :+1:

**Comment by Marcloure** [comment]
Just a note on resources that go up and down on a round base: they can be hard to manage and exhaustive to play with.

I played with the Pathfinder's Kineticist for a while, and I had to work like an engine to manage getting those numbers up and down, and to analyse whether or not I should expend my charges or not, and how dangerous it is to continue charging up. You have to consider so much more to cast a spell, and that consumes a lot of effort from the player beyond picking the right spell.

**Comment by itamarcu** [comment]
Alright, here's a simpler/tighter suggestion (after discussion on discord). I'm separating the paragraphs to also comment about a few of them.

> **Sorcery Overflow** - 2nd/3rd level
> Magic lives and breathes in the veins of a Suffused, temperamental and wild, and control of that power is ever-illusive, for their magic is at once seductive and self-destructive. Every time they call upon their power, it becomes easier to channel, but at the risk of them losing control. To compensate, Suffused can vent off this power, unleashing their magic onto their surroundings.

> Whenever you expend mana or stamina dice, you accumulate an amount of raw energy equal to the number of stamina dice expended or three times the amount of mana expended. This raw energy can keep accumulating, though it resets to 0 when you finish a long rest.

> You have an energy threshold, as shown in the Energy Threshold column of the ((subclass name)) table. 

(Threshold will be equal to three times your level, probably. This might change as calculations are being made.)

> As long as your raw energy is equal to or greater than your threshold, your attack rolls have advantage and creatures have disadvantage on saving throws against spells you cast.

(this is the primary reason you'd be tempted to keep going and accumulate so much energy. It might be unbalanced and might need to be changed - potentially becoming stronger at higher levels. Other ideas are... extra damage (needs to balance AoEs and single-target), hasted condition (better for bloodragers), static bonus to attack rolls or malus to enemy saving throws, temporary hit points)

> After each time you accumulate raw energy or take damage above half your threshold, if your amount of accumulated energy you have is equal to or higher than your threshold, your magic threatens to get out of control: Make an ability check with your spellcasting ability, against a DC equal to the total amount of raw energy you have minus your energy threshold (for example, if your amount of energy is 21 and your threshold is 12, the DC is 9).

> On a failure, you must immediately release the accumulated power in an uncontrolled way, as a sphere centered on you. The sphere's radius is a number of feet equal to half the energy, rounded up to closest multiple of 5.

> As a bonus action, you may choose to release the accumulated power in a controlled way, directing it in a cone or line away from you. The cone or line's length is a number of feet equal to the energy, rounded up to closest multiple of 5.

> When you release the accumulating power, all creatures within the area take force damage equal to the amount of raw energy you accumulated, and you lose all of your raw energy.

> Starting from 7th level, when you fail the check to hold onto the energy, you may choose to instead succeed and take force damage equal to half the amount of raw energy. This damage can't be prevented.

> Starting from 13th level, when you release your accumulating power in a controlled way, you may choose to release only half of it. You lose half of your raw energy (rounded down), deal damage equal to that amount, and in a range depending on that amount.

---

The goal here is that the sorcerer casts about 4 spells at their mana limit, and then reaches their threshold. At this point, they should either slow down (using more cantrips and non-spell actions) or keep going and risk an uncontrolled release which will damage them and those near them - should happen after they release a total of about 7 mana over the turns after they reached the threshold.

They can also release the power manually, instead of trying to reach the risky peak. This costs a bonus action each time, the range is technically smaller but much better-controlled, and they can spread the damage around - this is the safe option, and it should functionally be similar in power to the Power Surges.

**Comment by itamarcu** [comment]
By the way, a note: apparently the Sorcerer has 30 mana at highest level, while the Bloodrager has 15 mana, or 8 mana plus 23 stamina. Functionally the Bloodrager has half as much energy. 

I don't know how to deal with this - I'm not sure why this is, though I guess it's because the bloodrager has more powerful features to cover up for less of these resources. In that case, though, there's basically two options -
- Bloodrager's description of this feature will be different, where bloodrager gets twice as much value out of the energy expended, or sorcerer gets half as much value. Maybe only change the threshold.
- Bloodragers just have less energy and that's okay, they're balanced around it, so this feature will be less important to them.

**Comment by Euthrosyne** [comment]
One thought regarding this iteration: Are we removing the flavor/functionality that invoking a theme influences in some way how the energy is released? Is that feature shifting to the origins/metamorphosis rework?

**Comment by mlenser** [comment]
> the Bloodrager has half as much energy [...] I'm not sure why this is
The Sorcerer is a full caster. The Bloodrager is a half-caster gish. All archetypes follow this pattern. See Acolyte: Priest/Paladin/Avenger, Alchemist: Blood Hunter, Chemist, Mutant, Mage: Wizard/Magus, etc.

**Comment by mlenser** [comment]
> As long as your raw energy is equal to or greater than your threshold, your attack rolls have advantage and creatures have disadvantage on saving throws against spells you cast.

This is broadening out to an area that will result in much much higher damage from the Sorcerer and Bloodrager than their counterparts.

Power Surge needs to be rather limited in its effectiveness. It adds a small bit of damage on top, but not significantly more power like this would.

_____________

> After each time you accumulate raw energy or take damage above half your threshold, if your amount of accumulated energy you have is equal to or higher than your threshold, your magic threatens to get out of control: Make an ability check with your spellcasting ability, against a DC equal to the total amount of raw energy you have minus your energy threshold

The wording here is incredibly complex and I mentally stopped reading very quickly. I agree with Marcloure. This feature needs to not be taxing on the player.

__________________

I think this needs to be simplified significantly. What I envisioned was basically power surge, but instead of immediate damage it would charge up a bit and then be used. The goal has to be around the same power level as the current power surge. There isn't room for more than that power level.

**Comment by itamarcu** [comment]
Simpler suggestion:

> **Power Overflowing** - 2nd level feature
> Magic lives and breathes in the veins of a Suffused, temperamental and wild, and control of that power is ever-illusive, for their magic is at once seductive and self-destructive. Every time they call upon their power, it becomes easier to channel, but at the risk of them losing control. To compensate, Suffused can vent off this power, unleashing their magic onto their surroundings.

> Whenever you expend mana or stamina dice, you accumulate an amount of raw energy equal to the number of stamina dice expended or three times the amount of mana expended. This raw energy can keep accumulating, though it resets to 0 when you finish a long rest.

> You have an energy threshold, as shown in the Energy Threshold column of the ((subclass name)) table. When your energy reaches your threshold, you become energized. 

(it's 3 times your level for sorcerers, and 1.5 times your level for bloodragers, since they have half as many resources.)

> While energized, the power of your magic peaks. When you deal damage with a spell or a weapon, you can deal extra force damage equal to half the energy accumulated. If you're dealing damage to multiple creatures, spread the extra damage as evenly as possible between them.

> While energized, whenever you accumulate more energy or take damage above half your threshold, your magic threatens to spill out. Make a spellcasting ability check against a DC equal to 10 or to how much excess energy you have beyond your threshold, whichever is higher.

> On a failure, you must immediately release all of the accumulated power in an uncontrolled way, as a 15 ft sphere centered on you. You become slowed 2 until the start of your next turn.

> When you release the accumulating power, you lose all of your raw energy, and all creatures within the area make a Dexterity saving throw against your spellcasting DC. A creature takes force damage equal to the amount of raw energy you lost on a failure, or half that much on a success. If you released the power uncontrollably, you automatically fail the saving throw, and the damage can't be reduced or prevented for you. 

> You can also choose to carefully discharge the power in a controlled fashion. As a bonus action, you can release all accumulated power by blasting it away from you in a 15 ft cone or 20 ft line.

And some added benefits at higher levels (these numbers are just gut feelings):

> Starting from 7th level, when you fail the check to hold onto the energy, you may choose to instead succeed and take force damage equal to the amount of raw energy you accumulated. This damage can't be reduced or prevented.

> Starting from 10th level, when you release the accumulating power, the length or radius of the area is doubled (30 ft cone, 40 ft line, or 30 ft radius sphere). In addition, when you release the power in a controlled way, you can choose to target a single creature you can see within 60 ft, instead of a line or a cone.

> Starting from 13th level, when you release your accumulating power in a controlled way you may choose to release it only partially. You only lose half of your raw energy (rounded down), and deal damage equal to that amount.

**Comment by Euthrosyne** [comment]
How do people feel about the loss of thematic inclusion? It makes the feature much simpler to implement, but does get rid of a lot of flavor, especially the utility elements. Should the power released change depending on what themes are used to cast a spell as it does now?

**Comment by itamarcu** [comment]
@Euthrosyne - Good question. I was thinking that a Force blast/explosion is as flavorful as you can be with "too much magic buildup", though I can see how it'd make sense for a fire sorcerer to have a fiery explosion, for example. Alternative mechanics for releasing the blast (e.g. Life making it heal everyone nearby) are interesting, but they would add *a lot* of complexity to this idea.

Maybe once this idea develops further we could combine it with the currently-in-progress sorcerer subclasses, so that each subclass would have its own small twist on this feature. For example, the draconic one could have a chance to frighten creatures while it's energized, the phoenix fire would make the released energy fire damage and add the burning condition, the antimagic sorcerer could accumulate extra energy when countering/dispelling enemy spells, and so on.

Could also give them the ability to "spend" energy equal to e.g. half the threshold for a thematic non-damaging effect like an earth shield or a healing aura, though at that point it might as well just be using energy for mana, and we're trying to avoid that.

**Comment by mlenser** [comment]
Power Surge reworked so that you store and expend surges after you cast a spell or use a maneuver

**Comment by mlenser** [comment]
Closing this as Power Surge was reworked a bit.
