### ISSUE TITLE
Increase identify spell DC

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#349]
Currently it's 10 + mana, but I think 10 + 2 * mana scales the DC better.

**Comment by mlenser** [comment]
I wrote about this last time we made this change. See https://github.com/mlenser/kryx-rpg-issues/issues/300#issuecomment-636183219.

It's purposefully easier to identify a spell as Counterspell and Dispel Magic are harder.

### Summary:
- Identifying requires proficiency
- ~70% chance to identify a spell and get advantage on the counterspell. Prof+ability vs mana cost. At tier 2 that's d20+3+3 vs dc 12, or 70% ([anydice](https://anydice.com/program/1c2fa))
- ~50% chance to stop a spell cast by a caster of equal level when you cast counterspell at the same mana as the spell. ~75% chance to stop the spell if you identify the spell first. So about ~**67.5% chance to counterspell** (0.7x0.75 + 0.3x0.5)

**Comment by Marcloure** [comment]
Ah, yes. I understand the issue with counterspell. It's just that a player of mine found this very powerful scroll of Meteor Swarm, but the DC to identify it turned out to be kinda low. Today I was DMing for my second group, and one of my players wanted to identify if a spellcaster was using something aggressive or not, but again, the DC was 12.

But I get the issue about trying to help counterspell there.

**Comment by mlenser** [comment]
By RAW there is no check to identify spells. Wizards just spend time to add it to their spellbook as long as the spell qualifies.

It isn't really all about counterspell. If your character has proficiency in the skill, they should be fairly good at identifying spells in that power source. Without proficiency you can't even do it, so the basic check is "do you have proficiency or not". Once you do, the check is fairly easy, by design.

**Comment by mlenser** [comment]
@Marcloure I actually decided to go this route. See https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=1867996895 for the calculations
