### ISSUE TITLE
Two weapon fighting problem part 2

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#351]
The other side of the coin to two weapon fighting. TW, as is, is the best martial option to a wizard forced into meele (that for some reason didn't take any damaging cantrips) or a pleb, with no fighting styles, and even every monster proficient in a light weapon.

Fighting with two weapons is hard (supposedly, never tried) but it is the best strategy even if you are not trained in it (fighting style or feat). I will spare you all of the math, but with a 55% hit chance, two hatchets or clubs (simple and light) deal an expected damage of around 4 damage (considering +1 strenght, a pleb). With that hit chance, this expected damage is equivalent to a single attack with a 2d6 weapon ( (7+1)/.55 =~4). There are no 2d6 weapons anymore.

That is equivalent of saying that if you are trained in all weapons, but not specialized in any style, wielding 2 clubs have higher expected damage (and higher minimum damage, because you are more likely to hit at least once) than a great-sword. That seems weird to me.

I have no idea how to make it more believable, but someone proficient with a weapon has no motives not to dual wield it (if he is building for damage). How can we explain not every monster in the book that has two hands not dualwielding their weapons, since it's that much better?

**Comment by mlenser** [comment]
Lets assume an ability mod of 1 since these people aren't fully martial:

### TWF:
- Clubs/Daggers/Katars/Sais/Sickles: 2d4 + 1 = 6
- Hammers/Hatchers: 2d6 + 1 = 8

### Other simple weapons
- Greatclub/Quarterstaff: 1d8 + 1 = 5.5

### Other factors
- TWF has to hit both attacks, which is less likely to produce the full damage, but more likely to get some damage.
- Weapon proficiencies. A Wizard does not have proficiencies in Hammers/Hatchets

So for the normal simple weapons (not hammers/hatchets) the damage is slightly higher for TWF vs one bigger weapons, but a bit more variance and some reliability to deal _some_ damage.
This seems totally fine?

**Comment by mlenser** [comment]
Note: There is probably something wrong with Hammers/Hatchets. I'll need to look at them again.

**Comment by itamarcu** [comment]
I also agree that this is a bit of a flavor fail - spellcasters in most media, when forced to use a melee weapon (and not unarmed), will usually either use a quarterstaff or a single one-handed weapon (dagger or club, mostly). I can't think of any dual-wielding mage, except for cultists, perhaps.

By the rules, dual-wielding is just stronger (more damage on average and more consistently able to land at least one hit per turn. Only lower opportunity attack damage is a real drawback). I don't think it's "totally fine" - clearly, dealing 6 damage is better than dealing 5.5.

One factor that alleviates this is the fact that, even though it's not part of the Kryx RPG rules (yet), full spellcasters are expected to keep a hand free or holding an arcane focus (and a quarterstaff, which is a two-handed weapon, can be one). If a wizard is normally holding a wand in one hand and a dagger in the other, they won't be able to dual-wield until they stow the wand and pull a second dagger (which should delay them a little bit). It's even slower for spellcasters who just keep two of their hands empty.

For non-spellcasters it's a bit harder to justify. Why is a [Goblin](https://www.kryxrpg.com/monsters/goblin) not holding two scimitars? Why does a [Commoner](https://www.kryxrpg.com/monsters/commoner) hold a single club instead of two clubs (or even a greatclub, really)?

Perhaps this could be solved by only allowing two-weapon fighting if you have a certain quality (proficiency with martial weapons, a high enough dex/str, some new class feature, etc).

**Comment by Paulorpribeiro** [comment]
Just some number to add to the discussion. The expect damage is factoring in the to hit chance. Its expected damage after attack (action), not after hit. 

H = hit chance = 55%
M = miss chance = 45%

Two daggers: 
HH x 6 -> two hits, average dmg of 2d4+1
HM x 3.5 -> hit+miss, average dmg of 1d4+1
MH x 1d4 -> miss+hit, average damage of 1d4 (second hit is with OH)
Total: 1.815+0.866+0.618 = 3.3
Other weapons with a single attack
1d8 -> 0.55 x 5.5 = 3.02
1d10 -> 0.55 x 6.5 = 3.75

So two dagger are better than two handed staff , a little worse than two handed battle axe.

Two hatchets would be slightly better than two handed battle axe and a little worse than great sword or maul.
Also, better to hit chance and advantage will probably favor the two weapons better

**Comment by mlenser** [comment]
> I don't think it's "totally fine" - clearly, dealing 6 damage is better than dealing 5.5.

For PCs this is a tertiary option. 0.5 damage difference which is less after attack chances are taken into account. This is not worth "fixing", especially when this is how it is by RAW.

___________

> Total: 1.815+0.866+0.618 = 3.3

I'm not sure whow you got these numbers. 0.55x3.5=1.925, 0.55x2.5 = 1.375. All together that's 3.3. But both attacks hitting is a 30% chance. There is far more math that could be done here if we really cared to flesh it out, but this is not a complete comparison.

_______________

In D&D 3.5 spellcasters can dual-wield daggers or use a simple two handed weapon without specific training.
In PF spellcasters can dual-wield daggers or use a simple two handed weapon without specific training.
In 5e spellcasters can dual-wield daggers or use a simple two handed weapon without specific training.
In PF2e spellcasters can dual-wield daggers or use a simple two handed weapon without specific training.

Based on that, I don't see why it should be restricted.

**Comment by mlenser** [comment]
> Why is a Goblin not holding two scimitars? Why does a Commoner hold a single club instead of two clubs (or even a greatclub, really)?

This logic is really stretching it. "Why don't all NPCs have optimized weapons, strategies, and tactics".

NPCs are different. Many have single swords for flavor reasons or training reasons or all kinds of reasons. If we wanted to optimize NPCs then they wouldn't use a single weapon (not considering the dueling fighting style). They would then use a weapon + a shield, TWF, or a big weapon. Which, based on the numbers for PCs are all equally balanced - far more than RAW is. NPCs aren't built the same way, but the differences here are very small and if you have optimized NPCs then they should probably get fighting styles and then they're just as balanced as PCs.

**Comment by itamarcu** [comment]
This is just a minor flavor issue - I think I'm fine keeping it as it is, and explaining that wizards/goblins/commoners want to keep an empty hand for other purposes. I understand if it's too minor or too difficult to change this part of the system.

> Why is a Goblin not holding two scimitars

Yeah, my bad for bringing this into the argument - it's not really relevant and wouldn't be fully fixed by a dual wielding change.

> In D&D 3.5, PF...

I googled a bit - In D&D 3.5 if you dual-wield you take a penalty of -2 to your attack rolls. In Pathfinder, you get a -4 and a -8. In Pathfinder 2nd edition, you get a penalty to your second attack no matter which weapon you're using, so there's very little reason to attack once with each weapon instead of twice with the same weapon. (all of these systems have a feat or ability to recude the penalty, but we're discussing unrained character)

Only in 5e wizards have no reason *not* to dual wield, if they get into a hairy situation.

But still, like you said, this is a tertiary option and might not be worth the time to handle.

**Comment by mlenser** [comment]
Hammer is no longer light and Hatchet is now 1d4.

**Comment by Paulorpribeiro** [comment]
The math I referred to is binomial chance calculation, where the expected result ( damage in this case is)
Chance to hit twice x appropriate damage + chance to hit first, miss second x appropriate damage + chance to miss first, hit second x appropriate damage + chance to miss both x appropriate damage (0 in this case)

The total chance is 100%, and the damage is applied as appropriate. 

What I wanted to demonstrate is that dual wielding a 1d4 weapons is roughly equivalent of wielding a 2d4 weapon and dual wielding a 1d6 weapon is roughly equivalent of wielding a 2d6 weapon. This is not valid after extra attack.

I think what jumps to my eyes is that wielding two weapons, which is supposed to be more complicated than wielding one, is more effective and everyone proficient can do it, so there is no reason not to, unless you specialize in something else.

It may not be worth "fixing it", just seems off to me.

**Comment by mlenser** [comment]
@Paulorpribeiro if you think it is a problem please find some 5e discussions about it (as this isn't unique to my system). If there is some kind of concensus that it is a problem  then I can take a second look.

**Comment by Paulorpribeiro** [comment]
Yes, the problem is persistent in D&D. The main difference is that in 5e RAW two weapon fighting costs at least a bonus action - which has much less options than here, but still - while in this system it is absolutely free. If you are proficient, you can fight with two of the weapons, its part of the training... It bothers me a little, mainly for thematic reasons, but mechanically it's better this way than any other fixes I can think of. Better leave it like that.

The only option I see is have multiple degrees of weapon proficiency (like skills, capable, proficient and expert) and go from that. This is a major effort though, and have many balance implications .

**Comment by itamarcu** [comment]
I agree with you, but @mlenser asked if you can specifically find discussions of 5e players who are also bothered by this. I think that would be helpful to see how much of a problem this is, and to see if others have thought of better fixes.

Personally, I think an easy fix would just be "full caster classes cannot use two-weapon fighting unless they have the dual wielder feat". I don't think any full-casting class (priest, chemist, wizard, druid, warlock, psion, sorcerer) is ever shown dual-wielding light weapons in popular fantasy media, or that *any* player build is based on being able to do this.
