### ISSUE TITLE
Prismatic Vortex should be updated

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#357]
[Prismatic Vortex](https://www.kryxrpg.com/spells/prismatic-vortex) looks like [Prismatic Spray](https://www.kryxrpg.com/spells/prismatic-spray) but every turn. Since Prismatic Spray was updated recently, the Vortex should be updated the same way, right?

**Comment by DalenWBrauner** [comment]
I would suggest leaving them as-is. While there was an overhaul of continual spells being added as augments to similar instantaneous spells, at first glance, I think there are just a few key differences here:
- Prismatic Spray is a Cone out from you, not a sphere. You can aim it in ways the previous spells can't. For comparison, Cone of Cold and Burning Hands didn't receive a "continual" augment.
- Prismatic Vortex is a cylinder that you can place 120ft away from you, unlike say Frost Nova, which continues out from your position. That's a valuable difference I'd suggest is worth keeping (though an augment to have the Vortex follow you would be cool).
- While the two have otherwise similar effects, they technically aren't identical (e.g. Indigo).

On a different note, it's a bit odd that a Vortex would be a cylinder, isn't it?

**Comment by mlenser** [comment]
Lookes this over. Vortex would be far too complex with the differences that Prismatic Spray has.
