### ISSUE TITLE
Dual wielder split

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#378]
I quite like the split, it was indeed overpowered was one feat, nice catch.

But the two weapon defense feat seems a little too weak. Perhaps add to it something like "If you have two weapons drawn and take the nimble defense or parry reaction, add 1 to the AC gained by the maneuver".

I always thought maneuvers should have more sinergy with feats.

**Comment by itamarcu** [comment]
A feat shouldn't add more efficiency to a maneuver, especially not a specific maneuver. That's bad design unless it serves a really specific flavor purpose, because then either the maneuver needs to be weaker for everyone without the dual wielder feat or somehow balanced in a way that specifically fits the feat.

I do agree it seems kind of weak, though. Maybe it could do something with dodging, disengaging, dashing, opportunity attacks, reflex saves?

**Comment by itamarcu** [comment]
Suggestion for [Two Weapon Defense](https://www.kryxrpg.com/feats/two-weapon-defense) improvement:
> You gain a +1 bonus to AC while you are wielding a separate melee weapon in each hand. **You can draw one or two melee weapons when a creature makes an attack against you, unless you are incapacitated (no reaction needed).**
> **As a reaction when a creature misses you with a melee attack, you can parry its weapon away, giving it disadvantage on the next attack it makes against you before the end of the turn.**

The first part is just intended to prevent the player from constantly walking around with two weapons drawn just in case of a sneak attack (plus, it's pretty epic to have a character unsheathe and then block a strike in a single, smooth motion).

The second part is my idea for an extra defensive benefit - using a reaction to grant disadvantage but in a restricted situation. It's not meant to be strong, just something that might come up sometimes. Could be nerfed further (this just felt elegant).

I also suggest renaming this to "Twin Parry" or "Twinned Defense" (these are both PF2e feat names) or "Dual Defense".

**Comment by Marcloure** [comment]
I like "Twin Parry" or "Twinned Defense"

**Comment by DalenWBrauner** [comment]
That second idea is cool, but I think it belongs in a maneuver, not a feat.

Is it not just +2 AC because replacing a shield with a weapon is too strong for this feat?

We could do +1 AC, and then a once-per-turn, no-reaction-required +1 AC bonus to a single attack against you. The flavor being that your weapon can assist in parrying, but while a shield is specifically designed for defense, a weapon can really only parry one other weapon at a time. The balance being that this doesn't help you if you're attacked multiple times in a turn, such as from multiattack etc. (But maybe that's also too maneuver-like.)

**Comment by mlenser** [comment]
I don't believe +1 AC to be weak. Lacking some flavor, maaaybe, but not weak.

It causes you to take 10% less damage. That's impactful.

_____

> You can draw one or two melee weapons when a creature makes an attack against you, unless you are incapacitated (no reaction needed).

Reaction to draw weapons? That's weird. If anything that belongs on tiny weapons like daggers. But even then, just do it on your turn.


> As a reaction when a creature misses you with a melee attack, you can parry its weapon away, giving it disadvantage on the next attack it makes against you before the end of the turn.

Sounds like a maneuver.

**Comment by itamarcu** [comment]
> But even then, just do it on your turn

The problem here is that this just wants players to constantly have their swords both drawn, to have the +1 AC. It's easy for someone to walk around a dungeon with a shield and a sheathed sword, interacting with objects and such, and this person will keep their defenses up. With this feat, players will feel pressured to keep both weapons drawn constantly, for the bonus AC. I'm suggesting that we add a sentence that makes them stop worrying about it. It's probably a good idea to limit it to light weapons, too.

**Comment by mlenser** [comment]
You can already draw two weapons as one. I don't think this area should be "fixed".

+1 AC is rather strong. Many people underestimate it, but it really makes a mathematical difference.

There could be a minor effect to go along with +1 AC, but it can't be super impactful.

**Comment by Paulorpribeiro** [comment]
I understand that a feat that "buffs" a specific maneuver is bad design. My idea behind it was " you get +1 AC until the end of your turn when you spend stamina", mimicking the design of suffused's power surge or psionicist's psichic redoubt. You gain a benefit when you spend resources. I just mentioned the 2 resction maneuvers, because it wouldnt fit if you use a maneuver like savage attack an gain an AC bonus. Perhaps the idea is just less absurd if it provides +1 AC when you take the dodge action? Just brainstorming.

But ok, maybe my suggestion was not very well written. And I kinda agree with @mlenser, the feat is not as weak as it is boring, and therefore needs a ribbon, not a buff.

**Comment by Marcloure** [comment]
Maybe you can't be flanked while wielding two weapons as an additional benefit?

**Comment by mlenser** [comment]
Flanking has nothing to do with multiple weapons.

**Comment by mlenser** [comment]
Two Weapon Defense renamed Twin Parry
