### ISSUE TITLE
Grappled weirdness

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#386]
There are several grappling-related weirdnesses in D&D 5e, and this system kept most of them. I think we should consider changing stuff around.

### The facts

- You can **start a grapple** by...
  - (PC) Replacing one of your main attacks (so it costs 1/2 an action for martial, or 1/5 for a monk, though this might not be intended)
  - Using a bonus action maneuver to grapple (many monsters have only this, e.g. [Oaken Bolter](https://www.kryxrpg.com/monsters/oaken-bolter))
  - (Monster) Having attacks that grapple on a hit, e.g. [Glabrezu](https://www.kryxrpg.com/monsters/glabrezu)
  - (Monster) Having neither of these other two options (e.g. [Barbed Devil](https://www.kryxrpg.com/monsters/barbed-devil)), and using your entire action to grapple
 You can **end a grapple** by...
  - Spending your entire action to attempt to escape
  - (PC) Replacing one of your attacks with a Shove attack, to shove the grappler away
  - Escaping or pushing some other way (usually action or bonus action, magic or maneuver).

### The problems
- How many times can you grapple/shove with the additional attacks given to you from being a monk?
- Why does "classically" escaping a grapple cost your entire action, while starting a grapple costs only one attack?
  - This creates asymmetry, where it's easier to debuff your enemy than it is to escape that debuff.
- Why does "classically" escaping a grapple cost your entire action, while shoving your way out of it costs only one attack?
  - As a result of this, players who have extra attack should never try escaping the normal way - shoving is more efficient and even lets you avoid opportunity attacks
- Why can't monsters with multiattack just replace attacks with grapple or shove attempts, like players can?
  - This creates asymmetry, it's more wasteful for a monster to escape a grapple than it is for a character (unless the monster has special traits or uses bonus-action maneuvers that push).
- Why aren't you allowed to grapple/shove with an opportunity attack? A lot of people online asked about this, and frequently the arguments devolve into "I think it's fine to allow" vs "that's against the rules".

### My suggestions
- Change the grappling condition's escape action to allow characters to benefit from extra attack.
- Add a rule that allows Multiattacking monsters to replace an attack with a grapple/shove (potentially limited to one per turn, if this is somehow broken).
- Decide if we want Monks to be able to grapple/shove a lot (as they get 4 or 5 attacks per turn)
- Allow grapple/shove as an opportunity attack (might need more discussion). Do note that it'd be less useful when monsters only need an attack (not an action) to escape.

**Comment by DalenWBrauner** [comment]
_I feel we should be addressing the list of priorities Kryx posted in discord first, but here are some thoughts:_

One strange consequence of allowing individual attacks to be replaced with a grapple is that, depending on your interpretation of the rules, a character can replace both attacks with grapple checks. If the value of a grapple is equivalent to the value of a single attack, then I suppose this is okay, but it certainly feels like a strange in practice. If you fail on the first, you can try again. If you succeed on the first... what do you do with your second attack? Your options are pretty limited now that you're grappling a target.

If we decide it would be good to reduce its usage to an action rather than in place of a single weapon attack, but it's important for some balance reason that Extra Attack improve a character's grappling ability, then an alternative could be to have it grant advantage on the check instead. (Or better, grant it as a seperate feature entirely at the same level.)

> players who have extra attack should never try escaping the normal way - shoving is more efficient and even lets you avoid opportunity attacks

I definitely agree we need to avoid trap options like this, but I'm unsure of the right solution. One possibility is to write explicitly into either the Escaping a Grapple rules or the Extra Attack feature that a single weapon attack can be used instead of an Action to attempt to escape.

> Allow grapple/shove as an opportunity attack

I'm not sure why this isn't already a rule, here or in RAW. Grabbing someone as they attempt to move past or away from you is visible in just about every piece of media with an action sequence. If grapple checks are equivalent to single weapon attacks for multiattack, then I don't see why it couldn't be used here. The Disengage action would still make you immune to these attempts, or you could the risk of attempting to move past without it, and possibly be forced to use your action to break a grapple if you fail. It provides meaningful player choices, enables weaponless solutions to encounters, and doesn't hamper creature mobility in any way they can't already address.

That said, if this capability is too powerful mechanically, this can be dampened by having grapple in place of opportunity attacks be made at disadvantage. This also feels in-flavor to me, as grabbing someone as they unexpectedly run past you should be more difficult than going out of your way to approach and grab someone on your turn.

**Comment by mlenser** [comment]
> How many times can you grapple/shove with the additional attacks given to you from being a monk?

Similar to the RAW Monk at low levels and RAW Fighter at high levels. Not a problem, imo

> Why does "classically" escaping a grapple cost your entire action, while starting a grapple costs only one attack?

Ask the D&D 5e designers, not me. I don't think this is a problem. If you weaken the escape mechanism then many creatures based on grappling become much weaker.

> while shoving your way out of it costs only one attack?

I can't find any strong evidence about this online. But I would say that the rules specify how to escape a grapple:
![image](https://user-images.githubusercontent.com/235857/85458161-154dbe00-b5a1-11ea-8e5a-e622cc0ee09c.png)

Spells like thunderwave and other options exist, as specified on PHB 290, but I wouldn't allow a player to bypass those escape grapple rules and use other rules (which are much easier) in their place.

> Why can't monsters with multiattack just replace attacks with grapple or shove attempts, like players can?

What is stopping them? The grappling rules don't specify PC rules: "If you’re able to make multiple attacks with the Attack action, this Attack replaces one of them."

Multiattack would fit.

> Why aren't you allowed to grapple/shove with an opportunity attack?

I would not allow this. You get 1 melee attack. There are other cases as well like Haste.

**Comment by mlenser** [comment]
This discussion seems out of the scope of my ruleset. Core D&D systems like grappling should be discussed on other forums and if there is a concensus then a change could be made, but it doesn't look to be the case here. Feel free to take up the debate on another forum and report back if you get substantial response to the issues you raise.
