### ISSUE TITLE
Consider weapons as skills instead of weapon proficiency

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#411]
Goals of weapon skills:
- **Flavor:** Skills are handled in a more fine-grained way instead of a broad way that is essentially "every martial can use every weapon". I don't believe that is a flavorful solution. While this will surely cut both ways in the positive and negative, I believe the positives can outweigh if this is executed correctly.
- **Consistency & Simplicity**: Weapons would use the proficiency system completely from capable to proficient. This would be worthwhile to cut down on rules. Other systems (star wars edge of empire, fantasy age, and I'm sure others) use skills/ability tests to determine if a weapon hits or not so this is a pretty common solution in other RPG systems.
- **Learn new weapons**: Characters can learn new weapons or improve in their current weapons, creating a more flavorful character.

Regarding **tax**: Martials would get more weapon skills allotted so they can pick up a type or two. But "tax" is a word that should really mean tax. By the same logic all skills are a "tax", which I don't believe to be the case. They're ways to define your character.
Regarding **forcing certain weapons**: This is how I see the vast majority of characters played. A character is built with an idea in mine of using axes, swords, hammers, or spear-like weapons. Rarely do I see characters cross over. It almost always happens because a GM forces them to do so via magic loot (typically swords).
This "problem" would also exist with weapon-type feats suggested above.

**Comment by Marcloure** [comment]
My issues with this:
- Attacks already work like skills. In RAW, they are calculated the same way a proficient Str or Dex skill would be. Here we have levels of proficiency, and there are effects that only apply to skills, so those is the main difference, but:
- I don't see reason to add levels of proficiency to attacks. Players already stick to their favored weapon (as you mentioned), so they will lose almost nothing by not being good with other weapons, but they will gain a bit of attack bonus with their favorite. I would lose any day 97% of a character's weapons proficiencies to gain a +1 to attack.
- Effects that give (dis)advantage to all ability checks would need to be removed, since attacks are much much more important than skills. We could make them grant (dis)advantage to all skills that are not attacks, but then we are adding complications to solve a problem that we created in the first place.
- Everyone would be expert with their favored weapons, I wouldn't they be? So that is a 1 higher attack for everyone. The same is not true for skills because everyone uses a variety of them, and when you invest in a skill, you lose in another. That is considerable, since you can't beat any challenge with the same skill, but you can win every combat with the same weapon.

**Comment by mlenser** [comment]
Alchemical save DCs are now handled via the Alchemy skill, Maneuver save DCs are now handled via the Weapons skill, and Spell attacks and spell save DCs are now handled via magic skills.
