### ISSUE TITLE
Add more Cosmos spells

### ISSUE THREAD

**Issue by laserbison** [mlenser/kryx-rpg-issues#440]
Magic class progression specifies the option to 'Learn a new spell from a theme you know in your power source. The spell must cost equal to, or less than, your mana limit. If the spell costs 2 or more mana you must know a number of spells from the spell’s theme equal to the spell’s mana cost minus 1"

Cosmic spells start at 2, so there's no way for mages to learn them without acquiring a spellbook and having spent an arcane discovery on a theme they can't learn spells in. Suffused are just plumb out of luck.

**Comment by DalenWBrauner** [comment]
If the ideal solution is to create more Cosmos spells, I'm curious as to which of the following flavors / thematics are thought to fit the theme well:
- Vacuum of Space, e.g. [Steal Breath](https://www.kryxrpg.com/spells/steal-breath)
- Space Dust, e.g. a unique version of [Sand Cloud](https://www.kryxrpg.com/spells/sand-cloud)
- Literal Sunlight and Moonlight, similar to the [Daylight](https://www.kryxrpg.com/spells/daylight), [Sunbeam](https://www.kryxrpg.com/spells/sunbeam) and [Moonbeam](https://www.kryxrpg.com/spells/moonbeam) spells
- Astrology, e.g. a unique version of [Augury](https://www.kryxrpg.com/spells/augury) or [Fortunes of Fate](https://www.kryxrpg.com/spells/fortunes-of-fate)
- Spells related to the Astral Plane (I believe we discussed this should stay seperate)
- [Wish](https://www.kryxrpg.com/spells/wish)ing upon a star?

**Comment by itamarcu** [comment]
* Steal Breath can be renamed "Sudden Vacuum", or even simply added to the theme as is.
* Space Dust - not really sure if that's thematic? When I think about space stuff I don't think about dust or small particles. Maybe something like a comet's trail or a gas planet could be relevant.
* Light stuff - maybe?
* Astrology - I'd rather not, because the link between outer space and fortune-telling is the same as the link between sheep and [Haruspicy](https://en.wikipedia.org/wiki/Haruspex). The beast theme can't do divination, so Cosmos shouldn't either.

I suggest:
* Cosmic Radiation - take [Blinding Light](https://www.kryxrpg.com/spells/blinding-light) and replace being blinded with being poisoned (or even burning). You can make a bunch of spells with different shapes that all deal with cosmic rays, gamma rays, 
etc - see https://en.wikipedia.org/wiki/Health_threat_from_cosmic_rays for inspiration.
* Orbits - very thematic. We could use [Floating Object](https://www.kryxrpg.com/spells/floating-object), maybe. [Warding Winds](https://www.kryxrpg.com/spells/warding-winds) can be easily reflavored to be about a swarm of tiny asteroids that spin around you and protect you.
* Supernova - explosion stuff, possibly like Fireball but radiant light, and pushing/poisoning instead of burning? Possibly only centered on yourself.
* Gravity - should really decide if it's the same theme or a different theme. If it's the same theme, there could be a bunch of spells that pull creatures into a location. Levitate would make sense too (low-G). A black hole would make sense too - just reflavor [Maelstrom](https://www.kryxrpg.com/spells/maelstrom).
* Electromagnetism?

More inspiration here - https://powerlisting.fandom.com/wiki/Category:Cosmic-Based_Powers

I really think we should decide first if Cosmos and Gravity are different.

**Comment by laserbison** [comment]
I personally like the idea of a produce-flame like cantrip- either literally produce flame or a radiant version to better capture the idea of conjuring a little star mote. Light and firebolt are pretty iconic wizard spells that wizards don't have easy access to so it would fill a good niche

I like fireball for that same reason, but it's a little harder to thematically justify

**Comment by itamarcu** [comment]
Yeah, a minor mote/meteor as a cantrip would make sense.

> wizards don't have easy access (to fireball)

That's getting off-topic, but... have you looked at the wizard class? They get so many spells and arcane secrets that I'd be surprised if a non-fire wizard who wanted this spell didn't get it. Plus, I'm personally of the opinion that this spell is iconic because it's overpowered/over-reliable in 5e, and in this system it wouldn't be that anymore, so this is a good opportunity to create less stereotypical D&D wizards!

**Comment by laserbison** [comment]
> That's getting off-topic, but... have you looked at the wizard class? They get so many spells and arcane secrets that I'd be surprised if a non-fire wizard who wanted this spell didn't get it. Plus, I'm personally of the opinion that this spell is iconic because it's overpowered/over-reliable in 5e, and in this system it wouldn't be that anymore, so this is a good opportunity to create less stereotypical D&D wizards!

Yeah, maybe "easy" was too strong a word there. I meant more like, default. If you know what you're looking for, you can access almost any spell you want as a wizard for sure- in my opinion fireball specifically is such a iconic wizard spell in popular culture (wizards in most RPGs, TTRPGs, and even in shooters or even mobile games with any wizard themed classes or characters shoot a ball of fire that explodes), and it's weird to me that there's no way to access it in the arcane power source. 

This is entirely a taste thing, and I don't count that as a criticism of the system at all. There's also something to be said about how the Arcane power source has this identity about being more about the high concept metaphysical and fundamental forces of the universe. In my opinion, I like the idea of having "stereotypical" builds (like the kind you see as generic "wizard" or "cleric" enemies) as easy and obvious to build for new players. New players who are drawn to DnD in my experience want to build out these kinds of iconic wizards, and seasoned veterans get to feel extra different and customized when they break away from the mold.

But again: this is completely a personal preference thing, and not really relevant or necessary.

**Comment by mlenser** [comment]
Dark Star from Explorer's Guide to Wildemount

**Comment by mlenser** [comment]
Sudden Vacuum added to the Cosmos theme

**Comment by itamarcu** [comment]
- [Levitate](https://www.kryxrpg.com/spells/levitate) should be added to Cosmos.

- The feat [Ascendant Step](https://www.kryxrpg.com/feats/ascendant-step) could be added to Cosmos - possibly renamed to something like "Reject Gravity", "Free-Float", or something similar

- [Floating Object](https://www.kryxrpg.com/spells/floating-object) can be added to Cosmos, or slightly altered to force the object to orbit around you and.

- A feat like [Far Wanderer](https://www.kryxrpg.com/feats/far-wanderer), for cosmos-themed characters who came from outer space or are adapted to living outside planets.  Gives "you don't need to breathe" plus a minor situational benefit, e.g. resistance to extreme pressures, or extreme cold.

- A feat like [Lord of the Storms](https://www.kryxrpg.com/feats/lord-of-the-storms) or [Vampiric Wings](https://www.kryxrpg.com/feats/vampiric-wings), that grants 60 feet flying speed at high level, should be added.  Might even be more thematic to make it a slower speed but "can float".

**Comment by mlenser** [comment]
- **Cosmos**
  - Far Wanderer added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)
  - Floating Object added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)
  - Gravity Defying feat added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)
  - Levitate added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)
  - Ascendant Step added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)

more to come from above

**Comment by mlenser** [comment]
- Hungering Darkness covers Dark Star and Ravenous Void's niche.
- Magnify Gravity covered by Gravity Sinkhole

Explorer's Guide to Wildemount spells are officially picked over

**Comment by mlenser** [comment]
- Hungering Darkness covers Dark Star and Ravenous Void's niche.
- Magnify Gravity covered by Gravity Sinkhole

_____


- **Cosmos**
  - Gravity Defying feat added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)
  - Gravity Fissure added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)
  - Gravity Sinkhole added to the Cosmos theme [#440](https://github.com/mlenser/kryx-rpg-issues/issues/440)


Explorer's Guide to Wildemount spells are officially picked over
