### ISSUE TITLE
Increase Black Tentacles area

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#441]
The spell is similar to Whirlwind and Maelstrom, so it should have double its normal size, since the huge AOE control is it's main selling point

**Comment by mlenser** [comment]
According to my calc these are all balanced. Though they are heavily based on conditions so I wouldn't trust this 100%.

![image](https://user-images.githubusercontent.com/235857/87088312-d96b5780-c234-11ea-92f6-290ce71131fa.png)

**Comment by itamarcu** [comment]
These four are balanced against each other, but Whirlwind and Maelstrom are apparently overpowered (according to the sheet):
![image](https://user-images.githubusercontent.com/6516621/87089175-acbc3d80-c23e-11ea-903f-0b6398818900.png)

I think it's Whirlwind and Maelstrom that should have their areas reduced, and potentially even nerfed further, because they also fling people away.

**Comment by Marcloure** [comment]
> According to my calc these are all balanced

These spells are like RAW web but a bit larger. Web is a fairly balanced spell I think, but expending 1 additional mana (or imagine a 5th level slot) to increase the size by this little ain't great. Sure, these 3 spells deal a bit of damage, but 1d6 is... well, it takes 3 turns to kill a CR 1/8 mob, it's there more to break concentration I believe.

Also, their are kind of "save for nothing spell", since if you succeed you can just walk away (and take 1d6/2 damage)

**Comment by mlenser** [comment]
The damage is contributing a very small amount:
![image](https://user-images.githubusercontent.com/235857/87116215-7a7a0280-c275-11ea-9197-2d6083b306b4.png)

These spells are calculated to effect around 2.2 creatures in terms of value (likely more, but the value of effecting multiple creautures is reduced).
Ensnare is a similar spell, but against a single target and does much more damage.

So this spell is 3 mana because we have single target hard CC at 2 mana so aoe hard CC should be 3 mana. It's not only Hard CC, but also takes an action to break out of. Based on the comparison to single target spells, this spell applying hard CC to multiple targets, and taking an action to escape makes this spell worth 3 mana. I believe it is balanced where it currently resides.

**Comment by itamarcu** [comment]
@Marcloure - do note that these areas are ongoing, and you can push enemy creatures into them if they get out. That's not really "save or nothing".
