### ISSUE TITLE
Fighting Style clarifications

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#448]
> You have trained and adopted styles of fighting as your specialties. You can **learn** fighting styles from themes you know. As a bonus action on your turn, you can enter a **stance**. You can only have one **stance** active at a time and it remains active until you finish a short or long rest.

First, the term _instance_ is used in place of _style_. I don't know if this needs to be changed though.

Second, how do you learn a style? And how many styles do you know? If it's all styles from a theme, then I think it's better as: "As a bonus action on your turn, you can enter a stance (style?) from a theme you know."

**Comment by itamarcu** [comment]
This change was made in other places to explain how you learn Fighting Styles:

![image](https://user-images.githubusercontent.com/6516621/87241391-60822080-c42b-11ea-8481-a1d21de93b27.png)

Still, I would rather have it work like you suggest - instead of learning specific fighting styles you just automatically know all the ones in your themes. It's clean and understandable and easy to use.

This will also solve a new issue that I believe @mlenser missed - martial classes start with no fighting styles known, instead of 1 + INT, so as it currently stands they would have to spend their first Combat Ability on a fighting style.

**Comment by Marcloure** [comment]
Oh, I didn't see that. I don't know if I like that you have to exchange a power pick for a passive benefit, seems like an unnecessary nerf.

**Comment by mlenser** [comment]
Wording cleaned up

![image](https://user-images.githubusercontent.com/235857/87250584-10747f80-c466-11ea-9248-d2cc6de2e460.png)
![image](https://user-images.githubusercontent.com/235857/87250577-0783ae00-c466-11ea-9cb3-28e04d4cf035.png)
