### ISSUE TITLE
Timeless Body could be lowered to 13th level

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#468]
Timeless Body is a feature that shouldn't be low level by its flavor, but the feat Gift of Life is a 14th level feat, so I think it's reasonable that a Naturalist or Psionicist would gain this feature at a similar (earlier) level.

Increasing the feat's level is also an alternative.

Another reason for this suggestion is to give something to the Naturalist and the Psionicist between the 10th and 17th level. The Warden and the Ranger, for instance, gain no class features between those levels. I don't know if it's needed, but they could then gain another non-combat feature at 17th level.

**Comment by mlenser** [comment]
> give something to the Naturalist and the Psionicist between the 10th and 17th level.

Gish classes generally don't have features in this window. They aren't really intended to since features were moved to feats. So feats are meant to cover it. Suffused obviously breaks that not that they have subclass features. Mage's feature is small and part of their scaling. Psionicist and Naturalist follow the standard mold

**Comment by Marcloure** [comment]
The Rogue also gains features at 13th level, quite a few actually

**Comment by mlenser** [comment]
Timeless Body reduced to 13th level
