### ISSUE TITLE
Improve Feral Senses

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#469]
Feral Senses, the 17th level Naturalist's feature, is good, but I think it's a bit lackluster. It's a weaker blindsense when we already have a lot of feats and spells that grant blindsense, and the rogue also gains it within a 10 feet range. 

I suggest a small improvement to Feral Senses:

> You are also aware of the location of any invisible creature within 30 feet of you, provided that the creature isn’t hidden from you and you aren’t blinded or deafened.

Instead of "provided that the creature isn’t hidden", we could say that a invisible creature can't hide from you if it doesn't have full cover. It could still stalk you, but it wouldn't be able to rely on invisibility to hide from you.

**Comment by mlenser** [comment]
> provided that the creature isn’t hidden from you

This is dependent on being able to detect the creature through other senses than sight. Sound or something similar.

This seems like the right choice.

**Comment by Marcloure** [comment]
It's just that I feel like this feature isn't that powerful for a 17th feature. It only works against a) invisible creatures (which is situational), and b) they can't be hiding. This doesn't work in darkness or against obscurement like blindsight does.

**Comment by mlenser** [comment]
17th level features aren't super powerful. They're nice, but not deal breaking.

If a Naturalist needs more at 17th level then I suggest we add something more. I don't think Feral Senses should be blindsight.

**Comment by itamarcu** [comment]
Knowing the location of an unseen creature simply lets you attack it or cast an AoE on it without having to guess - that's the whole benefit.

> You are also aware of the location of any invisible creature within 30 feet of you, provided that the creature isn’t hidden from you and you aren’t blinded or deafened.

This sentence, in its current form, is meaningless - everyone is already aware of the location of invisible creatures due to sounds they make, air movements, tracks it leaves, etc. The awareness stops if the invisible creatures starts hiding, but at that point this part of Feral Senses doesn't function either.

**Comment by mlenser** [comment]
> This sentence, in its current form, is meaningless - everyone is already aware of the location of invisible creatures due to sounds they make, air movements, tracks they leave

This isn't the case in my rules. See the 4th bullet of the unseen condition:

![image](https://user-images.githubusercontent.com/235857/88901432-0ec1fe80-d251-11ea-8748-3baaebd04e77.png)

**Comment by itamarcu** [comment]
You mean the fifth bullet? "Any noise it makes or any tracks it leaves" doesn't seem different than the RAW rules, unless the implicit intention is that normal activity does not make any noise.

As far as I know (and these rules don't seem to suggest anything else), invisible creatures still need to hide, or to have favorable conditions - e.g. to use silent abilities, or hover above the ground, or fight when there's no smoke or rain in the air. Otherwise, while they still gain most benefits of being unseen, their location can be determined.

Invisible creatures already get the ability to hide as a bonus action in this system, which should allow them to conceal their position better than RAW.

**Comment by Marcloure** [comment]
> Invisible creatures already get the ability to hide as a bonus action in this system, which should allow them to conceal their position better than RAW.

Only the moment they become invisible, but I agree with you.

**Comment by mlenser** [comment]
Being unseen does not mean your position is known. I can clarify the wording, but there are some cases of it currently:

> When an unseen creature makes an attack, it gives away its location when the attack hits or misses.

How could it give away its location if its location is already known?

> The creature’s location can be detected by any noise it makes or any tracks it leaves or it can be guessed

This is a Perception check

______________

> their location can be determined.

They location can be determined, 100%. But it isn't automatically known as you wrote above

______________

The rules around hiding are super unclear and my system doesn't iron them out. If the position has to be detected before stealth, why would an unseen creature stealth?

**Comment by mlenser** [comment]
Feral Senses moved from 17th level to 13th level and reworked part of it to be blindsense in a 10 foot radius.

https://github.com/mlenser/kryx-rpg-issues/issues/473 opened to add a new 17th level feature.

**Comment by mlenser** [comment]
Feral Senses moved back to 17th level

**Comment by Marcloure** [comment]
May I question why? The rogue has blindsight at 13th level

**Comment by mlenser** [comment]
Gish classes generally do not really have 13th level features beyond their damage improvements, sometimes the longer life features, and other minor scaling improvements.

The model is meant to be features at:
- 1st level
- 2nd level
- 7th level (some upgrades)
- 13th level (some upgrades)
- 17th level
- 20th level

If anything, Rogues should receive less features.

**Comment by Marcloure** [comment]
Sure, I just don't think it's fair in a table with a Rogue and a Druid where the Rogue gains the same feature 4 levels before.
