### ISSUE TITLE
Snap Shot and Swift Strike discrepancies

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#492]
Snap shot adds the maneuver die to the extra attack's damage, but swift strike does not. Is there a reason for it or is this set wrong?

**Comment by Marcloure** [comment]
Ah, I suppose it's because 2h weapons deal d12 damage?

**Comment by itamarcu** [comment]
Still feels a bit wrong - especially since not all ranged weapons do the same damage and not all melee weapons deal the same damage. a Heavy Crossbow deals 1d10, while a Longsword deals 1d8.

Also, Swift Strike requires you to hit once to attack again, while Snap Shot does not. Furthermore, Snap Shot lets you hit any other creature in range, while Swift Strike is more limited by your positioning.

I'm in favor of making them more similar to each other. My suggestion is to make both "when you take the attack action" (not requiring a hit) and not adding stamina dice to the damage.

If you want to strongly balance around different weapon sizes, you could say "...with a weapon that isn't heavy/two-handed" or say "if it's a light weapon you can add your stamina die".

**Comment by mlenser** [comment]
Snap Shot recalculated and its extra damage from the stamina dice has been removed
