### ISSUE TITLE
Kinetic Assault and Kinetic Grasp

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#498]
There is an apparent imbalance between the two,both 1 mana spells.

Assault causes a bit more damage (15.5 vs 14) at a longer range (120ft from assault vs 60ft of grasp) although 60 ft is already pretty good.

Grasp has the possibility of repeating the attack with a bonus action for a minute (uses concentration though) and has 4 other options other than push (that is the equivalent of kinetic assault).

Grasp seem way better than assault, both for the flexibility (which I feel is not accounted for in the balance spreadsheet) and the repeat.

They both look balanced in the spreadsheet, but one is obviously better, so maybe some parameters must be adjusted as well.

I might also be wrong that kinetic grasp is better than assault, so if someone thinks that way, pls tell me why/how

**Comment by Paulorpribeiro** [comment]
My proposal for fixing would be to up kinetic grasp to 2 mana and balance it there. Also, the flexibility of certain  spells is not accounted for in the spreadsheet. They must be accounted somehow, may be a damage mod? Not sure.

**Comment by mlenser** [comment]
Kinetic Grasp is the same power level as Force Hand and Giant Crawling Claw. Please check the spreadsheet in the future - I generally group similar spells together.
![image](https://user-images.githubusercontent.com/235857/90309707-205f0380-deeb-11ea-976a-8a906b14fc8c.png)

Kinetic Grasp doesn't do half damage (which it should). If it did, the damage would be lower than 3d6.

**Comment by Paulorpribeiro** [comment]
I know it is similar to the spells you mentioned, I'm comparing it with the eyes of a character with the telekinetic theme and a choice of spell to choose. The choice, between assault and grasp seems pretty obvious, and that means an issue between those two. I checked the spreadsheet, mentioned them even, but we can't blindly trust everything about it. If the spells feel imbalanced but numbers tell they are balanced, either the spreadsheet parameters need a change or my1st iimpression is wrong. That is why I asked, why would anyone choose kinetic assault over kinetic grasp? If no-one would, them one is better than the other and they need to be changed.

Thats not personal, just an overlook

**Comment by mlenser** [comment]
> I know it is similar to the spells you mentioned

It's the exact same as said spells. All should change or none. Based on the numbers there, those spells are perfectly balanced. I think they should probably be changed to attacks instead of saves, but that's unrelated.

_______________

> I'm comparing it with the eyes of a character with the telekinetic theme and a choice of spell to choose

You're overlooking the half damage. Kinetic Assault is longer range, deals more damage (16.5 vs 14), and deals half on a save.

Realistically, you're looking at 12.8 vs 7.7 damage on average. Huge difference. The spreadsheet has taken this into consideration, but perhaps you haven't considered the full math here?

![image](https://user-images.githubusercontent.com/235857/90310018-dcb9c900-deed-11ea-98ec-40522c2f846d.png)

**Comment by Paulorpribeiro** [comment]
I indeed have not considered the half damage on save, and that changes the balance a little. But both the flexibility and possibility of repeat of the grasp and related spells is maybe downplayed in the spreadsheet. I personally would always choose the repeatable and more flexible spell with any class with access to spells.
But maybe that's just me

**Comment by mlenser** [comment]
Kinetic Grasp now does 3d6 (10.5) or half on a save. So it's 12.8 vs 8.6 damage. That's a big difference in damage.

Scale it up to 3 mana and you're looking at 11d10 (60.5) vs 11d6 (38.5). Or after saves: **47 vs 30 damage**

> repeat of the grasp and related spells is maybe downplayed in the spreadsheet

How so? The damage is ~2/3 of the burst spell. Damage in future rounds is considered half value and these spells aren't considered to last long.

> flexibility [...] is maybe downplayed in the spreadsheet

Spells shouldn't be less powerful because there are multiple options. Many cantrips provide utility, melee, and ranged options. Those cantrips shouldn't be less powerful than other cantrips.

Versatility is ultimately power, but it isn't a factor when comparing each option of a spell and shouldn't be. If there are spells that are too similar, the spells should be combined or one should be removed. In this case we're looking at a repeat vs non repeat. Quite a big difference in those.

**Comment by itamarcu** [comment]
@Paulorpribeiro - if you think that Kinetic Assault is not a good choice due to its lack of versatility, maybe you could think of a change or an augment to the spell that would allow it to have more utility/versatility while remaining unique?

For example, currently Kinetic Assault pushes a creature 15 feet away from you. I think it could be changed to push in any horizontal direction, or to have augments increase the push distance, or to be able to target and deal more damage to objects.

**Comment by mlenser** [comment]
Damage on subsequent rounds has been changed from a value of 50% to a value of 66.66%. Ongoing maneuvers and spells are therefore weaker.

At 3 mana:
11d10 (60.5) vs 8d6 (28). Or after saves and half: 47 vs 21.7 damage

**Comment by Paulorpribeiro** [comment]
I think I agree with the change, the burst damage now is reason enough to make the repeat option not automatically mean the best. I just don't agree with the following:

`Versatility is ultimately power, but it isn't a factor when comparing each option of a spell and shouldn't be`

It definitely is a factor. If I were to create a storm spell that shocks my weapon attacks, allows me to use  an action to cast llow damage ightning bolts and a reaction to zap foes that hit me, it is obviously not a 1 mana spell (if it's viable cat all) no matter how you decrease the damage of every part of the spell because it is too versatile. Thats an example, i have no intetest in such a spell, just discuss wether we meed a wayvto account for versatility and have a "many options" modifier in the spreadsheet.

On a ompletely different subject

`@Paulorpribeiro - if you think that Kinetic Assault is not a good choice due to its lack of versatility, maybe you could think of a change or an augment to the spell that would allow it to have more utility/versatility while remaining unique`

Perhaps kinetic assault could have an augment target multiple close enemies? Or is it too similar to the likes of thuderwave? Shouldn't there be a thundewave-like spell in telekinesis?
