### ISSUE TITLE
Bestial Spirits is a bit too powerful

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#501]
Bestial Spirits have some pretty powerful options, and also some that are not as competitive. Bear spirit gives ~8-9 temp hp and advantage on Reflex, while the wolf grants Pack Tactics to every ally in the aura (and the players will make use of it, so it's basic advantage on every attack roll), and the unicorn a small but ok boost to heal.

Beyond balancing the options against each other, I think the spell should either last less, require concentration, or have a regular aura instead of double the normal.

I'm reporting this by experience: it's very easy to benefit from the wolf spirit with 2 mana (20-foot radius), and as it doesn't require concentration, you don't have to end the spell earlier to cast another one, so it's virtually 10 minutes with the whole party attacking with advantage.

**Comment by mlenser** [comment]
@Marcloure I need more details. Which ones are too strong and which are too weak? Do you have any recommended fixes?

**Comment by mlenser** [comment]
Bestial Spirits removed in favor of Spirit Guardians

**Comment by Marcloure** [comment]
I'm sorry, but Beastial Spirits (a buff spell) is a much different spell from Spirit Guardians (damage and debuff).

About which spirits I find too powerful: **wolf**, maybe **shark** (when compared to **eagle**, which requires reaction to grant advantage).
Too weak: **bear**, **unicorn**.

**Comment by mlenser** [comment]
I don't believe the old version should exist. It's like a suped up Bestial Transformation in some cases and just mediocre in others. If there are any that should persist, we could add them to Bestial Transformation, but I didn't think they deserved preservation at a glance.

Sharks have had their blood stuff removed in favor of blood in the water, so that should be gone if we go that direction.
