### ISSUE TITLE
Add more Madness feats/spells

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#503]

**Comment by itamarcu** [comment]
I have suggestions!

## Cantrips (they all scale/augment normally, not mentioned here)

### Disturb (0)
As an action, you disturb the mind those near you. Each creature that you can touch or see within 5 feet of you must make a Fortitude saving throw. Creatures with an Intelligence of -5 or less are unaffected.

On a failed save, a creature takes 1d4 psychic damage.

On a successful save, a creature takes half as much damage.

### Discombobulate (0)
As an action, you confuse a creature you can touch or see within 60 feet. The target must make a Will saving throw.

On a failed save, the creature takes 1d6 psychic damage and moves 5 feet in a random direction if it is able to. This movement doesn’t provoke opportunity attacks.

On a successful save, it takes half as much damage and doesn’t move in a random direction.

### Infuriate (0)
As an action, you provoke a creature within 120 of you that can see or hear you. The creature must make a Will saving throw. A creature with Intelligence lower than -4 is unaffected.

On a failed save, the creature takes 1d4 psychic damage and it has disadvantage on its next attack against any creature other than you.

On a successful save, it takes half as much damage

## Spells

### Lapse of Judgement (1)

As an action, you can induce momentary madness in a creature you can touch or see within 60 feet. The target must make a Will saving throw. A creature with Intelligence lower than -4 is unaffected.

On a failure, the creature must use its reaction to act irrationally. Choose one of the following effects:
* The creature makes a weapon attack against the closest creature to it within its range.
* The creature drops any object it is currently holding.
* The creature moves half of its speed in a random direction, and then falls prone.

## Feats

### Unsound Mind (6th level)
Your irrational behavior can protect you from mind-altering effects. When you become frightened, or charmed, you can choose to instead become confused.

### [A copy of [Altered Memories](https://www.kryxrpg.com/feats/alter-memories) that applies to your spells, no idea how to call this] (14th level)
[ ... when you cast a madness spell (maybe limited to spells that confuse, or spells that deal no damage...?), you can make a creature unaware of the influence, forget what happened, yada yada]

### Subverting Influence (10th level)
*Prerequisites: you know the Misdirection spell*
You can cast *[Misdirection](https://www.kryxrpg.com/spells/misdirection)* at will, without expending mana.

-----

Disturb is a reskinned [Radiance](https://www.kryxrpg.com/spells/radiance). The flavor can be that the nearby creatures see something grotesque and unnerving in you - or it can just be a generic short-range psychic blast

Discombobulate is a reskinned [Infestation](https://www.kryxrpg.com/spells/infestation). I slightly altered the wording of the random movement (I think it's cleaner like this).

Infuriate is like a miniature version of Bloodlust - it plays up the concept of madness used to enrage creatures. Here, specifically, it's about provoking an enemy into irrationally attacking you.

Lapse of Judgement is based on [Blood Puppet](https://www.kryxrpg.com/spells/blood-puppet) and [Command](https://www.kryxrpg.com/spells/command).

**Comment by DalenWBrauner** [comment]
I think these are all _really cool_.

Only weirdnesses are:
- Why is Disturb a fort save? It should probably be Will unless you have some other thematic in mind.
- Lapse of Judgement is cool, but being able to choose to make someone attack the nearest target is rather powerful. I can think of a few ways to mitigate that (for example, which Lapse effect occurs is rolled randomly instead of chosen by the caster), but I'd rather remove it and add other cool lapse effects like in Command. Unless I'm forgetting some other 1 mana spell that allows you to do that.

**Comment by itamarcu** [comment]
Disturb was a failed copy-paste, should be Will :P

Lapse of Judgement is meant to have a stronger effect than Command, because it wastes an enemy's reaction and not their whole action. I felt that spending 1 mana to force one attack (plus eat a reaction) was okay, because Blood Puppet is a 1 mana reaction spell that can cause an attack plus ~4 damage (though it's more situational). Still, I made it "attack the nearest creature" instead of attacking any creature (as Blood Puppet did) to limit it more, and to keep to the idea of madness and lack of control. Making the effect itself random would be too unreliable, IMO.

**Comment by mlenser** [comment]
Lapse of Judgement not needed as Confusion is 1 mana. It's the same niche.

What is the point of unsound mind? Confused isn't much better than Charmed or Feared, though it would completely nullify certain enemies that depend on those conditions for followups. Not sure that is a good idea as it is super niche, but very very powerful in that niche.

Misdirection at will is far too strong I think.

**Comment by mlenser** [comment]
- **Madness**
  - Discombobulate added as a Madness cantrip [#503](https://github.com/mlenser/kryx-rpg-issues/issues/503)
  - Disturb added as a Madness cantrip [#503](https://github.com/mlenser/kryx-rpg-issues/issues/503)
  - Alter Memories added to the Madness theme [#503](https://github.com/mlenser/kryx-rpg-issues/issues/503)

**Comment by itamarcu** [comment]
Alright!  Also, regarding the few you commented on:

Lapse of Judgement is really different because *you* can choose how the creature acts, and it's taking away its reaction (not its action), so the spell can be balanced to give a better controlled benefit than Confusion or Command.  I think it should be better compared to Command, not Confusion.  The flavor is that you momentarily make somebody act irrationally, not that you confuse them for several rounds.

Misdirection at will was based on the RAW Mastermind rogue ability:
> Beginning at 13th level, you can sometimes cause another creature to suffer an attack meant for you. When you are targeted by an attack while a creature within 5 feet of you is granting you cover against that attack, you can use your reaction to have the attack target that creature instead of you.
In RAW it is a more restricted trigger (need to be granted cover), but no reflex save, so I felt like they're comparable.

**Comment by mlenser** [comment]
> Misdirection at will was based on the RAW Mastermind rogue ability

Ya, it's too much to use your reaction to not only avoid being targeted, but also force it to target someone else. That should definitely have a cost (reaction + resource)
