### ISSUE TITLE
Increase Antilife Shell to 3 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#527]
> The barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier.

This is a very potent effect, basically turning you immune to most melee attackers (since even with 2 mana, it is a 10-foot radius). I think this effect should be available only at tier 3. Also, it's a 5th level spell in RAW (available at 9th level).

**Comment by itamarcu** [comment]
RAW antilife shell is also a concentration spell, while here it's without concentration.

Some melee attackers could throw weapons or use something with 15+ ft of reach, or simply attack other creatures - but I agree that this is a very strong effect.

I recommend either increasing the cost to 3 mana or adding concentration.

There could also be an augment for keeping the sphere in place instead of following you (making it similar to a wall of force and antimagic sphere, and rewarding some creative usage)

**Comment by Marcloure** [comment]
I think it's fine-ish without concentration, since it doesn't boost any number or cause conditions, but I like the idea of making it static with an augment to make it an aura.

**Comment by DalenWBrauner** [comment]
If it _was_ concentration, melee fighters would be able to break that concentration with ranged attacks. I rather like that option for counterplay; at least on paper, that is. Maybe I'd hate it if I were the caster.

Also I'm with Marcloure- it following as an aura ought to be the augment.

**Comment by itamarcu** [comment]
Generally, these positive/helpful spells are an aura that moves with you, and sometimes have an augment to remain in place. See for example - [Antimagic Sphere](https://www.kryxrpg.com/spells/antimagic-sphere) and [Wild Magic Sphere](https://www.kryxrpg.com/spells/wild-magic-sphere). I think having the sphere follow you is the much more common use case, while detaching it from you is not really that useful (more useful with Wild Magic Sphere).

Still, it's not a hard rule so I'd be fine with this spell being 2 mana for a stationary shell and a 1 mana augment to make it follow you. I still think it's quite strong without concentration (though that depends on the specifics of the campaign and the enemies the characters would be fighting).

**Comment by mlenser** [comment]
Antilife Shell now has concentration and an augment to cast it on a location
