### ISSUE TITLE
Create content for Death Theme

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#544]
As a result of the Death/Undeath split, @itamarcu pointed out Death could use some more feats. We brainstormed some things on discord, but haven't refined anything yet. Stuff like:

* Ravage Spell (based on Time Ravage), for the sake of denying resurrection
* Fatality Maneuver (similar effect, likely 5 stamina)
* Potentially a Feat for making it harder for your victims to make death saving throws (e.g. increasing the C.R. by 5)

**Comment by Marcloure** [comment]
I suggest a version of Fire Master / Adept but for necrotic damage.

**Comment by itamarcu** [comment]
### Feat - Lethal (2nd level)
Your methods are particularly lethal, and your victims rarely survive encounters with you. When you reduce a creature to 0 health with a maneuver or spell that belongs to the Death theme, the creature becomes Wounded 1.

(alternative but similar: the creature has disadvantage on its death saving throws, or the creature fails every saving throw, or the creature just instantly dies)

**Comment by Marcloure** [comment]
That is almost useless for PCs, and creatures don't gain Feats

**Comment by itamarcu** [comment]
2nd-level feats can be more flavorful than useful, and this is certainly something that some assassin-like characters would want. Still, maybe this could be improved (to instant death) or paired up with an additional effect (such as preventing enemies from healing or reducing their maximum hp or gaining some benefit from killing creatures).

**Comment by itamarcu** [comment]
### Spell - Detect Death (1 mana)
*(ritual); concentration, 5 minutes/mana or psi*
As an action, you can sense the presence and location of corpses and piles of bones within 30 feet of you, including undead. If a living creature is reduced to 0 health or dies while it is within your range, you sense it as well.

(based on [Detect Disease](https://www.kryxrpg.com/spells/detect-disease). I removed the part about barriers because it'd be pretty useless when most dead creatures are underground and inside coffins, and the range is already short. the flavor here would fit most a character like a death priest or a blight druid, someone who can feel death around them. I considered adding something about telling when or how a creature died, but I think we can keep it simple.)

**Comment by mlenser** [comment]
- Death Adept and Death Master feats added
- Ravage spell added
- Detect Death spell added

> Fatality Maneuver (similar effect, likely 5 stamina)

Maneuvers are not magical. They cannot ravage.

> Your methods are particularly lethal, and your victims rarely survive encounters with you. When you reduce a creature to 0 health with a maneuver or spell that belongs to the Death theme, the creature becomes Wounded 1.

As Marcloure wrote, this is an empty flavor option for the most part.

____________________

Please open a new issue if you have new ideas.
