### ISSUE TITLE
Add augments to 5 mana spells

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#553]
Players can't augment 5 mana spells, but the lich for instance has mana limit of 7. This means lich can cast stronger fireballs than meteor swarms

**Comment by DalenWBrauner** [comment]
A point of conflict: If you bake that sort of text into the spell itself, players are likely to wonder how they might achieve such a thing.

It would be _nice_ if there was text _somewhere_ on the site that could give guidance on this type of situation- e.g. how to augment damage beyond 5- but augments often each have their own unique parameters, so that may not be feasible.

The lazy solution is to demote the spell to 4 mana and then add an augment that scales damage "for each additional mana or psi expended", but I don't think that's for the best. There should totally be some 5-mana exclusive spells (that can be augmented by powerful creatures).

Perhaps the best way to go is simply add an augment, but explicitly include some wording such as "Creatures capable of augmenting past 5 can..."

**Comment by mlenser** [comment]
The Lich doesn't even have any 5 mana spells. 😛

**Comment by mlenser** [comment]
I've check all 5 level spells and none are used by monsters so this is currently a non-issue.

5 mana spells are already on their own in terms of effectiveness so I don't think they need augmentation. Meteor Swarm is already doing damage equal to a 6 mana spell for example and a others are even more value.

**Comment by Marcloure** [comment]
> The Lich doesn't even have any 5 mana spells.

It doesn't have, but I think the stat block list is just a suggestion? If someone makes a fire lich or a time lich, they will likely give it 5 mana spells.

**Comment by mlenser** [comment]
Then the other part applies:

> 5 mana spells are already on their own in terms of effectiveness so I don't think they need augmentation. Meteor Swarm is already doing damage equal to a 6 mana spell for example and others have even more value.
