### ISSUE TITLE
Consider removing Expertise

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#558]
As part of working on skills I've examined my system's changes to expand the expertise system to all classes. I'm not sure that change was a good change.

## "All or Nothing" skill development
The 'bounded accuracy' philosophy of 5th edition was designed to ensure that each character has a reason to attempt ability checks.

Othwerise all skill checks become either trivially easy for experts, or impossible for everyone else. That is to say, the DM either sets skill DCs low enough for everyone to have a fair shot at making it, in which case the expert almost can't fail (and in that case, why would the non-experts even try?), or the DM sets the DCs high enough for the expert to be challenged, in which case everyone else can't possibly do it (so again, why even roll?).

This leads inevitably to a situation where there isn't much point to basic proficiency; everyone wants to dump all their advancement into a few skills in order to be "the one" for those specific skills, and everyone else avoids those skills like the plague because they know they can't be good at it.

It isn't good for a group's balance or enjoyment for one character to be the God of Persuasion while everyone else has to just wait for that one character to handle all the Persuasion rolls. Maybe that one guy gets a moment of power-fantasy gloating, but the rest of the table is effectively being told, "You cannot contribute in this situation." And that's not fun at all.

![chart](https://user-images.githubusercontent.com/235857/92949575-98253d00-f45b-11ea-9f6e-28b48ad415f9.png)
This graph shows how expertise expands the problem, especially at high levels
Math: https://docs.google.com/spreadsheets/d/1sGvcz9vbq9yk4kRBEY6ZYGWhGO6-t7CWudznQcWPk74/edit#gid=444002489

## Without expertise
These factors and motivations exist without expertise, but they are not as amplified as they are by the expertise expansion.
The Rogue's ability to excel at skills can be handled in a way that does not cause these problems.

**Comment by Marcloure** [comment]
My main gripe about expertise is that... well, it is actually with having 3 levels of proficiency. Most of my player don't really have any interest in being capable with a skill., they rarely are "just a bit" interested in a skill. Either they want to be good at it or they don't care. However, I do think that capability + proficiency is better than proficiency + expertise because of the problem you have laid out. 

Expertise may become an unique feature of the Infiltrator Rogue, since I and others have this perception that it has fewer features than the other Rogue archetypes. Or it may just be gone for all.

**Comment by itamarcu** [comment]
One thing that somewhat alleviates this is that many groups tend to assign a bit of extra value to simply having proficiency, regardless of score. For example, only allowing a player to Help with an Arcana check if they have proficiency, or telling a player that they need to have Medicine proficiency to use a Healer's kit.

For Rogues, I think something like "Reliable Talent" could work, making their skills more *consistent*, not just increasing the ceiling.

One potential direction is to make Expertise (as a skill improvement, a feat, or a class feature) work like this - making it "you can always take 10 instead of rolling" (or take 5, or "you cannot roll below 10").

By the way - is there a chance that this thought about removing expertise is a result of spellcasting skills being harder to balance with expertise? :P

**Comment by mlenser** [comment]
> they rarely are "just a bit" interested in a skill. Either they want to be good at it or they don't care.

Ya, this is that "all or nothing mindset" and like I said above, it doesn't disappear. However, it is lessened without expertise.
Also, my system does somewhat force characters to take some capability as they only have so many skills on their list.

______________


> I think something like "Reliable Talent" could work, making their skills more consistent, not just increasing the ceiling.

I'm not sure rogues even need something here. A Rogue, even without reliable talent, is good at picking locks and the rogue contributes just as well to combat as other classes. I'm not sure this feature is needed to make them really good skill users. They're already really good skill users and have the most skills of any class.

But if the Rogue does need something, then Reliable Talent is what I was thinking. It could be scaled down to lower levels. Though that's still a problem for Everything as skills #414. I'll make the choice irregarless to #414 for now.

_____________

> is there a chance that this thought about removing expertise is a result of spellcasting skills being harder to balance with expertise? :P

It triggered the thought, but the reasoning is unrelated to whether I do that change or not. The trigger caused me to re-evaluate "wait, I'm attempting to adjust the system's numbers higher to adapt to expertise. Why do I have expertise in the first place?". That question triggered some googling and a post that I mostly plagarized for what is written above. I think it's convincing and so is the math.

**Comment by itamarcu** [comment]
What's the point of Capability in such a system, though?

It's a +1 bonus at the levels where most players play, becomes +2 at level 9, and only +3 at the highest tier. Functionally, it's going to matter very little compared to your ability score in something.

Unless the numbers change to increase the bonuses of both (which I assume they will not do), I think there should be more incentives for players to be Capable at something. I think the best way to do that is to put a capability requirement on a lot more skill checks, tool/item uses, and perhaps feats.

I suggest...

**Skills**
- Acrobatics - Grab Edge, Soften Fall, Tumble - should require capability (currently they require proficiency, other than tumble)
- Alchemy, Engineering, Arcana, Occult, Psionics, Primal, Divinity - should require capability for all use cases. recalling knowledge, monster lore, identifying magic items, and identifying spells
- Athletics - maybe put a lower limit on your jump distance if you're capable? +1-+3 feet of jump distance are quite insignificant.
- Brawn - require capability to overrun, and *maybe* to shove/trip? or with disadvantage on shoving/tripping unless you're capable?
- Deception - require for using a Disguise Kit
- Medicine - require for most of the things mentioned there (instead of proficiency, for some)
- Skulduggery - require for forging documents, arming/disabling traps, and opening locks
- Streetwise - require for recalling knowledge (like the other knowledge skills), understanding unfamiliar slang, maybe to locate a fence and to track
- Wilderness - require for a bunch of these

**Gear**
- Climber's Kit could require capability in Athletics
- Battering Ram, and perhaps Sledgehammer and Crosbar, could require capability in Brawn to provide the advantage to the check
- Navigator's Tools - wilderness? acrobatics? unsure, because seafaring doesn't fully match a skill I can see

**Feats**
- Thematic Diversification and the Initiate skills already require proficiency in power source skills
- several of the Deceit feats could require capability in Deception, Stealth, or Skulduggery
- same with Divination and Insight/Perception/Investigation

**Comment by mlenser** [comment]
> What's the point of Capability in such a system, though?

To differentiate between a bit of experience and a large amount of experience. Examples:
- "I went through basic training in my country so I can jump and swim and push things pretty decently" vs "I spent a few years in the military"
- "I was a street rat that lied and stole to survive" vs "I have been a master thief for years"

A character could choose to be good in a lot of skills, like the RAW Bard's Jack of All Trades feature.

> It's a +1 bonus at the levels where most players play, becomes +2 at level 9, and only +3 at the highest tier. Functionally, it's going to matter very little compared to your ability score in something.

Half proficiency exists in RAW 5e, capability is just codifying it into a standard rule and using it more extensively. If the math matters enough for RAW featurs like a Bard's Jack of All Trades then it surely matters enough for us as well.

________

>  I think there should be more incentives for players to be Capable at something. I think the best way to do that is to put a capability requirement on a lot more skill checks, tool/item uses, and perhaps feats.

Tools are dead. Navigator's Tools are useful for Wilderness under the "Determine cardinal direction" usage, though how it helps could be codified (I'd eyeball it offhand as advantage).

Can you open the rest as a new issue? I think it's a worthwhile discussion and we could probably make some changes to those things, but it's separate from having expertise or not.

**Comment by itamarcu** [comment]
That's fair, though I do want to point out that 5e only had half-proficiency as Jack of All Trades, which was specifically rooted in the flavor of being a jack of all trades. Plus, mechanically, a dozen tiny bonuses *do* feel meaningful, while a single tiny bonus is easily forgotten.

**Comment by mlenser** [comment]
From Discord, for the record:
> One thing that I didn't mention before: I don't plan to adjust monsters that have expertise in a skill by RAW. Aarakocra and dragons with perception, Aboleth with Psionics (Arcana in RAW).
> 
> While I prefer a system where the same system is used for PCs and NPCs, I'm willing to deviate in this regard for a few reasons:
> - The monsters are balanced for this in RAW so I'm inclined to leave them
> - The bonus of expertise over proficiency is half of what it is in RAW (+1-3), so any concerns on the monster math is limited
> - It does not have the negative effects like expertise does for PCs - there is no "all or nothing" problem
>
> NPCs can already go above 5 in abilities whereas PCs can't, so this is a similar situation.
> 
> Compared to RAW: Ancient Black Dragon has Perception + 16 in RAW, +12 in my system

____________________

> mechanically, a dozen tiny bonuses do feel meaningful, while a single tiny bonus is easily forgotten.

In either case the character notes the half proficiency on their character sheet. One comes with choices, the other is automatic. So if the argument is that a +1 bonus is not meaningful, then that doesn't hold water when Jack of All Trades exists.

**Comment by mlenser** [comment]
Expertise has been removed for PCs
