### ISSUE TITLE
Interacting with objects in another creature's space

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#56]
The rules say:

 > When a creature tries to interact with an object in a space occupied by a hostile creature it chooses to make an Acrobatics or Athletics check contested by the hostile creature’s Acrobatics or Athletics check. If the creature attempting to interact with the object wins the contest, it can interact with the object.

Does that takes an action? Interacting is usually free once per turn, but the paragraph right above that one says:

> The GM might require you to use an action for any of these activities when it needs special care or when it presents an unusual obstacle. 

So, I'm not sure which action is required to kick/pick up an weapon under another creature. If it's a whole action, I think disarming maneuvers are quite bad then.

**Comment by mlenser** [comment]
With any concoction/maneuver/spell you have to evaluate the consequences of it happening.

Options like Hamstring will slow down the creature, making it possible that they can't attack for a turn or two, but that would require team coordination, positioning, and ranged attacks only. A very large cost.

Disarm, if successful, would be debilitating to any monster with a manufactured weapon. It isn't like other effects where it wears off. If the weapon is removed, it is likely removed for the whole fight.

The Champion for example does 3 attacks with a 2d6+5 (12) greatsword. So 36 damage a round. If you remove the greatsword we're looking at 1+5 (6), or 18 damage. So the Champion would do half as much damage with almost no ability to fix it.

The Berserker does 1d12+3 (9), or 1+3 (4), a little under half.

The Bugbear Chief does 2 attacks with 2d8+3 (11). So 22 damage a round. 1+3 (4) if you remove the weapon, or 8 damage. The bugbear does ~36% of its original damage.

Some monsters like the Bugbear Chief have backup weapons and that makes this issue much less problematic. But for monsters like Berserker and Champion this issue is rather substantial.

If all monsters with manufactured weapons had backup options (like they should, imo), then Disarm could probably be 2 stamina.

_________

> Does that takes an action?

Yes. The same as Overrun, Shove, etc take actions. If you're just picking a weapon off the ground, no. If you're fighting another creature to bend down and pick up a weapon at their feat, then yea.

We could make the saving throw with levels: if they fail by 4 or more then it is flung to a space not under their feet.

**Comment by mlenser** [comment]
Disarm maneuver recalculated and reworked a bit. It is now 2 stamina dice, does damage right away, and has the ability to knock the weapon further away from the creature if it fails by 5 or more.
