### ISSUE TITLE
Some stun spells are better than others

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#571]
[Bind Blood](https://www.kryxrpg.com/spells/bind-blood), [Hold Creature](https://www.kryxrpg.com/spells/hold-creature), [Stasis](https://www.kryxrpg.com/spells/stasis), and [Paralytic Poison](https://www.kryxrpg.com/spells/paralytic-poison) are all the same - spend 2 mana, 1 min concentration, creature within 60 feet makes a save or gets stunned for the duration with saves every turn.

However, [Psychic Crush](https://www.kryxrpg.com/spells/psychic-crush) and [Memento Mori](https://www.kryxrpg.com/spells/memento-mori) are both strictly better. as they also deal 2d6 psychic damage. Memento Mori is even better than that, with a range of 120 feet.

There are also some differences in immunities - Hold Creature doesn't affect constructs/undead, Bind Blood doesn't affect creatures without a blood, and (possibly) Psychic Crush and Memento Mori don't affect mindless creatures. However, I think these flavorful differences are fine, as long as we address the basic mechanics. Also, the damaging ones don't have augments that paralyze, but maybe ones could be added to them now..?

**Comment by Marcloure** [comment]
Yeah, good catch. This was caused when hold creature's paralyze was increased to 3 mana

**Comment by itamarcu** [comment]
Oh, also worth mentioning (in context of balancing these): [Death Clutch](https://www.kryxrpg.com/spells/death-clutch)

Pretty much the same as Hold Creature, Stasis, etc - except 3 mana and deals 7d6 damage every turn (plus half on the last turn).

**Comment by mlenser** [comment]
Psychic Crush and Mememnto Mori can never paralyze.

The differences here are relatively minor. 7 damage is nice, but ultimately not super meaningful at 5th level.

This should be fixed, but it's not a major issue.

**Comment by itamarcu** [comment]
It's not super meaningful but it's more than nothing. It makes these spells particularly useful as concentration-stoppers, since a failed save (stunned) instantly stops concentration but a successful save (half damage) still has a chance to stop the target's concentration.

If you want to balance them while keeping the damage, I suggest reducing the range of the two abilities to 30 feet, and making them unable to target creatures with Intelligence lower than -2 (or "mindless" creatures). I think it makes sense, that "showing a creature a glimpse of its own demise" won't do much to a zombie, a golem, or an ooze.

**Comment by mlenser** [comment]
Mememnto Mori was meant to be 60 feet - I've corrected that.

**Comment by mlenser** [comment]
These spells have different use cases
- [Hold Creature](https://www.kryxrpg.com/spells/hold-creature) and [Stasis](https://www.kryxrpg.com/spells/stasis) are more neutral - they could be used to restrain someone without hurting them
- [Bind Blood](https://www.kryxrpg.com/spells/bind-blood), [Memento Mori](https://www.kryxrpg.com/spells/memento-mori), [Paralytic Poison](https://www.kryxrpg.com/spells/paralytic-poison), and [Psychic Crush](https://www.kryxrpg.com/spells/psychic-crush) are very offensive and damaging
- [Death Clutch](https://www.kryxrpg.com/spells/death-clutch) is a lot like the second group, but persistent and fortitude based.

**Comment by mlenser** [comment]
- **Blood**
  - Bind Blood changed to be similar to Memento Mori and Psychic Crush, but more damage as it is Fortitude [#571](https://github.com/mlenser/kryx-rpg-issues/issues/571)
- **Fate**
  - Memento Mori corrected to 60 feet instead of 120 feet and can be augmented to paralyze [#571](https://github.com/mlenser/kryx-rpg-issues/issues/571)
- **Mind**
  - Hold Creature range increased to 120 feet [#571](https://github.com/mlenser/kryx-rpg-issues/issues/571)
  - Psychic Crush can be augmented to paralyze [#571](https://github.com/mlenser/kryx-rpg-issues/issues/571)
- **Poison**
  - Paralytic Poison changed to be similar to Memento Mori and Psychic Crush, but more damage as it is Fortitude [#571](https://github.com/mlenser/kryx-rpg-issues/issues/571)
- **Time**
  - Stasis range increased to 120 feet [#571](https://github.com/mlenser/kryx-rpg-issues/issues/571)
