### ISSUE TITLE
Metamagic - Heightened Spell cost

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#573]
[Metamagic](https://www.kryxrpg.com/feats/metamagic) - Heightened Spell:
> When you cast a spell that requires an attack roll or forces a creature to make a saving throw to resist its effects, you can expend 2 metamagic, mana, or psi to gain advantage on the first attack roll of the spell or 3 metamagic, mana, or psi to give one target of the spell disadvantage on its first saving throw made against the spell. You can not use this metamagic option in combination with other metamagic options.

My questions:
1. Why does it cost 2 MM to gain advantage but 3 to give disadvantage? Why are attack roll spells and saving throw spells not the same? The value difference between a miss and a hit is frequently bigger than the difference between a saving throw success and a saving throw fail (specifically for damaging spells). Missed spell attacks will usually do nothing, while successful saving throws still make the target take half damage.
2. Why only advantage on the first attack roll of a spell? I understand why it can only give disadvantage to one save (otherwise AoEs and multi-save spells are the best use), but with attack rolls, you don't have "AoE attacks"; the only spell that involves multiple attack rolls is Scorching Bolts, and I think it certainly makes sense for the metamagic to give advantage to all bolts, mathematically. Other than that, I guess it prevents repetitive advantage with Animate spells, but for those a more specific distinction could be made.

My suggestions:
- Make it cost 2 for both advantage attacks and disadvantage saves, or make it cost 3 for both.
- Change the advantage attacks' wording to: "gain advantage on each attack roll of the spell until the end of the turn".

**Comment by mlenser** [comment]
> Why does it cost 2 MM to gain advantage but 3 to give disadvantage?

Attacks have a high chance of hitting, so advantage changes the chance to hit from ~60% to ~85%. And if it hits, it's just damage pretty much.
Saving throws have a much lower chance of success, so when the creature has disadvantage the benefit is much higher. And when that saving throw fails, it can often be a harsh condition.

By RAW a saving throw is 3 sorcery points. I added attacks at 2. Saving throw disadvantage should not cost less.

___________________

> Why only advantage on the first attack roll of a spell?

Because it is consistent and simple wording that leads to predictability. Wording like "gain advantage on each attack roll of the spell until the end of the turn" would be less clear for all cases except scorching bolts.


TBH I'd rather remove the advantage to an attack on Heightened Spell than use this wording. Heightened means the spell is harder to resist, not easier to hit. I think it was a mistake to add that part.

**Comment by mlenser** [comment]
Heightened Spell Metamagic can no longer give advantage on a spell attack
