### ISSUE TITLE
Commonality between Gravity and Telekinesis

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#594]
Perhaps there are some combinations to be made with themes here or perhaps these themes can share many spells.

Force should maybe be split between raw magic (magic missile, detect magic, alarm) and barriers. I believe barriers is quite different.

**Comment by itamarcu** [comment]
Force is currently:

**Force Damage** - Force Beam, Disintegrate, Force Spear, Force Sword, Force Weapon, Magic Missiles, Force Hail, Homing Motes

**Force Constructs** - Magical Ward, Persistent Armor, Blade Ward, Mage Armor, Floating Disk, Force Barrier, Force Bulwark, Force Hand, Force Shield, Tiny Hut, Wall of Force, Invulnerability

**Utility Over Magic** - Magic Sense, Sense Magic, Martial Empowerment, Glyph of Warding

**Generic Magic** - Prestidigitation, Alarm, Knock/Lock

"Force Damage" itself, for most of these spells, is basically just a generic formless kind of damage, that isn't exactly physical, goes through most creatures' resistances, and is very magical.  However, force damage is not really related to force constructs - these are probably better described as simply being forcefields.  

Exceptions:
- Disintegrate - a green beam of matter-destruction, while all other attacks are just generic "magic beams".
- Force Sword - it's a sword-shaped creation that also does force damage.  Is it a force construct?  maybe it doesn't really matter, because it can't do anything but deal damage?

Forcefields in media are generally considered to be "hard energy", "hard light", "magic matter", etc.  I think connecting "pure magic damage" and forcefields isn't a stretch, in my opinion. If we choose to split it, I think it will be difficult to justify taking the forcefields/barriers theme, unless it gets more versatility.  In addition, "pure magic" will need to go somewhere.

I don't think Telekinesis and Gravity are really similar to Force, though.  The only real point of similarity is Force Hand, and it might better as a Telekinesis-only spell.

Maybe some magic-utility spells could be moved to Antimagic, but that might require changing that theme to just be about generic magic-affecting magic (metamagic?) and that might not be desirable.

**Comment by mlenser** [comment]
The barriers is where they are similar. Inertial Armor, Inertial Barrier, and Inertial Wall. Either they shouldn't exist on telekinesis/gravity or should be reflavored for telekinesis.

**Comment by mlenser** [comment]
> add a Gravity power surge to the suffused.  make it similar to the Telekinesis surge, but no damage and in any direction of your choice instead of just push/pull?

**Comment by itamarcu** [comment]
My suggestions:
* **Remove Kinetic Barrier, Kinetic Bulwark, Inertial Armor, Inertial Barrier, and Inertial Wall.**  Telekinesis in media is almost always about moving things around, not about blocking movement.  When it includes blocking movement, it's usually a temporary reaction from the user (e.g. holding your hands forward and making bullets stop in mid-air); not something they maintain for a long period.
* **Remove Reverse Gravity and Gravitational Well from Telekinesis.**  While that theme can imitate gravity magic in certain ways, it shouldn't be able to do the "classic" gravity-themed spells when they aren't really telekinesis-related.  For Reverse Gravity, while it's really fitting for a telekinesis user to lift dozens of objects/creatures at once, it doesn't make sense to *reorient* their gravity like this for an entire minute afterwards.  I think the spell should be recreated as something similar to Levitate but in a sphere (maybe just an augment to Levitate).
* **Remove Minor Telekinesis from Gravity**.  It doesn't fit.
* **Add Immovable Object to Gravity**.  I think it really fits both themes.
* **Add Wall Bind to Gravity** - It's classic for gravity manipulators to do this kind of stuff.  Maybe you can even remove it from Telekinesis.
* **Add a "Wallwalking" (permanent augmented wall bind) 10th level Gravity feat** - because it's just so fitting for high level gravity manipulators to constantly run on walls/ceilings, and it feels like a good flavorful alternative to Ascendant Step and Gravity Defying.  Personal and permanent gravity manipulation feels perfect.
* **Add [Feather Fall](https://www.kryxrpg.com/spells/feather-fall) to Gravity.**
* **Add [Airy](https://www.kryxrpg.com/feats/airy), [Updraft](https://www.kryxrpg.com/spells/updraft), and [Whirlwind](https://www.kryxrpg.com/spells/whirlwind) to Gravity, as reskins.**  Airy can be renamed "Enhanced Leap" or "Decreased Personal Gravity" and the language part can be removed or replaced with something else.  Updraft can be renamed "Uplift" or "Upend", with flavor text tweaked to say it uses gravity and not wind to temporarily pull somebody upwards.  Whirlwind can be renamed "Gravity Vortex", and maybe have some other minor details changed.

Overall, these changes should make Telekinesis feel more unique and less like it draws from these other two fields.  If some effects (like Kinetic Bulwark or Inertial Barrier" are still mechanically interesting, I suggest moving them to other themes and reflavoring them (e.g. Force, Earth).

**Comment by mlenser** [comment]
> **Remove Kinetic Barrier, Kinetic Bulwark, Inertial Armor, Inertial Barrier, and Inertial Wall.**  Telekinesis in media is almost always about moving things around, not about blocking movement.

Kinetic barriers exist in many genres. See https://masseffect.fandom.com/wiki/Codex/Weapons,_Armor_and_Equipment#:~:text=Kinetic%20barriers%20are%20repulsive%20mass,without%20knocking%20away%20their%20chair. for example

> **Remove Minor Telekinesis from Gravity**.  It doesn't fit.

How does it not? Gravity can move objects around. Maybe not all the parts, but gravity can have a cantrip like this.

__________________

Overall your suggestions make gravity, telekinesis, and force more unique. I'm not sure that all should exist in their currenty definitions though.

**Comment by itamarcu** [comment]
> Kinetic barriers exist in many genres
Yup, but the specific one you linked (and most of the ones I know) are pretty much the same as forcefields, or "hard energy constructs".  Not *telekinetic* - i.e. not something that is created by a person focusing and using their psychic power.

I think there's room for abilities like these, I just think it would better fit in other themes like Force.

> gravity can have a cantrip like this

Yeah, exactly.  I do think Gravity should be able to move things around, but the ability to do stuff like use lockpicks from a distance feels like too much minute control, when gravity generally doesn't allow for that.  Maybe this could be a new cantrip, that doesn't allow for fine control but has better range and/or better weight thresholds.

**Comment by Marcloure** [comment]
Based on the discussion from #743, you guys seem to want to allow Gravity do anything that gravity does. Thing is, gravity is just another force (not really, but let us not go into that), so anything a force can do, Gravity can as well. You can push, pull, counterweight, pin objects, make them move in any direction and to any point. You can make Gravity affect an area or a single object, etc.

Considering all this, Gravity is just an "apply force and cause acceleration at a distance" theme, thus making it the same as Telekinesis, since Telekinesis is also "apply force and cause acceleration at a distance". I don't see what is the difference between the two; anything one can do, the other would do as well, since both are themed around the same concept.

---

As for the Force theme, I think it's mostly fine. The issues I see there are Alarm, Warding Glyph, and Knock Lock, but I don't know where else these spells would go. The theme could be renamed as well, to tell it's not about applying forces, but about Octarine magic (it could be named Octarine, after all).

**Comment by mlenser** [comment]
> you guys seem to want to allow Gravity do anything that gravity does. Thing is, gravity is just another force (not really, but let us not go into that), so anything a force can do, Gravity can as well. You can push, pull, counterweight, pin objects, make them move in any direction and to any point. You can make Gravity affect an area or a single object, etc.

The things you describe are what is generally accepted as Gravity powers. See https://powerlisting.fandom.com/wiki/Gravity_Manipulation for examples.


> both are themed around the same concept.

Largely, yes. Hence this issue. Though there may be differences and that's why this issue exists. Until this issue is solved, they are pretty much the same.

## Telekinesis
![image](https://user-images.githubusercontent.com/235857/113700450-25b9ca00-96d7-11eb-8585-de78a1186546.png)

## Gravity
![image](https://user-images.githubusercontent.com/235857/113700337-0327b100-96d7-11eb-9a01-4713332ee37d.png)



___________________


> it could be named Octarine, after all

That word means nothing in English. Only Discworld. The wiki isn't detailed enough to know if that is the same thing, but either way the word is too obscure.

In 5e, Force is defined as "Force is pure magical energy focused into a damaging form. Most effects that deal force damage are spells, including magic missiles."

Which is what that theme is. It is similar to [Sorceries in Dark Souls](https://darksouls2.wiki.fextralife.com/Sorceries)

If there is a better word to describe "raw magic" than force (which would also rename the damage type) then I'm open to it, but I haven't seen one.

**Comment by Marcloure** [comment]
There is a thing I don't understand: why the desire to have both Telekinesis _and_ Gravity as separate themes? Both deal with acceleration and forces, so why split them?

**Comment by itamarcu** [comment]
Telekinesis = an invisible hand is grabbing and moving and stopping things around you, applying force on things to move them around, often with precise control.

Gravity = you make one thing pulled towards or pushed away from another thing.

I think this is the most basic difference between the two.  Gravity has less control but more raw power, in a way.  It can more easily affect a large area, while telekinesis has to affect specific objects.

**Comment by Marcloure** [comment]
Well, if that is the difference, it isn't being applied in many instances:
- Immovable Object is somewhat precise, since it affects only that object, and it isn't attracted to another thing. It's a dragging force holding the object in place
- Telekinesis has Gravitational Well, Kinetic Onslaught, and Kinetic Explosion, which are not precise or a dragging force
- Telekinesis also has Entangling Debris, which seems to make everyone in the area generate a strong gravitational field

Gravity could have many other spells from Telekinesis with enough freedom of interpretation. For instance, Animate Object can be in Gravity if **a)** you make the objects ignore gravity, and **b)** you make them gravitate towards the target.

**Comment by itamarcu** [comment]
Immovable Object - I kind of agree that it's not super fitting for Gravity as much as it's just fitting "Space" (but we can't have that...).  I'd personally be fine with putting it in Telekinesis, though I'd like Gravity to have a spell that simply increases the weight of something, generally.

Gravitation Well - yeah, this should be Gravity-only.

Kinetic Onslaught - pretty weird spell, I'm not sure where its flavor comes from.  I guess it could be TK as much as it could be Gravity.  It seems like it's just Kinetic Explosion over and over again in the same spot, which is kind of odd.

Kinetic Explosion - this is actually fine for telekinesis because a lot of depictions of TK in media involve sudden application of force.  Force-pushing someone, blowing a lot of items away from you in all directions, stopping a bullet that is shot at you - they're all sudden force applied to something (in one direction or in all directions), and that seems fine to give to TK.

Entangling Debris - this is just Animate Objects on a piece of ground.

Animate Objects for Gravity - yeah, honestly I can kind of see this happening, or at least a form of it.  The spell itself is pretty weird because it give some sort of limited programming/sentience to the animated objects.  I think it could work if you rename it to something like Orbital Debris, flavored as a bunch of objects that follow one creature and harrass it by bumping into it a lot.

**Comment by mlenser** [comment]
I have cleaned up some the Gravity and Telekinesis themes.
    - Gravitational Well removed from Telekinesis.
    - Reverse Gravity removed from Telekinesis.
    - Wall Bind added to Gravity.
    - Unburden added to Air, Gravity, and Telekinesis as it is similar to levitate.
    - Gravitational Pull added to Gravity as a reskin of Earthbind.
    - Wall Walker added to Gravity and Telekinesis.
    - Minor Gravity added to Gravity as a reskin of Minor Telekinesis without the minute control, but longer range.
    - Feather Fall added to Gravity.
    - Gravitational Buoyancy added to Gravity as a reskin of Airy and Athlete.
    - Upend added to Gravity as a reskin of Updraft.
    - Gravity Vortex added to Gravity as a reskin of Whirlwind.

I've also opened https://github.com/mlenser/kryx-rpg-issues/issues/984 and https://github.com/mlenser/kryx-rpg-issues/issues/985 to add more Gravity and Telekinesis spells.
