### ISSUE TITLE
Mind Over Body is too powerful at higher level

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#598]
I think Mind Over Body is too strong at higher levels. A caster with the Mind theme can basically ignore picking proficiency in Fortitude save, and expend 1 mana to use its Will bonus instead of Fortitude. That is a +7~9 to a save with a single mana, more way more than conviction or other bonus spell at that level, and it allows the caster to have full proficiency in the other 2 saves.

I think Mind Over Body should allow a reroll, a just add a flat bonus, or something that doesn't invalidate having proficiency.

**Comment by itamarcu** [comment]
I suggest replacing "you may roll a Will saving throw instead." with one of:
1. You may add your Charisma, Intelligence, or Wisdom to the result.
2. You may add half your Will saving throw bonus to the result.
3. You may roll a Will saving throw with disadvantage.
4. You may add a bonus of +3 to the result (and another +2 per augment).  This bonus cannot exceed your Will saving throw bonus.

**Comment by DalenWBrauner** [comment]
A spattering of things we went over:
- > Most of the above are good suggestions, but change the spell from 'dodging a Fort save' to 'augmenting a Fort save'. Which is fine, but completely different: it ends up being a better pick for characters with High Fortitude than with Low Fortitude, because that's what it augments.
- > Rolling with disadvantage will put off a lot of potential casters, as they might actually end up with a worse result after spending mana and a reaction. This would feel ***really terrible*** to use.
- > I thought about suggesting an augment that allows you to remove the penalty, but Marcloure created the issue to specifically address "at higher levels", so I'm unsure if that makes sense.
- > At low level, with +1/+2 prof and +3/+4 stats, your bonus would be +4 to +6, so half would be +2/+3.
- > At 9th level, a Psionicist would probably have +4 and +5 for a total of +9 Will save, so this ability would grant them +4.
- > At the very highest levels this would scale to +5.

**Comment by mlenser** [comment]
I agree that getting a 5+ bonus as a 1 mana spell is too much. I agree that replacing Fortitude saves with Will saves for 1 mana is far too broken and effectively lets you stack up Will and Reflex and ignore Fortitude.

I think the the solution is that Mind over Body gives a +2 bonus to Fortitude saving throws (the same as Thought Shield does for Will). This spell is then good for all characters. It is not any better for characters with a high or low Fortitude as both can roll within 2 of succeeding on pretty much all saves in the game.

**Comment by mlenser** [comment]
Mind Over Body spell and maneuver reworked to give bonuses to Fortitude saving throws
