### ISSUE TITLE
Mind Blast is too powerful

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#612]
Compared to Archon’s Trumpet, Mind Blast is quite better, since it also deals damage and can be used as a line.

Now, compared to Hold Person and Psychic Crush, Mind Blast is also really great, since it's an AOE stun that deals damage. Of course, its range is quite shorter than Psychic Crush's, so that may be fine.

**Comment by itamarcu** [comment]
Archon’s Trumpet lasts for a minute (same with HP and PC), while Mind Blast lasts for a single turn.  That's what makes it less powerful.

**Comment by Marcloure** [comment]
Hmm, that is true. I missed that

**Comment by Paulorpribeiro** [comment]
Practically, it won't last for a minute, it will last for as long as the rest of the party takes to kill the stunned (or paralyzed) foe(s) or they succeed on the save. I'd be amazed if you need (have to) concentrate in hold person (for example) for more than one round after cast. In theory the aoe is not OP because the stun is shorter, but in practice, this difference is negligible because of continuous saves and the rest of the party attacking the stunned foe. If they are paralyzed instead,   the enemy's life expectancy is shorter still.

**Comment by mlenser** [comment]
> Practically, it won't last for a minute

Durations aren't balanced for 1 minute. The spreadsheet gives a Will save of up to 1 minute ~182% of the value.

**Comment by itamarcu** [comment]
@Paulorpribeiro - paralyzed creatures can die super fast, but stunned is more about incapacitating an enemy than about making it a better target (IMO).  If all you want is the attack advantage (for party focus fire), Faerie Fire is an easier way to do it.  But with spells like Hold Person or Archon's Trumpet, you can disable certain enemies to free you up to deal with other enemies.  For example, you could stun the big tough boss to be able to focus on the healer without getting punished or blocked by the big guy.

**Comment by mlenser** [comment]
Comparisons are off as Mind Blast only lasts 1 turn
