### ISSUE TITLE
Critical hit and "critical miss"

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#640]
The critical hit and "critical miss" (automatic miss in this case, but crit miss is more evocative) are described in the 2d10 as "you critically hit if you roll 18, 19 or 20 and you automatically miss if you roll 2, 3 or 4".

I think a little bit simpler way would be to say
Crit hit: you crit if you roll 9+ in both dices
Crit miss: you auto fail if you roll 1 or 2 in both dices

The chance is a little lower if math doesn't fail me (4% for both, against 6% in the current rule, 5% in regular d20 as a baseline). That's pretty minor, but I think knowing wether you crit or auto fail right away without summing the dice is more exciting and breaks a little bit of the norm. You just take a look at the dice and see "crit!" without bothering to sum the dice.

Just my opinion, but I think would look cooler

**Comment by mlenser** [comment]
It could also be done with doubles. 1-1, 2-2, 3-3, 4-4, 5-5 are failures and 6-6, 7-7, 8-8, 9-9, 0-0 are crits. But that would have a big impact on the math in not such a fun way to calculate.

With your suggestion you've removed 3-1 and 1-3 and 8-10 and 10-8. You've kept 1-1, 1-2, 2-1, 2-2 and 9-9, 9-10, 10-9, 10-10. Not sure it is really better.

**Comment by Paulorpribeiro** [comment]
It's easier to remember and asses on a first glance (no math required) and the change in the math is minor, 1% less than the "standard" chance of 5% On d20

**Comment by mlenser** [comment]
It's practically as "difficult" to compare both above 9 as it is to compare both above 18. If you want "easy" then doubles would be the choice.

**Comment by itamarcu** [comment]
I thought about this again and was bored, so, I used AnyDice to calculate the results:

https://anydice.com/program/23092

### Results

- **5e RAW Crit (natural 20 on 1d20)**: `5%` crit, `9.75` with advantage, `0.25` with disadvantage
- **Current Crit (2d10 rolling total 18 or more)**: `6`, `14.9` adv, `1.1` dis
- **High Doubles (2d10 rolling 5+5, 6+6, etc)**: `5`, `14` adv, `3.5` dis
- **High Rolls (2d10 rolling 9+ on each die)**: `4`, `10.4` adv, `0.8` dis

### Analysis
- The four options are pretty similar overall
- RAW Crit has a very low chance of critting with disadvantage, compared to the others
- Current Crit and High Doubles both have a relatively very high chance of critting with advantage;  it's ~2.6x as likely as with a normal roll.  Compare with RAW (~1.9x).
- High Doubles has a pretty high chance of critting even with disadvantage
- High Rolls seems almost identical to Current Crit but with 33% less crits overall.

I don't think the spreadsheets has any data about how often a character rolls with advantage or disadvantage, so I will have to give a rough estimate:  I believe it's something like 8% for advantage and 3% for disadvantage (because generally if you have advantage you'd rather attack, and if you have disadvantage you'd rather do something else).  

**Based on these chances, I think the current crit system will lead to expected damage that is about +1.33% higher than RAW, with High Doubles also around +0.44%, and High Rolls being -0.82%**.  I based these calculations on the diffs between the values - formula looks like `8% * (14.9-9.75) + 3% * (1.1-0.25) + ((100-8-3)%)*(6-5)` for current crit compared to RAW for example.  These obviously depend on the 8% and 3% numbers that I arbitrarily chose above.

### Outcome
Based on all of this - I think High Doubles and High Rolls are valid, balanced alternatives for the crit rules, and I'm in favor of adding them as variant rules in that section of the website.  I think the main reason to choose one method about another would be how fun and easy it feels, in the table, to determine if a roll is a crit or not.

**Comment by mlenser** [comment]
High doubles changes the math quite a lot. Let's say you roll a 5+5 and add 4 to a roll. That's 14. 14 against Defense 16 now hits when it previously did not. That's too difficult of math for my tastes.

**Comment by itamarcu** [comment]
Sorry, with High Doubles, I meant that you crit if you roll 6+6, 7+7, 8+8, 9+9, or 10+10, regardless of the modifier.  This means a 5/100 (5%) chance of critting, regardless of your modifier.

**Comment by mlenser** [comment]
> Oh, but I think I see the issue with double 6s auto-hitting, the chance of hitting high-AC creatures increases overall by 1%, or 2% if you'd otherwise need to roll 15 or higher.

Exactly. My gut says this probably isn't good.
