### ISSUE TITLE
Improve Updraft below 5th level

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#641]
The Updraft cantrip does absolutely nothing until 5th level: it raises a creature 5 feet into the air and then releases it, dealing no damage and no condition. It needs to do something at this level too, or it's not a cantrip and should be removed.

**Comment by itamarcu** [comment]
The cantrip could say that the target lands prone.  A cantrip to make the enemy fall prone seems reasonable, and it's already something that would happen at higher levels.

Do note that the cantrip is also useful for utility - you can lift your friends to high places!

**Comment by mlenser** [comment]
Prone is too strong for low level cantrips. Until 9th level Upsraft is a utility cantrip.

Until 9th leve lit is just as shem says:
> Do note that the cantrip is also useful for utility - you can lift your friends to high places!

**Comment by mlenser** [comment]
Updraft changed to a 1 mana spell

**Comment by itamarcu** [comment]
Why not just keep the cantrip as it is? 

The new spell:
> On a failed save, the creature is lifted into the air and then slams into the ground unless it has some means to stay aloft. If the creature falls, it takes 4d6 bludgeoning damage and is prone.
On a successful save, the creature half as much damage, but doesn’t fall prone.

...is disappointing. It removed all the fun utility of the cantrip, like reaching stuff on the ceiling, temporarily moving enemies out of cover, or jumping higher to reach a rope.

I think the "become prone" part of the cantrip was the least interesting part of it, and if the issue is with prone being too good at low level, it can just be changed.  The cantrip could say it pushes the creature 10 feet upwards and the creature doesn't fall prone.  It's not even unrealistic - people land on their feet at that height all the time, especially if they have the extra second of being pushed upwards and orienting themselves.

**Comment by mlenser** [comment]
> Why not just keep the cantrip as it is?

When a cantrip has to effectively "do nothing" in the first tier then it is an indication that the effect (prone) is too strong to be a cantrip.

> It removed all the fun utility of the cantrip, like reaching stuff on the ceiling, temporarily moving enemies out of cover, or jumping higher to reach a rope.

Being raised 1.5 meters is rarely useful and reading your action to updraft someone out of cover seems like it's not worth the effect.
