### ISSUE TITLE
Drown spell saves

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#656]
https://www.kryxrpg.com/spells/drown

Currently the spell requires one immediate save failure to get the target to drown, and then an additional save at the *start* of the target's turn to see if it takes damage and keeps the effect.

I don't think the sheet accounts for the timing here - how the damage isn't immediate, and the save is at the start of the turn.

I think the repeated save should go to the end of the creature's turn.  If the damage needs to be reduced, it's fine - the intent of the caster is to surround the target's head with water, not to inflict the most damage.

**Comment by Paulorpribeiro** [comment]
If the save is at the start of its turn, there should be no immediate save (when the spell is cast), otherwise the target has 2 chances to end the spell before it affects it for even one turn.
I think the options here are make the target save (and take the damage) at the end of its turn or drop the initial save (when the spell is cast) and keep the save at the start of the turn.

**Comment by itamarcu** [comment]
I think moving it to the end of the turn is better. If you drop the initial save until the start of the creature's turn, you make the spell automatically affect creatures for a brief period, and that's too powerful.  For example, you could use it on a spellcaster to prevent them from counterspelling you or to give advantage to allied ranged attacks.

**Comment by mlenser** [comment]
The goal is that the damage takes effect before their turn. Corrosive Consumption, Death Clutch, Five Shadows, Inflict Wounds, etc all work in that way so that the creature potentially dies before it can attack. Else the value is more like acid where it is delayed a turn.

Burst with Light is end of turn, but really shouldn't be. I'll try to fix both.

**Comment by mlenser** [comment]
Drown adjusted to not have two saving throws
