### ISSUE TITLE
Slowing spells are too costy

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#672]
_Cold Snap_ and _Slow_ are concentration spells that deal no damage, and give slow 3 at 3 mana. That is the same cost of paralyzed. Paralyzing spells, however, take 2 actions, so that is fair.

Now, _Bonecrush_ is a maneuver that takes 1 action, deals damage, requires no concentration, and causes Slow 3 at 5 Stamina. Considering that 1 mana = 3 stamina, that maneuver should cost at least 9 Stamina (not considering that it deals damage, and requires no concentration, so it doesn't limit your combos).

**Comment by itamarcu** [comment]
Relevant: #341 

Quoting Kryx:
> Slow makes the enemy 20% more likely to be hit by your allies attacks and fail your allies Reflex saving throws. That's effectively a 20% damage boost to all allies smart enough to attack or use a Reflex save. That's definitely worth a 1 mana spell.

I still agree with you about the direction but it'll need to be balanced.  Perhaps it could increase the level of Slow by +2 when augmenting?  or add extra creatures more easily, or add some extra status condition (e.g. disadvantage on first attack)

**Comment by mlenser** [comment]
Disorient can stagger (big part of slowed 3) at 2 stamina dice, or stun at 5 stamina dice.

But Cold Snap/Slow would be fine starting at slowed 2 and offering an increase to slowed 3. The problem comes in where hasted 2 is too strong for a 1 mana spell.
Hasted and Slowed are inherently tied together in this regard. Slow can't be 2 while hasted is 1.

**Comment by Marcloure** [comment]
Can't spells start at slow/hasted 1 and progress by 2 slow per mana? This way you cause slowed 4 at 3 mana (1+2+2), not slowed 3. Well, I guess then you would have little incentive to use 3 mana instead of only 2.

**Comment by mlenser** [comment]
Hasted is exactly where it should be.
- 1 mana: +3 meters speed and it gains a +2 bonus to Defense and Reflex saving throws.
- 2 mana: above & extra utility action
- 3 mana: above & extra action can be used for utility or attacking

**Comment by itamarcu** [comment]
> Hasted and Slowed are inherently tied together in this regard. Slow can't be 2 while hasted is 1.

Why is that?

They aren't mechanically symmetrical because Haste automatically works on a willing creature while Slow has a chance to fail. Due to this chance of failure, I think it's very natural for Slow to start at Slowed 2. 

If it feels ugly for some reason, maybe Slow should be partially split (into a "variant" use, similar to healing word) or completely split into a new spell. 

But, I don't think Slow should be meaningfully worse just for the sake of symmetry, and Cold Snap definitely shouldn't be worse just because a different spell has to be symmetrical this way.

(It's also worth noting that the 5e spells are even less tied together - they're the same level and function almost like inverses, but Haste targets 1 allied creature while Slow targets up to 6 enemy creatures)

**Comment by mlenser** [comment]
Hasted and Slowed are inherently connected. One Hasted level removed one Slowed level and vice versa. Having them give different levels for the same mana makes them no longer counter eachother.

**Comment by mlenser** [comment]
Are there examples of low mana spells that provide better cc than Slow?

**Comment by Marcloure** [comment]
Maybe Five Shadows or Blindness (boith from Shadow)? They deal damage and cause other lasting effect, while slows often last only for 1 turn.

If the issue isn't that slowing spells are too cost, than is that the maneuvers are too cheap by my comparison in the original post.

**Comment by itamarcu** [comment]
> One Hasted level removes one Slowed level and vice versa. Having them give different levels for the same mana makes them no longer counter eachother.

True, that's a good point, though the chance of success still affects this balance.  If an enemy is casting Haste every turn (e.g. an evil time cultist buffing an evil time knight), and a player character is trying to counter them, casting Slow every turn will not be enough because it only succeeds about half of the time while Haste succeeds every time.

But, if it's important that it stays 1 for both - What about the option of Slow and Cold Snap affecting two creatures?  similar to how Bane targets 2 creatures.

**Comment by mlenser** [comment]
> maneuvers are too cheap by my comparison in the original post.

I'm not too concerned about the maneuvers. The spells may seem weak, but there are no comparable options to compare with. The sheet isn't perfect to compare these things so I feel without a better spell option to compare with that the spells are decently placed.

> What about the option of Slow and Cold Snap affecting two creatures? similar to how Bane targets 2 creatures.

**Comment by mlenser** [comment]
- **Ice**
  - Cold Snap now targets two creatures [#672](https://github.com/mlenser/kryx-rpg-issues/issues/672)
- **Time**
  - Haste/Slow now slows two creatures and specifies that you can mix and match the effects when you augment it [#672](https://github.com/mlenser/kryx-rpg-issues/issues/672)

**Comment by Marcloure** [comment]
A really strong point for these maneuvers is the lack of concentration. Not because they can be broken this way, but because you can stack a lot of effects. Battle Leader + slow + dot, for instance. Now, if you use Cold Snap, you won't be using most of your other spells
