### ISSUE TITLE
Courage Cantrip Suggestion

### ISSUE THREAD

**Issue by RodrigoZanon** [mlenser/kryx-rpg-issues#678]
I have two suggestions for Courage's cantrips.

**WarCry / BattleCry** or something like that

> As an action, you shout a warcry that frightens your foes. Each creature within 5 feet of you must make a Will saving throw.
> On a failed save, a creature takes 1d6 psychic damage.

The flavor is, that the enemies will fear the combat against you and your allies, this cantrip can be added in Fear Theme as well.
The second one:

**Precise Strike/ Combat Strike/** Or something like that

> As an action, you shout commands to an ally to strike an enemy. Chose one enemy within 30 feet. Your ally gain advantage on the first attack they make against the target during the duration. On a hit, add 1d4 damage to the attack damage roll. 
> If you miss by 4 or less, add half as much damage.

The flavor is similar to the True strike, but in this case, giving the advantage to an ally instead of yourself.

**Comment by mlenser** [comment]
War Cry dealing psychic damage to everyone around seems a bit more like something a Banshee would do than a War Cry.

Precise Strike: This is likely too strong for a cantrip. Advantage would already be worth a lot (much more than disadvantage due to features like Sneak Attack and the ability to pile on effects).

**Comment by itamarcu** [comment]
Precise Strike should basically be "Help but a bit better", IMO.  Stronger because you're expending a known cantrip slot for it, and because cantrips can scale.

This suggestion is like Help except:
- 30 ft range instead of 5 ft
- bonus 1d4 damage

I think we could remove the bonus damage, reduce the range, or somehow add an extra limit (e.g. requiring your reaction to grant the advantage).

Alternatively it could add to the attack roll?

**Comment by Marcloure** [comment]
Master Tactician is a 6th level feat that:
> Once on your turn when you use an action to make a weapon attack, you can use the Help action [increased to 30 ft.] without using an action

This feat allows you to give advantage to someone requiring no action. A cantrip that extends the reach of your help action to 30 ft. doesn't seem that powerful. Maybe just remove the extra damage.

**Comment by mlenser** [comment]
Guide added as a cantrip to the Courage theme

We already have Battle Cry maneuver and spell, Rally Cry feat, and Lead the attack (which is a war cry). I think that's enough war cries, plus the version proposed doesn't fit courage imo.
