### ISSUE TITLE
Consumptive Power feat is too strong

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#716]
https://www.kryxrpg.com/feats/consumptive-power

This feat is very strong. For full casters that take relatively less damage, this can give them 5+ mana per day, and for gishes this feat can double their mana pool. The feat also greatly increases in power as the character gains level.

The feat should probably be increased to 6th level (to be together with metamagic, which also gives virtual mana), and the exchange rate should be 2:1 or 3:1.

**Comment by Marcloure** [comment]
Consider that a very tanky character with Con +5 can exchange 2 hit dice (2d10+10 = 21 hp) for a 2 mana healing spell (7d8 = 31 hp). Of course, losonig 2 hit dice means you'll have 1 fewer on the next day, but it's rare that you'll need all your dice anyway.

**Comment by mlenser** [comment]
Consumptive Power cannot be used to restore your health

**Comment by mlenser** [comment]
I think preventing it from being used to restore your own health should be a huge improvement.

________________

> For full casters that take relatively less damage, this can give them 5+ mana per day, and for gishes this feat can double their mana pool.

If full casters are not taking damage either:
- they are burning mana to prevent being damages which is ok
- they are not being threatened enough either in melee or by aoe effects
- their tank is taking far too much damage and is barely alive

I believe this is a playstyle problem, not so much a problem that the system can fix beyond what I've already done by making everything short rest based.
___________

> gishes this feat can double their mana pool.

Gishes are often in melee so if they are sacrificing their health for mana they're going to have a bad time. I think some of the above applies here as well.

________________

> the exchange rate should be 2:1 or 3:1.

1 Health die is equivalent to 3.5+2 or 3 = 5.5-6.5 health for casters and ~7.5-8.5 for gishes. That seems like a fair emount to exchange for mana at a glance. 2:1 would put us at 11-13 for casters and 15-17 for gishes. That is the equivalent of what a spell can heal and feels like a bit too much.

**Comment by Marcloure** [comment]
>  preventing it from being used to restore your own health should be a huge improvement.

This doesn't do it. It's quite more efficient to expend 2 hit die and convert it to mana to deal damage, and then expend 1 mana to heal yourself at the end of the day. Using hit die is always more economical, and you save your mana to healing yourself.

> If full casters are not taking damage

They take less damage, not no damage. And if they can cast 20% or more 2 mana spells, they will lose much less health killing everyone.

> Gishes are often in melee so if they are sacrificing their health for mana they're going to have a bad time.

It's not their current health though. It's not easy to expend all your 13 + 3 + 3 hit dice. And what I said about healing

I do believe it should at least be a 6th level feat. If you use it once per short rest, it gives you 2 mana, which is equivalent to metamagic. Of

**Comment by itamarcu** [comment]
I think it would be better if it also cost you actual health (e.g. equal to the roll of the health die, or 1d6 times the number of health dice).
In addition, it would add some fun tactical risk to the ability, because you *know* a player will one day desperately use this when they're at a single-digit amount of health.

This would match the thematics better.  A cultist unsheathes a knife, cuts her palm, and spills the blood on a magic circle. She is paying both with her immediate health (Health) and with her ability to recover from the injury later (Health Dice).

If you want to go even further, have this damage reduce your maximum health until the next rest.

> 6th level feat

I'm against this, because the flavor of sacrificing your own health to fuel a spell is something that even "weak" characters should be able to do.  

If there are balance concerns, I recommend just increasing the cost (e.g. losing a health die plus 1d6 health, reducing your maximum health, paying 2 dice for every 1 mana).

**Comment by mlenser** [comment]
Reworked Consumptive Power to
> You gain the ability to consume your life force em power your spells. When you cast a spell that doesn’t restore your health, you can expend Health Dice equal to the spell’s mana cost, instead of using any mana or psi. For each Health Die spent in this way, roll the die and add your Constitution. Your health is reduced by an amount equal to the total.

I'm also against 6th level.

I think these changes should make this option more balanced. Let me know if you think something is still off and we can reopen the issue.

**Comment by Marcloure** [comment]
> Your health is reduced by an amount equal to the total.

This wording is a bit weird. Is your max health being reduced, or are you taking damage that can't be reduced by any means?

**Comment by itamarcu** [comment]
I like this, with minor nitpicks:
- typo:  "force em power your spells"
- adding your Constitution feels bad because it means a character is kind of punished for being durable, or similarly rewarded for having a low constitution.  I think it would be better if you only added half your constitution.  Or even just make it a set number like 1d12, to avoid acting differently depending on the user's class/monster.

**Comment by Marcloure** [comment]
Dealing damage that equals to Hit Die + Constitution just means you are taking % of hp as damage, since your health is also equally larger or smaller. This makes the feat as powerful for full casters as for gishes.

**Comment by mlenser** [comment]
> This wording is a bit weird. Is your max health being reduced, or are you taking damage that can't be reduced by any means?

It's not damage. Your health is just reduced. This wording is used elsewhere, though almost always for maximum health.

I can change it to
> Your lose health equal to the total.


____

> adding your Constitution feels bad because it means a character is kind of punished

Exactly as Marcloure wrote:

> Hit Die + Constitution just means you are taking % of hp as damage, since your health is also equally larger or smaller. This makes the feat as powerful for full casters as for gishes.

Characters with more health will lose more. Overall there is no punishment for having more con, just the same % cost.
