### ISSUE TITLE
Call Animal should allow a command when you summon

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#719]
Call Animal and other summoning spells require two actions to cast and another action to issue a command. This means you can't issue a command on the same turn you call the creature, which isn't ideal. I think you should gain a free command when you summon it.

**Comment by mlenser** [comment]
I'm totally fine with summons taking a round to be ready. Summons are super strong, it'd make thematic sense, and they can still prove useful in that first round.

**Comment by Marcloure** [comment]
It's quite bad to cast a spell that will have basically no effect until your next turn (defend itself is not very helpful). It takes your concentration and three actions (two now, one later) for something that doesn't deal that much damage.

Well, you can cast it out of combat, but it's bad to even have to use your action to give a command. It's not like commanding a creature will increase your DPR or anything. It's probably the worst use of your action unless in a very specific case.

**Comment by mlenser** [comment]
> for something that doesn't deal that much damage.
> It's not like commanding a creature will increase your DPR or anything.

It adds a significant amount of DPR (the same value as other ongoing spells) while also providing utility, tanking, and other benefits.

> it's bad to even have to use your action to give a command

This is how other spells work (see flaming sphere) and how summons will work.

**Comment by Marcloure** [comment]
> This is how other spells work (see flaming sphere) and how summons will work.

Psychic crush and Earthen Grasp allow you to attack on the turn you summon them, and some of them also have hp.

I am not here to discuss its damage though, I think that is fine. But requiring 2 turns and 3 actions for a spell to take effect is too much. It would need to be the strongest spell by far.

**Comment by mlenser** [comment]
> I am not here to discuss its damage though, I think that is fine. But requiring 2 turns and 3 actions for a spell to take effect is too much. It would need to be the strongest spell by far.

The action cost is part of its balance. Removing that means I need to nerf it elsewhere.

> Psychic crush and Earthen Grasp allow you to attack on the turn you summon them, and some of them also have hp.

They don't take damage for your group. They can't fly, swim, burrow, or climb. They cannot be used for other extra purposes like scouting.

**Comment by Marcloure** [comment]
> They don't take damage for your group.

Earthen Grasp and Force Hand have health, so I guess they can do that. Now, to another point, what "taking damage for the group" means? What incentive the monsters have to attack the summon instead of anything else?

I suppose the incentive is to stop the damage the summons deal, but then isn't this actually a disadvantage? If call beast deals the same damage as Psychic Crush but it can be killed, isn't that a weakness in relation to the other spell?

**Comment by mlenser** [comment]
Creatures aren't going to rationally attack a hand of force or sand. That is a completely different situation for creatures that appear as normal creatures.

> what "taking damage for the group" means? What incentive the monsters have to attack the summon instead of anything else?

Summons are not balls of fire. They can and should be attacked. If they aren't, then the GM should. If enemies are smart then they can CC summons or go for the caster, but not basic enemies.


> If call beast deals the same damage as Psychic Crush but it can be killed, isn't that a weakness in relation to the other spell?

Psychic Crush happens automatically. There is no chance to stop it except concentration. Call Beast having a possibility of being killed doesn't make it weaker - if the creature is killed then it has eaten a lot of damage which helps mitigate damage to others.

_____________

Look, I'm not set on 3 actions being the perfect solution, but there is no way that I'm going to rebalance companions and all summoning spells to handle utility. I'd be more likely to change summoning spells like Call Beast so they aren't instant, but take several minutes. It makes sense for undead to raise in a turn or elemental/fiends from other planes to be summoned, but doesn't make so much sense for Wolves to appear out of nowhere.
But I'm not going to focus on that right now.

**Comment by Marcloure** [comment]
> Call Beast having a possibility of being killed doesn't make it weaker - if the creature is killed then it has eaten a lot of damage which helps mitigate damage to others.

If enemies attack it, then they probably don't have any other higher priority target within range. In the case of psychic crush, they can't even attack it and would just have to accept the spell there.

> They can and should be attacked [by] basic enemies

I am not really a fan of this line of thought. If some behaviour is expected, then it should have a mechanical meaning. Sure, there is opportunity attack, but like, 1d8+3 with mediocre to hit bonus is almost ignorable at 9th+ level (3 mana)

> but there is no way that I'm going to rebalance companions and all summoning spells to handle utility

I am not asking you to, but it is really weird to lose 3 actions (40+ damage?) to summon a creature mid combat. I think summons be at 1 minute to cast is better if that means they can be slightly more impactful (right now they don't feel nowhere near as important as force sword, which can deal 30+ guaranteed damage per turn at 3 mana)

**Comment by Marcloure** [comment]
Lastly, I know you plan to redo companions with scalable monsters, so things are bound to be changed when that happens. I'm not really concerned about this spell right now, you don't need to give that much thought to it right now

**Comment by mlenser** [comment]
> If enemies attack it, then they probably don't have any other higher priority target within range.

As I wrote abote:

>If they aren't, then the GM should. If enemies are smart then they can CC summons or go for the caster, but not basic enemies.

It sounds like you are either using smart enemies or having basic enemies act smart.

The tanky factor has been there forever and isn't going away. If you're having basic enemies act smart then I'd recommend changing how you play.

______________________________

> I am not really a fan of this line of thought. If some behaviour is expected, then it should have a mechanical meaning.

That is not how 5e is designed nor is my system. Call Beast shouldn't specify that creatures have to attack it... 😕

**Comment by Marcloure** [comment]
What is a basic enemy? Sure, a wolf, ogre or undead may attack the nearest thing, but does a group of bandits or guards know how to fight best in a world where magic exists? What about an orc camp that has known war since ever, or a drow raiding party? A hellish squadron of bearded devils? What about the PCs that always play the optimal play?

My point here is: if being attack is an important part of the power of companions, they should, somehow and at least a bit, incentivase creatures to attack it.

None of this matters for now though, my concern with this post is only the initial 3 actions required for you to deal your first 15 damage with the spell.

**Comment by mlenser** [comment]
> does a group of bandits or guards know how to fight best in a world where magic exists?

Entirely depends on their knowledge of magic. If you give them skills in magical skills then ya. If not, then probably not.


> My point here is: if being attack is an important part of the power of companions, they should, somehow and at least a bit, incentivase creatures to attack it.

**Comment by mlenser** [comment]
> does a group of bandits or guards know how to fight best in a world where magic exists?

Entirely depends on their knowledge of magic. If you give them skills in magical skills then ya. If not, then probably not.


> My point here is: if being attack is an important part of the power of companions, they should, somehow and at least a bit, incentivase creatures to attack it.

There is no incentive to attack a RAW Fighter. A beast is like that.


> None of this matters for now though, my concern with this post is only the initial 3 actions required for you to deal your first 15 damage with the spell.

I understand your concern, but changing it to 2 actions would unbalance the spells, which is what I'm been trying to convey since the start. If you want to work with it as is, but change it so the beast can be used right away then I'd recommend using 2 mana for a 1 resource companion.

**Comment by Marcloure** [comment]
I won't discuss further about targeting the companion, that is a meaningless discussion for now and is not my point. However:

> changing it to 2 actions would unbalance the spell

Why? Doesn't the spreadsheet consider it takes two actions? What makes it worth 3 actions? I understand the spreadsheet doesn't take utility into account, but I don't see how flight or swim is worth that much more (1 action and 1 turn) when other spells deal much more damage and also fly (though usually only 30 ft.).

Imagine how horrible it would be to summon a beast only for it to take an AOE spell or breath, and have it die before it can even act once.

**Comment by itamarcu** [comment]
> (tanking)

Summoning spells are also used by enemy spellcasters, and we can expect the party to make smart tactical decisions and attack the shaman instead of the bear.  The spells need to be balanced for usage by both PCs and NPCs.  So, this should be treated the same way as the health of an Earthen Grasp, for example.

This problem also makes some enemy monsters less threatening - for example, the enemy archdruid casting [Animate Plants](https://www.kryxrpg.com/spells/animate-plants) will sure look very impressive, but those plants will be harmless for an entire round.  

I generally agree with the original point: as a player, it sucks when you spend your entire turn summoning a creature and don't get to use it until the next turn (when it might not survive, or you might lose your concentration, or it might become irrelevant).

Also, given that all of these summoned creatures will *keep acting according to your latest command* after given a command, it clearly implies that they don't need your active effort to control them.  But, if they don't, it's very weird that the game forces you to wait 6 seconds and spend half of your next turn just to tell your wolf "Get 'em!".  I could understand it if some summons have to "roll initiative" and get their bearings, but they shouldn't need to wait for the summoner just to know what to do.

I think the solution has to be that as part of the two actions needed to summon the creatures, you give them a command, which they will either immediately follow or follow on their turns / your next turns.

I'm okay with rebalancing all companions and summon spells, if needed, but...

> Changing it to 2 actions would unbalance the spells.
> The action cost is part of its balance. Removing that means I need to nerf it elsewhere.

How can the action cost be part of the balance, if the summon remains for an entire hour? It doesn't even require your action to command it every turn (see:  "Once given an order, the creature continues to follow it until its task is complete").  So, it seems to me that for at least *many* of the summoned companions, the obvious usage is to summon them at the start of a day or before a combat, and have them ready at the start.  The fact that they are expected to be useful for utility out of combat makes it even more obvious.

So, if they are balanced around being available at the beginning of combat (for a 0 action cost, potentially with 1 action spent on commanding them) - I would expect the balance to remain the same when they are summoned during the first turn of combat (for a 2 action cost), if not even requiring a buff.

**Comment by mlenser** [comment]
I'm not going to rebalance spells currently for the following reasons:

- I find summons grossly unamanagable in most cases and largely never use them for PCs or NPCs.
- I don't desire to currently rebalance all summons
- Companions might go away so rebalancing them in the mean time would not be worthwhile.


I've written the current work-around if you desire summons to be available on turn 1. That's your option
> If you want to work with it as is, but change it so the beast can be used right away then I'd recommend using 2 mana for a 1 resource companion.

**Comment by mlenser** [comment]
Summoned creatures can now be commanded on the turn they are summoned.
