### ISSUE TITLE
Buff Blizzard spell

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#760]
I believe Blizzard is underwhelming as a 5 mana spell. If you cast Cold Fog at 5 mana, you can apply slow 4 and deal 1d6 damage in an usually large enough area. While Blizzard is indeed much larger and has a longer range, it applies only slow 2 and deals 2d6 damage per turn.

Sure, you can decimate a town using Blizzard better than with Cold Fog, but I think Blizzard could also be a bit better in combat encounters. It could either gain a bit of damage or slow more.

**Comment by mlenser** [comment]
Blizzard is massive. It is a huge blizzard over a huge area. 100 meter radius vs a 5 meter radius is a massive difference. Yes, for most combats 5 meters is sufficient, but that's not the purpose of Blizzard. Blizzard blankets a whole city.

I wouldn't be opposed to Blizzard having two options like Meteor Swarm, but the current version is not comparable to Cold Fog.

If you want to make a more direct version of blizzard that can be one of the options for the spell instead of the city-blanket then feel free to reopen the issue with a suggestion for what wording that would use.

**Comment by Marcloure** [comment]
> Blizzard blankets a whole city.

Unless it's a small village, a 200 meters diameter won't cover much of a city. Sure, it'll still kill commoners and guards that can't find shelter, but that is such a niche use. Maybe Blizzard should go around corners, so you can cast it outside a fort or castle to affect its residents?

**Comment by mlenser** [comment]
> Unless it's a small village, a 200 meters diameter won't cover much of a city.

Most medieval cities were less than 1 square mile according to google. The diameter of a 300 foot radius sphere (using imperial here due to square mile) is about 11% of a mile, so you're right less than a city. But probably enough to cover a castle.

I'd be fine with increasing that size.

> Maybe Blizzard should go around corners

Feels like that would be too strong. Blizzards should be possible to hide from.

**Comment by Marcloure** [comment]
> I'd be fine with increasing that size.

Increasing the size is indeed an option, although I don't know how much size would be good.

**Comment by mlenser** [comment]
Blizzard radius increased to 200 meters and its duration increased to 5 minutes/mana or psi.

Let me know if you think anything else should be adjusted.

**Comment by Marcloure** [comment]
There is this little thing I posted on Discord:
> Blizzard is listed on the spreadsheet as a Reflex save spell, when it's actually a Fortitude spell

**Comment by mlenser** [comment]
> There is this little thing I posted on Discord

Already solved on the spreadsheet.
