### ISSUE TITLE
Animal Messenger duration/mana is redundant

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#779]
The spell has a duration of 6 hours/mana, but its only augment is to increasing the duration by 48 hours. This means the spell's duration actually increases 54 hours per mana.

It should just state the augment as the normal duration / mana.

**Comment by mlenser** [comment]
Currently:
- 1 mana: 6 hours
- 2 mana: 54 hours

There is no way to state that as a normal duration.

**Comment by Marcloure** [comment]
But why like that though? Why not have it last 48 hours per mana? At 2 mana, Whispering Winds and Sending cover the entire plane and travels instantaneously. Sure, Animal Messenger would cover more distance in a day at 1 mana, but it isn't instantaneous nor it allows a response.

**Comment by mlenser** [comment]
Why are the spells different? Because they are different in RAW
![image](https://user-images.githubusercontent.com/235857/115102030-cd8d8e00-9f48-11eb-9efd-3c838e1ee77e.png)
![image](https://user-images.githubusercontent.com/235857/115102033-d67e5f80-9f48-11eb-96c4-80c6a047f2f2.png)
![image](https://user-images.githubusercontent.com/235857/115102041-e138f480-9f48-11eb-8607-f3b1b968fa9e.png)

You'll also find the slightly weird augment for Animal Messenger in the RAW version.

**Comment by Marcloure** [comment]
I'm not asking why they are different. I was just saying that having Animal Messenger last for 48 hours at 1 mana shouldn't be an issue. Sending and Whispering Winds were just examples to say that this wouldn't be "broken"

**Comment by mlenser** [comment]
48 hours isn't a standard option. I can change it to 1 day/mana or psi

**Comment by Marcloure** [comment]
Sure, I'm fine with that too. It could also have an augment to increase the word count, so you can send longer messages.

**Comment by mlenser** [comment]
Animal Messenger duration changed to 1 day/mana or psi.
