### ISSUE TITLE
Increase Alchemical Weapon usage and options

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#785]
This Alchemist's feature gives them a free 1/2/3 catalysts concoction per short rest at levels 5/13/17. Not quite true, actually, since it only applies to 1 shot per round, so it's more like 0.5/1/1.5 catalyst per short rest.

Considering that the Alchemist doesn't have cantrips and that they are worse at creating concoctions in combat, I think the limitation of 1/short rest could either be removed or increased to 2/short rest (similar in usage to Channel Divinity).

Also, why those 3 options specifically? Why not any oil they know? Currently, they don't need to know those options to use them with this feature in the first place.

**Comment by mlenser** [comment]
Alchemical Weapon reworked and moved to 17th level as the Alchemist now has multiple attacks at 5th level with its crossbow. This damage is slightly better than cantrips until 17th level where this feature makes up the gap.

**Comment by Marcloure** [comment]
Isn't it intentional that the Alchemist deals more damage than full casters 0-cost rounds? Alchemists are really bad at adapting to the situation, so they rely much more on at will attacks than full casters do.

**Comment by mlenser** [comment]
They do:
![chart (5)](https://user-images.githubusercontent.com/235857/115972315-e6e89880-a54d-11eb-9e64-e0342bef08ae.png)

They do more DPR on an adventuring day than most martials. They're totally fine.

**Comment by Marcloure** [comment]
Have you considered that a Wizard or Acolyte can also, technically, use a crossbow (not a heavy one, but that is 1 fewer damage)?

**Comment by mlenser** [comment]
Yes, other casters can also use weapons.

Alchemy isn't subpar to spells. It's just different. There are many tradeoffs both ways. Alchemy can allow for far more versatility compared to a normal caster, can pass around buffs 1 tier earlier in many cases, can spread out the action economy by passing out potions before combat, can bomb small AoEs much better than spells, etc.

I would say Wizards and Priests shouldn't be using crossbows, but that's due to thematics, not balance.
