### ISSUE TITLE
Player feedback on gishes and weapon-wielding casters

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#809]
So, one of my players has been bugging me with a issue for quite a while now, and while I don't really agree with him, I'll still relay it here.

**He's asking:** what is the point of gishes when an armed full casters can do the same? (At least at higher levels)

**The context:** He plays a 13th level full-mana paladin and has the expected stats distribution. He's also considering a full caster who wields weapon, not a cantrip-slinger.

**His point:** A full caster with armor spell has 17 Defense while other gishes have 17, 18, or 20 (monks). This takes 2 mana from the full caster for 6 hours of armor. Let's also take some 4 more mana dedicated blur and shielding spells. Priests naturally have 20 Defense, so they can ignore this (relates to issue #807).

At 13th level, full casters can buff their weapons to deal an extra 5d6 damage. A gish at that level can deal 2d6 extra damage with the same spell. Our estimates:

- Adding the full caster's damage, it would be 1d12+5+5d6 = 29 * 2
- The gishes's damage: 1d12+5+2d6+2d6 (or 2d4 for the Paladin) = 25.5 + fighting style, which adds to ~29 * 2
- Considering the hit chance, the full caster has ~30 DPR, and the gish has ~38. Without the weapon buff, these numbers drop to ~12 and ~24

So far, the full caster used 12 mana from 20, and the gish 2 from 10.

There is also the matter of HP. The Paladin would have 26 more hp (but only deals 2d4 above). Other gishes have 13 more hp. 13 hp doesn't seem a lot.

Considering everything, full casters have 13 less hp, equal Defense (because of blur and shielding), and deal 8 to 12 lower weapon DPR. Both have the same 8 mana with expenses, but full casters will regain more mana on short rests. However, full casters can reach higher bursts, and they have access to much better and cooler spells at 3, 4 and 5 mana, some of these which completely shift the game (Major Regen, Resurrection, and Foresight, for instance). Full casters also make better use of many class features, like Volatile Power and Channel Divinity.

**Conclusion:** I suppose his insatisfaction is that these 8 to 12 lower weapon DPR (which is actually 30-50% less damage) doesn't make up for the burst and, more importantly, the delayed spell progression (and blocked 4 and 5 mana spells). Although this would break symmetry, his suggestion is to allow gishes to have access to 4 mana spells at 17th level, since having 2 mana until the 16th level is quite limiting and slow.

He didn't take pure martials into account, but our Stamina users can indeed deal some 35 damage with one action using 4 Stamina.

**Comment by Marcloure** [comment]
**My Take:** I don't agree with his point. Those 8 to 12 fewer damage per turn is quite substantial, and I believe that if the player wants to have better spells but still use weapons, they can do it following the path of weapon-enchating. They won't have a cool shining armor, but it seems like you can have a pretty reliable Sorcerer Archer doing that. Gishes only complement their kit with spells, their main stick is to hit with a weapon.

However, I do agree that gaining access to 3 mana spells only at 17th level feels a bit late. Not sure if something can be changed without breaking linearity, but going 8 levels in the same spell tier seems a bit slow. After you reach the 9th level, it's a lifetime before you can reach the last tier. For mana-only characters, you are basically stuck in progression after that (in terms of gaining new tools).

**Comment by mlenser** [comment]
> He's asking: what is the point of gishes when an armed full casters can do the same? (At least at higher levels)

Casters have been purposefully prevented from accessing many martial capabilities. Casters lack armor proficiencies (Defense), have less health, and lack the ability to be proficient in weapon.

Health and weapons aren't "fixable". A caster will never have as much health or deal as much damage with a weapon as a martial or gish does.
Additionally, spells are much less usable with weapons than maneuvers are, but this can kind of be avoided with some spell choices which combine with attacks or feat like metamagic which allows spells to be imbued.

> A full caster with armor spell has 17 Defense while other gishes have 17, 18, or 20 (monks).

Martials will pretty much always have better Defense with their armor proficiencies and maneuver options. Armor could be worked around with a feat or some spells, but spells are much more costly than maneuvers which can boost Defense on the fly. Also see https://github.com/mlenser/kryx-rpg-issues/issues/807#issuecomment-849736247.

> At 13th level, full casters can buff their weapons to deal an extra 5d6 damage. A gish at that level can deal 2d6 extra damage with the same spell. Our estimates:
> 
> Adding the full caster's damage, it would be 1d12+5+5d6 = 29 * 2
> The gishes's damage: 1d12+5+2d6+2d6 (or 2d4 for the Paladin) = 25.5 + fighting style, which adds to ~29 * 2
> Considering the hit chance, the full caster has ~30 DPR, and the gish has ~38. Without the weapon buff, these numbers drop to ~12 and ~24

Napkin math is not super helpful tbh. +to hit would be 1-3 lower for casters as they can never become proficient with a weapon. I could do a full comparison using actual DPR, but I'm quite certain that a caster would do significantly less than a martial gives lower chance to hit, less powerful weapons, and no class features to boost weapon damage. Sure they have more mana, but I don't think that'd close the gap nearly enough. +to hit is the biggest issue. In 1d20 which you guys use, a caster would hit ~70% as often as a martial/gish at 5th tier or ~80% as often at 3rd tier where you guys are. That's a huge problem.

I believe a full caster with a weapon would deal less damage than a full caster using cantrips.



> I do agree that gaining access to 3 mana spells only at 17th level feels a bit late

This "problem" is significantly less in my system than RAW. In RAW gishes get acces to 5th level spells at 17th level like gishes in my system do, but my system has moved a significant number of spells to be available at earlier tiers.

Gishes cannot gain access to higher mana spells, else maneuvers would be a subpar option.

> going 8 levels in the same spell tier seems a bit slow

My system has moved a significant number of spells to be available at earlier tiers. They're in the same tier longer, but this issue is a perception issue, not a balance issue.

> For mana-only characters, you are basically stuck in progression after the 10th level (in terms of gaining new tools).

A mana only paladin doubles its mana from level 10 to level 20. It goes from 7 mana to 15. That's a huge increase in resources. They also learn several new spells to expand their current options. I don't think this statement is accurate.

**Comment by Marcloure** [comment]
> Casters lack armor proficiencies (Defense)

He is comming from the perspective of a Paladin, which has the Priest as its full caster counterpart. The Priest can have Defense equal one lower up to above the Paladin without expending mana (depending on their Dex).

> +to hit would be 1-3 lower for casters as they can never become proficient with a weapon. They [use] less powerful weapons

I did consider that full casters have less hit chance due to lack of proficiency, but they wield a d12 weapon with capability. Not less powerful, just less likely to hit

Just to be clear, I'm not defending his view, just clarifying the argument.

---

> In 1d20, which you guys use, a caster would hit ~70% as often as a martial/gish at 5th tier or ~80% as often at 3rd tier where you guys are. That's a huge problem.

I may swap to 2d10 if some of these issues are derived from using 1d20. The sheet on Roll20 doesn't work quite nice with 2d10, but I guess I'll give it a try.

**Comment by mlenser** [comment]
> He is comming from the perspective of a Paladin, which has the Priest as its full caster counterpart. The Priest can have Defense equal one lower up to above the Paladin without expending mana (depending on their Dex).

Which is a bit of a flawed perspective. See https://github.com/mlenser/kryx-rpg-issues/issues/807#issuecomment-849736247

If a Priest is investing their abilities into Dex then they'll have pitiful health for a front-line character as their health is already lower than gishes/martials.

> I did consider that full casters have less hit chance due to lack of proficiency, but they wield a d12 weapon with capability.

No they don't. All d12 weapons require martial. See the text on the same page:

> Martial weapons, including swords, warhammers, longspears, various polearms, and other weapons, require more specialized training to use effectively. **Without such training, a character cannot apply their proficiency bonus to a martial weapon, even if they are capable or proficient with weapons from that group.**

> Just to be clear, I'm not defending his view, just clarifying the argument.

Understood.

**Comment by Marcloure** [comment]
> Without such training, a character cannot apply their proficiency bonus to a martial weapon, even if they are capable or proficient with weapons from that group.

Hm, that makes sense. I think the rules for using weapons are spread over many pages, so it's hard to know all. You need to read the class, then go to the skill, then to making attack rolls on rules for Combat, and then look the weapon's section.

**Comment by mlenser** [comment]
> Hm, that makes sense. I think the rules for using weapons are spread over so many pages, it's hard to know all. You need to read the class, then go to the skill, then to making attack rolls on rules for Combat, and then look the weapon's section.

Weapon groups shouldn't be defined on the Weapons skill, but if there is a way that this can meaningfully be improved please do open a new issue for it.

**Comment by mlenser** [comment]
Based on the discussion and some small patches to 4 mana spells and feats so only those with weapon training are using them I don't think there is any serious concern here that casters are better than martials for weapon-based combat. Casters have benefits in that they can cast more spells and bigger spells, but they have severe problems with health and DPR from weapons.

Based on that I don't think there is a concern here.
