### ISSUE TITLE
Update Areas of Effect text on the rules page

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#813]
On this page: https://www.kryxrpg.com/rules/concoctions-maneuvers-and-spells

![image](https://user-images.githubusercontent.com/29084710/120057056-a5e51780-c016-11eb-8128-d2910a877339.png)

A wall is defined in the text as "each panel, unless otherwise specified, is up to 3 meters long, 2 meters high, and 30 centimeters thick." The table contains different values, however.

This difference also happens for cones, lines, cylinders, and cubes (which I think were removed).

**Comment by mlenser** [comment]
I've removed them from the page so the table will be the main source of truth.

**Comment by itamarcu** [comment]
The new paragraph says:

> Every 5 meters of a wall is a panel.

This replaces the previous value of 3m for each panel, while the original Wall of Stone spell is made of 10 ft panels, i.e. 2m.

This matters because Wall of Stone (and Wall of Bones, Flesh, Ice, etc) use specific panels in two ways:

1. Panels are damaged and destroyed individually;  with bigger panels, enough damage to the wall in a single point will collapse an entire 5 meter section (which I believe is very large)
2. Panels probably need to be flat(ish), so if you want a zig-zagging wall or some other complex shape you have to work with increments of 5m (compared to the RAW value of ~2m).

I think it would be better if panels were 2m per panel, or even 1m per panel.

**Comment by mlenser** [comment]
The original Wall of Stone is 5th level (3 mana equivalent) and 100 feet long. Walls are not that long in my system. My system still preserves 1 space = 1 panel. You could make the argument that walls should maybe be longer, but that's not this issue.

> Panels probably need to be flat(ish), so if you want a zig-zagging wall or some other complex shape you have to work with increments of 5m (compared to the RAW value of ~2m).

Walls have two ways to be made:

> A wall extends from its point of origin in a straight path up to its length and covers an area defined by its width and height. Every 5 meters of a wall is a panel.
> 
> Alternatively, a wall can be shaped as a ringed wall with a diameter half the distance of its length.

Zig zagging only works when more mana is used.

**Comment by mlenser** [comment]
Errr, I see now. Mixed 5 feet and meters. I'll change it to be 1 space = 1 panel. So a 5 meter wall would have 5 panels.
