### ISSUE TITLE
Quivering Palm scales more than to other maneuvers

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#845]
Quivering Palm deals 1d8+1d8 after failed save per Stamina dice. This means at 2 stamina, it deals 2d8+2d8, at 3 stamina 3d8+3d8, so on.

Although that seems fine at first sight, it scales much better than the majority of other maneuvers:
- Feint is 1d8 + Advantage on your next attack. Expending more stamina to increase its damage increases it by 1d8 per stamina.
- That is also true for the scaling damage option of Disorient, Distract, Feigned Opening, Trip, Spring Attack, and many more.

At 4 stamina, Quivering Palm deals 4d8 + 4d8 (after failed save) while other maneuvers deal 4d8 + rider (after failed save), but this rider is usually the same as the base maneuver. This means that instead of using Spring Attack (or any other maneuver) at 4 Stamina, it is much more efficient to use Spring Attack at 1 stamina and Quivering Palm at 3 stamina.

While I think removing the damage scaling from Quivering Palm would be ridiculous, it could scale a bit slower. The secondary damage could increase every 2 stamina or something like that. Pure damage will always be a priority, so I don't think it should also scale so efficiently.

**Comment by mlenser** [comment]
It does so because it is an attack and a saving throw
![image](https://user-images.githubusercontent.com/235857/121899012-4b410080-cd24-11eb-891e-ad29d82b5edf.png)

> This means that instead of using Spring Attack (or any other maneuver) at 4 Stamina, it is much more efficient to use Spring Attack at 1 stamina and Quivering Palm at 3 stamina.

Quiverring palm has ~32% chance to go off. Other maneuvers have ~61%.

**Comment by mlenser** [comment]
The sheet has calculated the damage value for each maneuver. If there is an error, feel free to point it out.

- Quiverring Palm is the normal damage + 1d8x0.32 more damage
- Other maneuvers are the normal damage + 0.32*negative effect

That is fine as far as I can see.

**Comment by Marcloure** [comment]
The issue is that it's actually:

- Quiverring Palm is the normal damage + Stamina * 1d8 * 0.32 more damage
- Other maneuvers are the normal damage + 0.32*negative effect

Quiverring Palm scales its damage twice per stamina dice, while other maneuvers either scale the damage or the effect once per stamina dice.

**Comment by mlenser** [comment]
Conditions are not static, their value increases with the mana/psi usage.

See the spreadsheet - condition multiplier.

Quivering Palm is 100% how it should be.

**Comment by Marcloure** [comment]
> Conditions are not static, their value increases with the mana/psi usage.

They only increase if you don't increase the damage though. So it's either 1d8+stunned or 5d8+remove reaction.

I see the maneuver is balanced on the spreadsheet, I just don't understand how. Scaling damage on any other maneuver is much less efficient than scaling damage on Quivering Palm.

**Comment by mlenser** [comment]
Please look at the spreadsheet. Condition multiplier.

**Comment by itamarcu** [comment]
@Marcloure - another way of looking at it is that the relative value of conditions (like blinded, disoriented, etc) is always the same, while the relative value of the damage decreases.  When you spend 1 stamina on Feint, you get 1d8 damage and advantage on your next attack.  At low levels the damage is great, but at high levels the damage is only a small percentage of the enemy health, and it's the advantage that is most useful.  Therefore the damage needs to scale to remain relevant.

Maneuvers like Quivering Palm (or [Tear Flesh](https://www.kryxrpg.com/maneuvers/tear-flesh)) are purely damage based.  This means that the damage needs to scale even more, to keep the entire maneuver competitive with others.

Don't think of it as "stamina dice are more useful when spent on Quivering Palm" - think of it as "the first stamina die spent on Feint is super useful, so the additional dice after it don't need to be as useful".

---

Though, this does raise a potential problem, for late game:  I think it may incentivize people with e.g. a stamina limit of 5 to spend 1 on a "condition" maneuver (like Spring Attack) and then 4 on a "pure damage" maneuver (like Quivering Palm).

If the player planned on using both of these maneuvers anyways, then this player is committing to spending 1 stamina on each of them.  The next 3 stamina dice are then better spent on Quivering Palm than on Spring Attack.  This is because the dice will increase the damage of whichever attack you add them to, but with QP they also increase the damage behind the save.

This is not a huge problem because it only affects higher level characters that choose two maneuvers with different scaling formulas.  And because it's not really affecting any thematics.

@mlenser - is this acceptable?

**Comment by Marcloure** [comment]
> I think it may incentivize people with e.g. a stamina limit of 5 to spend 1 on a "condition" maneuver (like Spring Attack) and then 4 on a "pure damage" maneuver (like Quivering Palm).

This is a problem at any level after you get to 2 limit. It's better to use spring attack at 1 stamina and then another maneuver at 1 stamina than to use spring attack at 2 stamina. The only reason to scale the damage of maneuvers like spring attack, instead of using 2 maneuvers, is if you have advantage on your next attack roll.

**Comment by mlenser** [comment]
> @mlenser - is this acceptable?

It's super minor.

Conditions are more impactful against stronger creatures. This is very difficult to model. I attempt to do so with the condition multiplier which makes conditions more valuable the higher tier they are used. This is based on the assumption that you wouldn't waste a 3 mana condition with damage on a small creature. There is a gap in the math where you can use a 1 mana condition on an important creature for less "damage value". It was a suuuuuper minor issue with 1 action that is a bigger problem with 2 actions. However I think it's a very edge case issue that I have no better way to model.

![image](https://user-images.githubusercontent.com/235857/121933284-252c5800-cd46-11eb-9fb8-b2ef3edf07c4.png)

**Comment by Marcloure** [comment]
It is minor, but as I was running a dragon a while ago, I noticed that it's much better to use dive attack, trip, and then 2 other maneuvers than to use dive attack with 4 Stamina. It's a bit counter intuitive, but also, I'm not sure it's huge problem

**Comment by mlenser** [comment]
Dive Attack scales slightly worse than the guideline.
![image](https://user-images.githubusercontent.com/235857/121936735-3aa38100-cd4a-11eb-9c8c-d126560ea48c.png)

It won't make a huge impact. It's more thematic for a dragon to mix up maneuvers. If they don't, then it's ok too.
