### ISSUE TITLE
Add Directory to Skills Page

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#849]
**Is your feature request related to a problem? Please describe.**
While the Skills are sorted in a way that's very logical for the system, they're not necessarily easy to reference. This is doubly so for learning new changes to existing skills. It's currently difficult to see the bigger picture of which skills are in which categories (or which skills currently exist) until you scroll down to them in the page.

**Describe the solution you'd like**
Preferably, a list of skills somewhere above the full list, organized in the same way (so it's easy to grok the categorization), with links to each for quick scrolling.

**Describe alternatives you've considered**
A simple list of each skill without links or any additional detail would be fine; the skills can then be Ctrl+F'd from there. It doesn't matter where precisely on the Skills page they're listed, as long as they're above the full skill descriptions. They would preferably still be organized in the same way as the page, and all together at the top, as opposed to a list above each group.

**Comment by mlenser** [comment]
Themes don't list all of their feats/concoctions/spells at the top. They provide a short summary, but people have said how those are never read and can largely be removed.

I'm not sure how this is different. If the page is too long to understand, then that should be changed. Adding more content at the top just makes it longer.

**Comment by itamarcu** [comment]
When someone is learning a new spell in a theme, they can often scroll down a little bit and see all spells with the mana cost they're allowed to learn (e.g. 1 mana if that's your mana limit or if it's a new theme for you).  Sometimes you'll need to scroll a little bit up and down, but you can still see an average of about 6 options, so it's easy to quickly note them and decide what works best for you.

But if you're learning a skill, you need to decide between 26 complex options, and each of them takes up about half a webpage.  For me, at least, it's easier to see an index of all skills with links at the start, and then middle-click the 3 of them that interest me for that particular character to open in new tabs and skim through to see what they can do.

Also, I think the nice categorization system we got going on for skills can allow making a better index at the top.  Instead of one big list of 26 skills, it can be:

Combat - Brawn, Weapons

General - 11 skills, can possibly be split further or have things move around (e.g. Streetwise to Social, Medicine+Wilderness+Lore to a new Knowledge, Engineering and Alchemy to Magic/Knowledge)

Magic - the 5 spellcasting skills

Social - the 5 social skills

**Comment by mlenser** [comment]
If we feel that pages could use some kind of table of contents like Wikipedia's format could work well.

![image](https://user-images.githubusercontent.com/235857/122167273-02e82680-ce7b-11eb-8382-7bf3d62feae4.png)

**Comment by itamarcu** [comment]
In addition to Wikipedia having a nice table of contents, it also has a nice hide/show / collapse/expand button - which should help avoid a page that is too long, especially if it defaults to being collapsed.

![image](https://user-images.githubusercontent.com/6516621/122173526-7ba2af00-ce8a-11eb-94b3-dda36afddd57.png)

**Comment by mlenser** [comment]
Table of contents for skills
![image](https://user-images.githubusercontent.com/235857/122217117-62f7c080-cead-11eb-8422-33081a58d72f.png)
