### ISSUE TITLE
Time Stop should be at 3 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#856]
https://www.kryxrpg.com/spells/time-stop

Time Stop is a 2 mana spell that gives you an extra turn. Thing is, it takes 2 actions, so you expend 2 actions to gain 2 actions. The spell barely has any benefit at base cost, aside from giving you an extra turn of movement.

So, I believe it should be pushed to 3 mana and give you 2 aditional turns? Or to 1 mana and you gain an actual additional turn at 2 mana. I am not sure how valuable is a turn which you can't affect others.

**Comment by mlenser** [comment]
> I am not sure how valuable is a turn which you can't affect others.

It is very valuable. You can cast things like regnerate, drink a healing potion, cast a utility spell, etc.

But the current version has issues. I'll adjust it.

**Comment by itamarcu** [comment]
Depending on GM interpretation, it can also have inherent value because from other creatures' viewpoint you disappear and reappear someplace else and suddenly a bunch of things are different around you.  So, for example, you could use a Time Stop to draw special equipment from your bag and place it next to allies, or pour a bag of marbles behind your enemy's feet, or collect an item that your enemy dropped without being subject to an opportunity attack.

So, I think it's already valuable in its current form, for clever plays - but isn't too strong (since you can't affect creatures).

By the way, I think perhaps the augment of:
> You can increase the number of turns by 1 for every two additional mana or psi expended.

Could be changed into:
> You can augment this spell with the following options, expending mana or psi for each option.
> - You can expend 1 additional mana to gain another action during your additional turn.
> - You can expend 2 additional mana or psi to increase the number of turns by 1

**Comment by mlenser** [comment]
Time Stop reworked.
