### ISSUE TITLE
Increase Gag cost

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#857]
https://www.kryxrpg.com/maneuvers/gag

Gag makes the target unable to speak, which means they become incapable of casting many spells. I believe its cost should be increased.

**Comment by itamarcu** [comment]
Could also make it 1 stamina to Gag for a single turn, and enhance by +1 to Gag for a duration (which is how it is now).

**Comment by Marcloure** [comment]
Making someone unable to cast spells for 1 turn is potentially a lot, considering that a full caster can't do much besides casting spells.

**Comment by itamarcu** [comment]
[Incapacitated](https://www.kryxrpg.com/rules/conditions/#incapacitated) is valued in the sheet as about 11, a combination of "can't move" (3.6), "can't use actions" (6.0), "no reactions" (1.5).  For full casters, being gagged is slightly better than the other two - they can still take generic actions like dodge/disengage/dash, control concentration spells, and so on.  They can't speak to allies (or enemies) but that's not too important in combat, and most things that incapacitate do that too.  

So, going by gut feeling, I think the value of being Gagged should be something around ~8. below Incapacitated (11) but above Staggered (6.5).  I think this fits 2 stamina (hard to check on the sheet because I'm not sure I'm doing it right).

**Comment by Marcloure** [comment]
There is also [command](https://www.kryxrpg.com/spells/command), which removes 1 turn from the target. Curiously, it's not considered a super OP spell in RAW, I guess because you use your entire turn to remove someone else's. Here it is quite stronger, since it costs you 1 action to remove all actions from the target (maybe it should remove only 1 aciton?)

**Comment by Marcloure** [comment]
Another thing to consider is that single target stunning spells cost 2 mana, so something that does less than it surely should cost less. Or should do more damage and be 2 actions.

**Comment by mlenser** [comment]
Gag changes to 2 stamina dice and only lasts until the end of the creature’s next turn.
