### ISSUE TITLE
Fear should cost 2 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#902]
https://www.kryxrpg.com/themes/fear

This spell is very powerful for its cost. It is an AOE controlling spell that causes creatures to lose their whole turn, provoke opportunity attacks, and move away from you (which means they need to lose additional turns to go back). Also, note that it may last for the whole duration if the creature can't find cover.

Compare that with command, for instance.

Another possible solution is to make it similar to Sleep: 1 target + 1 target per mana.

**Comment by FoxenSocks** [comment]
It comes from a third level 5e spell, soI'd vote just making it two mana, given it's a major, persistent condition.

**Comment by FoxenSocks** [comment]
On closer inspection, DnD Fifth Edition has two different spells "Cause Fear" and "Fear."

Cause Fear is a first level spell: single target out to 60 feet, and can hit another target for each level higher you cast it.  It frightens, but does not compel the dash, and the target does not have to evade line of sight to remake the saving throw.

Fear, which this text more closely resembles, is a third level spell that works almost exactly as this one does.

So, it seems we ended up with the third-level spell (accessible at character level 5) text for the first-level spell price.

**Comment by mlenser** [comment]
> causes creatures to lose their whole turn

It doesn't lose its whole turn. It must use the Dash action. So 1 action. It can have more than 1 action.

> provoke opportunity attacks

It doesn't force provoking opportunity attacks: "move away from you by the **_safest available route_**"

> it may last for the whole duration if the creature can't find cover.

This should be exceptionally rare seeing as it can be behind objects and other creatures.

> Compare that with command, for instance.

Command is not a spell that I would use as a baseline. It is an inhereted spell that I'm not too fond of.

_____________

> So, it seems we ended up with the third-level spell (accessible at character level 5) text for the first-level spell price.

Spells were adjusted all over the place. RAW 5e's power levels are not a baseline that can be compared.

**Comment by mlenser** [comment]
The sheet isn't perfect with condition only effects, but it is a lot better now than it was before. According to it, Fear being a cone is more accurate to the expected power level than a hypotehtical single target version. The force dash away is a big part of the power.
![image](https://user-images.githubusercontent.com/235857/127473167-24e7d621-fbcf-4328-ad39-8f8ee6aa73e2.png)

That said, if you think there is some mistake for fear or some valuation issue on frightened or force dash away or anything else let me know and we can see if we can make it more accurate.

**Comment by itamarcu** [comment]
> It doesn't force provoking opportunity attacks: "move away from you by the safest available route"

It does, because if the creature is standing right next to you and is under Fear, it has to move out of your reach so even the safest route is harmful.  (A creature with 1 action won't be able to Disengage)

https://www.reddit.com/r/DMAcademy/comments/b2k4di/opportunity_attack_from_fear_based_forced_movement/

https://twitter.com/jeremyecrawford/status/954772646108909568

I suggest changing the spell a bit with one of the following options:
- The creature has to use either Dash or Disengage (but it can choose which one)
- The creature has to move away from you but it doesn't require one of these actions

By the way, note that Fear isn't a saving throw at the end of every turn - it's only a saving throw at the end of turns where you don't see the caster.  That's stronger than the default, which is what the sheet assumes, I think.

**Comment by mlenser** [comment]
It only provokes an opportunity attack if you're next to someone on the initial round, sure.

> By the way, note that Fear isn't a saving throw at the end of every turn - it's only a saving throw at the end of turns where you don't see the caster.

See above. You can almost always avoid line of sight unless you're in a 1 v 1 in an open plain with no place to hide. It's 99.999% of the time.

___________

As I wrote above: Please use the sheet to suggest changes:
> That said, if you think there is some mistake for fear or some valuation issue on frightened or force dash away or anything else let me know and we can see if we can make it more accurate.

**Comment by FoxenSocks** [comment]
> Spells were adjusted all over the place. RAW 5e's power levels are not a baseline that can be compared.
Ah gotcha.  I think an edit to the spell conversion list reflecting that this is more like Fear than Cause Fear (or that it also covers Fear) would be good.  Currently, only Cause Fear is listed.

**Comment by mlenser** [comment]
Only Cause Fear is listed as I only list spells that were removed or had their name changed. If a person is looking for the Fear spell, then Fear is the right place to look.

**Comment by FoxenSocks** [comment]
> Only Cause Fear is listed as I only list spells that were removed or had their name changed. If a person is looking for the Fear spell, then Fear is the right place to look.

Ah, I didn't realize.  That makes sense.

**Comment by Paulorpribeiro** [comment]
I suspect the spell seems like it needs a tweak, but I don't have the data to support it, but I will give my 2 cents

I agree with itsmarcu's first point,  having the target either use dash or disengage and move away from the source of the fear. The target still loses one action. It would make more sense for a target  who is adjacent to death it self to carefully move away than to dash full speed away. It is afraid of the target, but won't risk taking a swing just to get away quicker.

**Comment by mlenser** [comment]
That's not how https://www.dndbeyond.com/spells/fear works.

As above, this system uses the sheet to balance or at least estimate the balance of options. That is the baseline by which decisions are made. If you remove force dash away from Fear it becomes significantly less powerful and according to the sheet, not valuable enough for 1 mana.

But, as above:
> That said, if you think there is some mistake for fear or some valuation issue on frightened or force dash away or anything else let me know and we can see if we can make it more accurate.

According to the sheet this spell is ok. If someone would like to follow the process that this system uses to balance spells then please do follow up as I would be curious about your perspective.

**Comment by itamarcu** [comment]
@mlenser - according to [the sheet](https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=1121938024), the value of "force dash away" is 5.45, set to be equal to "pushed 10m".  however, being forced to dash away is significantly stronger - it will not only make the enemy dash away (moving ~10m away, more for faster creatures) but also **takes away the creature's action** to do so, and **forces an opportunity attack** in certain situations.

The value of taking away one of the creature's actions should be half of "can't use actions" (15.00), since the same calculation is used in Staggered.  Therefore, the value of "force dash away" should increase by about 7.5 when taking the action part into account.

On the other hand, I think forcing a ~10m movement away from you (by the safest available route) is less powerful than pushing 10m, because you can't use it to move an enemy into dangerous territory.

For forcing an opportunity attack - there is no calculation for that in the sheet, and I believe this is meaningful enough to include.  Based on the existence of maneuvers like Backlash and Riposte, a normal character can make a reaction attack for free under certain conditions (enemy moving away, i.e. opportunity attack) but could make a reaction attack under other conditions by paying 2 stamina.  Assuming those are balanced, the value of forcing an opportunity attack should be roughly the same as giving 2 stamina to yourself or an ally - which would be a whole lot (but I don't know the number).  A gish could use Fear on an adjacent enemy and then opportunity-attack right afterwards for high value, in a lot of situations.

Overall, my gut feeling is that forcing a creature to use its action to dash away and to allow an opportunity attack would be closer to ~3 ("push") + 7.5 (lost action) + ~5 (the OA) = **~15** in total - still much higher than **5.45**.

My suggestion of allowing the creature to disengage instead of dashing (still forcing the use of an action, but in a slightly more thematic way) would reduce the value to something like 10 - as it still eats the enemy's action, still moves a creature away, but it's a shorter distance and no opportunity attack.  I think the thematics for doing it when afraid would make sense for the victims of the spell.

**Comment by mlenser** [comment]
> it will not only make the enemy dash away (moving ~10m away, more for faster creatures) but also takes away the creature's action to do so, and forces an opportunity attack in certain situations.

10m is the correct measurement to use as a general distance, though it'll vary by creature. 5m is the standard movement by which all spells and maneuvers are balanced.

But it doesn't taken into account the loss of an action or the opportunity attack. The opportunity attack is likely uncommon. Or at least uncommon for all creatures in the cone (maybe 1 out of the group would be up for an opportunity attack unless there is significant setup, which would be ok and not something to consider).

> On the other hand, I think forcing a ~10m movement away from you (by the safest available route) is less powerful than pushing 10m, because you can't use it to move an enemy into dangerous territory.

Pushing never taked dangerous areas into consideration.

Pushed 10 meters is only used by Tsunami and this spell. It is never really used for forcing into difficult terrain and not worth considering. It's effectively "you move 10 meters away, which makes you less likely to attack".

___________

I'd rather remove the opportunity attack possibility than calculate it.

**Comment by Marcloure** [comment]
Dissonant Whisper also provokes opportunity attacks, and that indeed isn't considered in the spell. It's a very common 5e tactics to gang up a creature, cast dissonant whisper on it, and proc 2 or 3 opportunity attacks against it plus the spell's damage.

**Comment by mlenser** [comment]
> It's a very common 5e tactics to gang up a creature, cast dissonant whisper on it, and proc 2 or 3 opportunity attacks against it plus the spell's damage.

This is far beyond what this spell should offer and should be changed. Working together should be encouraged, but when something is this powerful in a case like this then it should be balanced for that case and then it is quite bad when not using this exploitative case. #907 opened to address this.

**Comment by mlenser** [comment]
Dissonant Whispers immediately using a reaction is strange when Incite Panic and Fear don't do so. These mechanics should be synchronized, imo. I would say remove the reaction movement, but I'll have to look at a few more cases.

**Comment by itamarcu** [comment]
> These mechanics should be synchronized, imo

I think it's fine to keep both of them - Fear is a persistent frightened effect that makes the creature want to keep moving away, and Dissonant Whispers is a brief/momentary psychic effect that forces the creature to move against its better judgement.

**Comment by mlenser** [comment]
> I think it's fine to keep both of them - Fear is a persistent frightened effect that makes the creature want to keep moving away, and Dissonant Whispers is a brief/momentary psychic effect that forces the creature to move against its better judgement.

Moving this discussion to #907

**Comment by mlenser** [comment]
Fear changed to a single target spell that forces them to move, but does not force them to dash and it augments for two creatures per mana.

**Comment by mlenser** [comment]
Frightful Presence added as a spell to the Fear theme.
