### ISSUE TITLE
Twist Fate is a better option than all other similar spells

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#904]
https://www.kryxrpg.com/spells/twist-fate

Twist Fate allows you to affect _every_ possible d20 check from yourself, your allies, or your enemies. From attacks to skill checks to saving throw. Compare that to

https://www.kryxrpg.com/spells/mind-over-body
- Which only allows for checks and saves _you_ make related to physical stats.

https://www.kryxrpg.com/spells/thought-shield
- Which only affects _your_ Will saves (has a nice augment though)

https://www.kryxrpg.com/spells/ancestral-blessing 
and
https://www.kryxrpg.com/spells/conviction
- Which only target allies (can't subtract the d4).

Twist Fate is just better than any of these options. My issue with that is that if you have access to Fate, all these other spells (maybe with exception of Thought Shield) become pointless to learn.

Maybe it should only add/subtract the d4, with no option to do the other?

**Comment by mlenser** [comment]
Thematic differences can allow for more versatility.

[Regenerate](https://www.kryxrpg.com/spells/regenerate) for example is less versatile than [Heal](https://www.kryxrpg.com/spells/heal) as [Regenerate](https://www.kryxrpg.com/spells/regenerate) can only be used on yourself.

That difference in versatility is totally ok. The same is true in this case: Mind over body should only impact yourself and your physical ability checks and saving throws. Twist Fate thematically impacts much more as it can twist fate for you, your friend, or your enemy. It's more versatile, but the same actual benefit. This presents itself many times in my system and is ok.

**Comment by itamarcu** [comment]
While there's thematic differences that allow extra versatility, there is still the problem that Marcloure said - if your character has access to the Fate theme, you should never pick any of the other spells.

Regenerate isn't a strict downgrade to Heal, because you get to heal once this turn and once next turn - could be more useful in certain situations.  It's less versatile but there's a reason for a character to know both spells.

I think a good solution would be to add more unique augments or conditional effects to some of the other options, to give them a niche where they are useful (to account for the versatility).  Would work if they're thematic.

Example ideas:

- Ancestral Blessing - first of all, it should get the 2 mana and 4 mana augments (I think we'll all agree on that).  Additionally, I suggest making the spell not work on constructs and undead, and making the affected creature's space glow with dim/bright light until the start of the next turn, as the spirits are visibly appearing there.
- Thought Shield - already has a unique augment, so it's fine
- Mind Over Body - could have a similar augment to Thought Shield, that gives you the bonus consistently until the start of your next turn.

**Comment by mlenser** [comment]
> While there's thematic differences that allow extra versatility, there is still the problem that Marcloure said - if your character has access to the Fate theme, you should never pick any of the other spells.

That is true for all of the spells that are thematically better than others. Regenerate is slightly different, but in general there are several options like this that are thematically superior in versatility. The result here is the same as I've always said: That is ok.

If there is a desire to improve certain options, please open a new issue.

**Comment by mlenser** [comment]
FYI if you desire to adjust spells and maneuvers in this area there are 21 spells:
![image](https://user-images.githubusercontent.com/235857/127495437-a712b919-b3d0-47be-9793-d18e02e0036c.png)
and 10 maneuvers:
![image](https://user-images.githubusercontent.com/235857/127495511-dbcc4e46-3489-4cf5-8ed0-02ec0c916c33.png)

**Comment by mlenser** [comment]
> If you have access to Fate, you don't need more thematic options like Judge, Browbeat, Ancestral Blessing, etc.

That would have a cost for all characters who don't already have the Fate theme.

I'd be happy to add rules to prevent dipping a theme for a spell or two or more harsh limits on the number of themes or a higher cost to add themes.

_______________

Twist Fate, Bend Luck, and Second Chance thematically should apply to you, your allies, and your enemies. Other cases like Conviction should only apply to you and your allies while Hinder should only apply to your enemies.

I understand the point you raised the issue for, but as I wrote above thematic differences in versatility is ok. If you desire to make each option attractive on its own, feel free to open issues to adjust each one.
