### ISSUE TITLE
Low challenge creatures with stamina makes them stronger

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#906]
I looked specially at Kobolds that got 2 stamina dice (as per their hit dice, I assume) and got quite a bit stronger.

Their damage (1d4+2, so 4.5 average) got a 100% boost (avg of 1d8) if they hit. Of course it's twice per encounter, but hey, how long does a 5 hp kobold live in an encounter?

Now every kobold's first attack will deal twice their previous damage if they hit; and their second attack (if they hit and survive to deliver the attack). If you don't Aoe kill them all, the second round of attacks will certainly kill you.
I can't throw 8 kobolds against a party of 4 2nd lvl adventurers anymore, cause they average 9 dmg per hit and probably 2-3 shot a character, keep in mind they only engage with at least 1:2 numeric advantage.

The example only illustrates the issue I want to talk about. Stamina dice for low CR creatures is a bit problematic. It increases the average damage they deal by quite a bit. This is specially true for creatures that attack in large numbers, since each will have the stamina dice. And keep in mind that 2 dice is probably plenty for the average combat duration.

The solution might be to give only one stamina to creatures with  CR 1/4 or lower (doesn't solve the issue completely, but makes it better) or to not give low CR critters stamina at all (but that goes against design direction I guess)

Does anyone have other ideas? Am I overreacting? Anyone with real gametable experience with this, although the change is recent, at least regarding kobolds?

**Comment by Marcloure** [comment]
I don't have much to say, besides reminding that low level PCs have a 6–10 more Health here than in RAW 5e, since they add Health from species.

**Comment by mlenser** [comment]
This is the case for all creatures, not just Kobolds. Every creature has had stamina dice or mana except some humanoids and fiends for quite a while. It has not been a problem in my games.

_____

> I can't throw 8 kobolds against a party of 4 2nd lvl adventurers anymore, cause they average 9 dmg per hit and probably 2-3 shot a character, keep in mind they only engage with at least 1:2 numeric advantage.

## My system

2nd level characters with 1 Constitution would have ~23 health on average. 8 from species, 8 from level 1, 5 from level 2, and 2 from Con.

Kobolds deal ~4.5 damage per round, with the possibility of bursting for two rounds where they would deal ~9 damage. 2 attacks, **_if they hit_**, would deal ~18 damage. It would take ~1.5 more hits to down an average PC.

Result: It takes ~3.5 **hits** to down an average PC, assuming no misses. If there are misses with the stamina dice, it would take much longer.

## RAW

2nd level characters with 1 Constitution would have ~15 health on average. 8 from level 1, 5 from level 2, and 2 from Con.

Kobolds deal ~4.5 damage per round

Result: It takes ~3.3333 **hits** to down an average PC

## Conclusion

The numbers above assume hits. Creatures will hit ~55% of the time, so you can nearly divide the number of hits in half to determine how many rounds before they down a PC (would be more due to stamina dice)

Seems similar to RAW.

___________


Unrelated: I'll verify if challenge 1/8 creatures should have 1 or 2 stamina dice. Kobolds should also have some cowardly options like scurry.

**Comment by Paulorpribeiro** [comment]
I think downing it to 1 dice for 1/8 creatures is appropriate. If they don't kill in their nova round, then they are at the mercy of characters, or flee. I might have exaggerated with 2-3 hits to kill, but my whole point is 1/8 creatures have had a 100% boost to damage (twice per encounter) Just like that. We're they that much unbalanced before the last change?

**Comment by mlenser** [comment]
There are a few factors here:

- 1/8 creatures should maybe only have 1 stamina. I'll check.
- Kobolds, as cowardly type creatures, should have utility options like scurry so their stamina isn't only used on offensive options.
- The GM should play creatures in a way that suits the creature, the scenario, and the campaign's vibe. Creatures don't need maneuvers to TPK parties. 8 Kobolds for example could team up to prone a PC and then all attack it to very likely kill it. Tucker's Kobold strategies could be employed to beat PCs. Meaning that GMs should know that using all stamina dice on the first round to nova PCs is probably bad for low challenge monsters. You should likely use some and save some for either utility or damage on later rounds.

**Comment by mlenser** [comment]
Challenge 0 to ¼ now have 1 stamina die.

**Comment by mlenser** [comment]
Kobold and Kobold Dragonshield have maneuvers that help them move around instead of just damage maneuvers.
