### ISSUE TITLE
Fire spells should ignite the target in flames

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#94]
Similar to Immolation does.
Once I decide which way to go on #87 I can do this.

**Comment by mlenser** [comment]
One thing I didn't consider: If a creature is already on fire then another spell that lights them on fire doesn't serve much purpose...

**Comment by Marcloure** [comment]
So, either the character shouldn't spam fire spells on ignited creatures (which I don't think is the ideal design), or the ignite damage isn't so meaningful that it's still worth to cast it on burning targets.

**Comment by mlenser** [comment]
Exactly

**Comment by mlenser** [comment]
I'll leave this until after #87 and then explore it.

**Comment by mlenser** [comment]
The only way to make this work is to make a condition for burning which deals 1d6 for each condition level. We could allow the level to increase indefinitely. Fire spells could add to this condition and the more the condition rises the more the creature Burns and wants to spend an action to make it stop.

**Comment by DalenWBrauner** [comment]
I like that a lot. Spells like Immolation can serve to intentionally inflict several stacks of burning, and using multiple AoE fire spells suddenly has a very cool utility to it. I think this leans into Fire's flavor very well.

**Comment by itamarcu** [comment]
I like that too, a "Burning" condition.

Would it also have a mechanic of setting other things on fire, or would that be too much?

**Comment by Lamorak11** [comment]
I also like this condition concept.

**Comment by mlenser** [comment]
## Burning condition
![image](https://user-images.githubusercontent.com/235857/81493759-5ca71600-92a3-11ea-8307-f0a47b57c8c1.png)

## Immolation
![image](https://user-images.githubusercontent.com/235857/81493782-91b36880-92a3-11ea-9666-dba333937fc4.png)

## Scorching Ray
![image](https://user-images.githubusercontent.com/235857/81493787-9c6dfd80-92a3-11ea-84d3-fbb3dbcb4786.png)

## Fireball
![image](https://user-images.githubusercontent.com/235857/81493795-ae4fa080-92a3-11ea-9879-39975c0346bf.png)

**Comment by Marcloure** [comment]
Burning needs to specify that it stacks, like exhaustion does:

"If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect’s description."

Otherwise, causing two "the creature is burning 1" is still the creature burning 1.

**Comment by mlenser** [comment]
Fire spells now cause the burning condition: Burning Hands, Fiery Rebuke, Fireball, Immolation, Incendiary Cloud, Meteor Swarm, Minute Meteors, Molten Upheaval, Scorching Ray, Wall of Fire

**Comment by DalenWBrauner** [comment]
I'm a little concerned about the Scorching Ray changes. Presenting a spell attack that then also requires a save presents two issues:
1. Half of the damage is locked behind an additional roll (the new Fortitude save), giving its targets 2 chances to avoid the damage
2. Because of the nature of Scorching Ray, you're already making 2 attacks. Whether your DM allows you to make a single attack roll to use for both rays, or requires an attack roll for each, this doubles the amount of rolling required. I'm worried this will slow down gameplay.

Regarding 1., I understand the tradeoff is that Burning _can_ last for several rounds, so I don't believe it's unbalanced- this is more of a play preference. I'd be comfortable with it being the black sheep of the fire theme that does not ignite targets, simply scorching them.

Overall I like the Burning condition and how the Water them interacts with it. But I think it needs to be more specific about Save DCs. The main paragraph should say:

> Burning always includes a level and a DC. The DC is equal to the [highest/lowest] save DC (typically from a spell) needed to avoid the burning.

and the first bullet:

> must make a Reflex saving throw against the Burning DC

and the second bullet:
> must make a Medicine check against the Burning DC

Either that, or all Burning conditions should have a listed, flat DC to extinguish them, perhaps scaling based on how bad the burning is.

**Comment by DalenWBrauner** [comment]
Made some minor clarifying edits

**Comment by mlenser** [comment]
> Whether your DM allows you to make a single attack roll to use for both rays, or requires an attack roll for each

Your GM should 100% require a roll for each. Otherwise it is too swingy.

> giving its targets 2 chances to avoid the damage

Ya, I forgot to calculate this part.

> I think it needs to be more specific about Save DCs

Interesting. I hadn't considered multiple sources with different DCs...

> and the first bullet:
> and the second bullet:

The bullets are combined because there is a lot of wording that would be duplicated: "The DC is typically a spell save DC. On a success, the burning condition ends. On a failure of 4 or less, the burning level is reduced by 1."

**Comment by DalenWBrauner** [comment]
It looks like you removed the Fort Save for Scorching Bolt's Spell, but not Spell Strike. Was that intentional?

>The bullets are combined because there is a lot of wording that would be duplicated

Either I'm not understanding what you mean, or vice versa. Let me post how I think it should read (additions in bold):

> Burning always includes a level **and a DC. The DC is equal to the highest (lowest?) save DC needed to avoid the burning (typically from a spell).** If a burning creature suffers another effect that causes burning, its current level of burning increases by the amount specified in the effect’s description.
> - A burning creature sheds light......
> - At the start of each of its turns......
> - A burning creature can use its action to make a Reflex saving throw or a creature can touch the burning creature and make a Medicine check to extinguish the flames. ~~The DC is typically a spell save DC.~~ On a success, the burning condition ends. On a failure of 4 or less, the burning level is reduced by 1.
> - If oxygen is removed......

Really it just needs to specify what the DC actually _is_. As of now it's completely ambiguous, but I assume you'd like it to stay the caster's DC.

>I hadn't considered multiple sources with different DCs...

Or we could use a flat DC for all Burning conditions. Just because a high-level caster burned you to begin with doesn't mean the fire is still magical afterwards, right? Maybe except for Immolation? And again, a flat DC could scale with Burning level.

**Comment by mlenser** [comment]
> It looks like you removed the Fort Save for Scorching Bolt's Spell, but not Spell Strike. Was that intentional?

The strike can't be an auto-hit in order to avoid crit fishing, so Fort save.

**Comment by Marcloure** [comment]
I'm not sure if crit fishing on a spell that would deal 1d4 without a save is too much. It was when the spell dealt 3d10, but I don't think it is anymore

**Comment by mlenser** [comment]
Let me phrase it differently: without the fort the creature would automatically take damage and ignite. Auto damage is for the force theme, not here.

**Comment by Marcloure** [comment]
Yeah, ok. That makes sense hahaha

**Comment by mlenser** [comment]
Searing smite does exactly that though.. hmm
