### ISSUE TITLE
Should Legendary Resistance be removed from the game?

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#943]
Legendary Resistance is a bit of a controversial feature in 5e, but here, I think it is an unneeded one. My reasoning:

- LR exists to prevent save or suck spells from completely owning bosses. While some of these effects still exist here, they mostly either have a higher cost (so you can only cast them once per short rest), or a save at the end of the turn.
- Creatures, specially high CR ones, have much more balanced saving throws here. We don't have high CR creatures with a +0 or negative saves, unlike in 5e.
- There doesn't seem to be a pattern to which creatures have LR. The Planetar, a CR 16 angel, and the Storm Giant Quintessent, the most powerful giant at CR 16, don't have it, but a Vampire at CR 13 and every adult dragon have it.
- Many "controlling spells" are considered to be extra powerful because they can lock down the boss, but this logic doesn't hold up very well when they have legendary resistance. You are kinda forced to only use damaging spells against them since they can just nope any control they take.

If LR exists to hamfistedly make solo bosses more threatening... well, it doesn't either way. Solo creatures still get heavily stomped by the action economy. I think this is just a weird and arbitrary feature.

**Comment by mlenser** [comment]
> LR exists to prevent save or suck spells from completely owning bosses. While some of these effects still exist here, they mostly either have a higher cost (so you can only cast them once per short rest), or a save at the end of the turn.

This is no diffrerent from RAW. Almost all RAW save or suck spells have a high cost and a save at the end of each round.

Potentional scenario: A 4 PC party spams CC spells like Stasis on the Ancient Black Dragon until one lands. Even with good saves the dragon would be vulnerable to this strategy. With the action economy and chance of success, the PCs would be able to stun lock the dragon while killing it fairly easily.

> You are kinda forced to only use damaging spells against them since they can just nope any control they take.

PCs can also use lighter CC so the dragon doesn't use Legendary Resistance or burn their Legendary Resistance. There are 4+ PCs so even the strategy above would work with Legendary Resistance - it would just be delayed by 3 Legendary Resistance uses.

___________

I'm a fan of Legendary Resistance. Without it, I think these solo-type bosses are super vulnerable.

**Comment by Marcloure** [comment]
Another point: LR creates a bit of an unhealthy, metagamey game. The players try to bait LR resistances out of bosses, and the GM knows the players are trying to bait it so they hold it back until most needed. Everyone is kinda put at gun point.

> Potentional scenario: A 4 PC party spams CC spells like Stasis on the Ancient Black Dragon until one lands.

That can only happen if you are doing a 1v4 fight, which doesn't work with or without LR. If you have the dragon and some supporting creatures, the PCs are wasting 3 to 4 full turns to stun the dragon (which doesn't necessarily progresses the fight in their favor) and ignoring every other creature in the fight.

**Comment by mlenser** [comment]
Some threads:

<https://www.reddit.com/r/dndnext/comments/786zb9/whats_the_right_way_to_use_legendary_resistance>
> Legendary Resistances are there to make sure the Ancient Red Dragon doesn't die in a single round because it rolled crap initiative and then was told by the divination wizard that it rolled a "1" on its WIS save against Hold Monster.

This case in my system would be slightly different, but overall quite similar.

<https://www.reddit.com/r/dndnext/comments/jl0a2w/is_legendary_resistance_an_unfun_mechanic>
> They're there to prevent weighty encounters being negated by a single spell.

<https://www.reddit.com/r/dndnext/comments/k6rhvq/an_alternative_to_legendary_resistance>

Paragon is an interesting mechanic:
> I think Paragon monsters is probably the best way I've seen this handled (though you can still have legendary resistances in some form on those). Just shake off any status effects when one of the x number of health bars is depleted. The party still gets their CC/save spell, but the monster isn't completely fucked by it

__________________

I don't see Legendary Resistance being removed. Maybe slightly adjusted or replaced with something similar, but it serves a strong purpose.

**Comment by DalenWBrauner** [comment]
I was literally about to suggest something like that Paragon mechanic- the ability to "shake off" a spell effect before a full turn has passed without negating it completely. I've been on both sides of these solo boss encounters- I think there's room for a more interesting and engaging design.

**Comment by Marcloure** [comment]
If there is desire for a "solo" template for monsters, that is fine, but I don't think Legendary Resistance is an elegant way to do that. Also, some monsters aren't exactly known for being fought alone and have LR, like the Vampire.

**Comment by mlenser** [comment]
> If there is desire for a "solo" template for monsters, that is fine, but I don't think Legendary Resistance is an elegant way to do that.

Legendary Resistance allows a solo monster with legendary actions to work fairly well.

A Dragon, for example, can fly in, breath a few PCs, fly away and repeat a few times until a PC or two are down. Then it can fly in and use Frightful Presence or other spells to CC other PCs. Then it has multiple actions and legendary actions. Fully viable fight.

__________

You may not like the mechanic, but then it's on you to suggest replacements as it serves a very specific purpose and it cannot be removed outright without a replacement.

**Comment by Marcloure** [comment]
If removing it is too much, I think at least reducing LR to 1 or 2 per long rest should be done. 

Currently, with 3 LR/long rest and 55% of success rate on a save, a party of 4 PCs all causing effects worth of expending LRs would take 7 turns to expend every LR. That is almost 2 full rounds doing absolutely nothing just to expend the defensive resources of a creature, _if_ we consider no PC will use buffing or damaging effects. Players will more likely just not even try to pass this defense and will just default to straight damaging spells, which at least deal half damage on a successful save.

**Comment by itamarcu** [comment]
Other options for special features or rules for "big boss" monsters:
- Hard To Stop:  If the monster would be incapacitated, it loses half of its available actions on its turn instead of being incapacitated.
- Paragon / Shake Off - Whenever the monster's health is reduced to 75%, 50%, or 25% of the maximum (maybe specify exact numbers on page), it shakes off all status conditions (or makes a saving throw against all of them with advantage).
- Bite The Bullet - At the start of the monster's turn, if it's affected by a spell that prevents it from attacking, the spell ends and the monster takes damage equal to 15 times the spell's mana cost.
- Reduced Effect -  Effects that apply to the monster from this list are downgraded by 1 (2?) levels:  Paralyzed → Stunned → Incapacitated → Staggered → Loses 1 action.
- Push Through (Legendary Action, maybe multiple) - repeat a saving throw or attempt to dispel a spell on the monster.
- change some unique save-or-suck spells (e.g. wall of force, time hop, banishment) to only work on creatures under a certain CR, or only creatures that have less than X health remaining
- add some sort of a "save or suck" spell tag, and add a feature for certain monsters that simply says they are immune to it.  Could combine with Magic Resistance.
- more unique solutions such as "the nullbeast is immune to spells that require a target" or "any spell that would harm the mirror king is instead deflected to one of his servants if it's within 10 meters of him"

Not all of these are thought out or as powerful and widely applicable as Legendary Resistance, but I think some of them can work nicely to fix the problems LR is here to solve.

**Comment by mlenser** [comment]
> If removing it is too much, I think at least reducing LR to 1 or 2 per long rest should be done.

Ok, I've misunderstood your original issue. I thought you were saying it was unfun.

You're seemingly now saying Legendary Resistance is too powerful. Based on the threads above, it is a necessary mechanic. You can either ignore it for your games or suggest viable alternatives that are the same power. Less powerful options do not accomplish what Legendary Resistance is there for.

_________

If you guys flesh out some of the suggestions above - maybe discuss them on Discord this could be revisited, but they would have to add up to the current power level of Legendary Resistance.

**Comment by Marcloure** [comment]
I think it is powerful, unfun, and arbitrary. I can make suggestions for alternatives, yes.

**Comment by mlenser** [comment]
More threads:
<https://www.reddit.com/r/mattcolville/comments/f0b2sj/legendary_resistance_is_antifun>
> So, I like the spirit of Solo monsters - both from 4E and 5E, but I thought to tweak them a bit to play better with party CC and various effects. To that end, I recommend these two abilities in place of legendary resistance:

Tenacity. Whenever this creature would be incapacitated, stunned, restrained, or paralyzed - you instead force it to lose one legendary action

Durable (Recharge 5-6). When the creature makes a saving throw, it may add +10 to the result.

<https://forums.giantitp.com/showthread.php?585112-Legendary-Resistance-Unfun>
> Have Multiple Monsters. Balance the CR in such a way that when one dies, the other one gets stronger.
Let the monster save at the start of its turn against any ongoing effect.
Randomizer the number of uses.
Have Legendary Resistance only reduce the effect, instead of negating it.
Have it cost a Reaction
Have Legendary Resistance negate the effect, but using it affects the boss in another way.
Make it passive that increases save chance to 50%, and each time it's used the save chance lowers.
Give bosses a flat bonus to saving throws instead.
Change Legendary Resistance into advantage to saving throws.
Change it into “you can re-roll a failed save once”
Don't announce to your players when you use Legendary Resistance
Have Legendary Resistance cost a resource for the monster, such as a legendary action, spell slot or other.

**Comment by Marcloure** [comment]
Mythic Odysseys of Theos, an official book about larger than life heroes facing legendary creatures based on the Greek world of MtG, has a new design for boss monsters as well. There, some monsters have **Mythic Actions** and **Mythic Trait**. Basically, when a mythic creature is dropped to 0 hp, it instead is healed to a lot of HP (200+) and unlocks its mythic traits. They also gain new, more powerful legendary actions (called mythic actions) in this second form.

**Comment by Marcloure** [comment]
Another option: make these creatures completely immune to hard CC after they lose 50% of Health, so you can still stun or paralyze them for the first rounds of combat, but they make the later rounds thougher.

**Comment by mlenser** [comment]
> Mythic Odysseys of Theos, an official book about larger than life heroes facing legendary creatures based on the Greek world of MtG, has a new design for boss monsters as well. There, some monsters have **Mythic Actions** and **Mythic Trait**. Basically, when a mythic creature is dropped to 0 hp, it instead is healed to a lot of HP (200+) and unlocks its mythic traits. They also gain new, more powerful legendary actions (called mythic actions) in this second form.
> 
> Now, they do have Legendary Resistance, but this evolving or mitigating design is more interesting to me than just complete deny.

While this is an interesting mechanic, it would not mitigate the issues that Legendary Resistance solves. Without Legendary Resistance, a creature would just be CCd to death for longer.

**Comment by mlenser** [comment]
> Another option: make these creatures completely immune to hard CC after they lose 50% of Health, so you can still stun or paralyze them for the first rounds of combat, but the later rounds are thougher (instead of harder at the beginning and easier later, as LR promotes).

This just means the creature can be hard CCd to 50% health. Not a good mechanic.

**Comment by Marcloure** [comment]
> This just means the creature can be hard CCd to 50% health. Not a good mechanic.

It means it is just a normal creature until 50% of health. It's not like a Storm Giant is bad just because it doesn't have LR.
