### ISSUE TITLE
Consider moving some dominant feats to fighting stance

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#967]
Some feats, like <https://www.kryxrpg.com/feats/great-weapon-master> are so important to martial characters that they present a few problems:
- They are essentially "taxes". They prevent the character from choosing more thematic or meaningful choices for the best mechanical combat choice
- They prevent the character from switching weapons

If these type of feats instead activated after 6th level when you are using a fighting stance, then it would solve both problems. Characters could choose more meaningful feats and they could switch between their weapons without being mechanically worse.

**Comment by Marcloure** [comment]
One issue is that there aren't that many martial feats I think. A lot of feats are weapon or armor proficiency, the rest are boosts to weapon styles.

I think many martials would default to sentinel, heavy armor master, and savage attacker...

**Comment by mlenser** [comment]
There are 256 feats. There should be enough to choose from that give a thematic or minor mechanical benefit. If there are too many feats they can always be reduced, but I don't think that's a concern based on the number of them.

Plenty of options for martials. Many in Animal, Courage, Earth, Fury, Sentinel, Skirmish, etc.

There would surely be some "stronger" options that may need adjustment.

**Comment by DalenWBrauner** [comment]
> There should be enough to choose from that give a thematic or minor mechanical benefit.

I agree. I believe Marcloure's concern would only apply in cases of a pure martial, and one more focused on optimization than interesting thematics. But as long as we continue to keep things balanced, I don't feel players will be nearly as pressured to pick only the feats they believe to be optimal.

> If these type of feats instead activated after 6th level when you are using a fighting stance,

A fighting stance not accessible until higher levels? I like the sound of that.

**Comment by Marcloure** [comment]
Well, it's not 256 available feats of course. Let's take a Ranger or Warrior for instance. If they want to improve their martial abilities, they don't have a lot of options.

If weapon style feats are removed, and we exclude weapon/armor proficiency and spell-like feats, I count:

- Earth: Heavy Armor Master
- Fury: Savage Attacker, ~Heavy Armor Master~
- Guardian: ~Heavy Armor Master~
- Sentinel: Sentinel, ~Heavy Armor Master~
- Animal: Stalker Prowess
- Courage: Master Tactitian, Battle March, Rallying Cry

So, from 6th level options, we have 7 feats, 3 of which are from Courage. Deceit and Shadow have some additional options for roguish characters, so they are better served.

Now, this Ranger or Warrior can pick a theme that has fewer to none maneuvers to grab a feat, but they will have to expend 2 maneuvers for that, and will need to wait for a specific level for that. They can also pick 2nd level feats, which some are still worth picking at 6th, 8th or 12th level, but they aren't keystone to the playstyle like 6th level feats are.

**Comment by DalenWBrauner** [comment]
I don't see General Feats being considered here- there are quite a few of these that benefit characters and martials without any prereqs, whether your character is combat-focused or not.

**Comment by Marcloure** [comment]
Do I think these weapon feats should be removed? Yeah, probably. I have a TWF warrior at my table, for instance, and he just can't switch to a TH weapon because that would mean losing 2 feats (Twin Parry and Two-Weapon Juggernaut), and that would feel really bad. However, there would be a void left if they were removed, I believe.

**Comment by Marcloure** [comment]
> I don't see General Feats being considered here- there are quite a few of these that benefit characters and martials without any prereqs, whether your character is combat-focused or not.

There isn't any 6th level feat a martial could pick. But, as i said above: "They can also pick 2nd level feats, which some are still worth picking at 6th, 8th or 12th level, but they aren't keystone to the playstyle like 6th level feats are"

**Comment by DalenWBrauner** [comment]
It rather sounds like the true problems are the two outlined at the start of this issue, and:
> but they aren't keystone to the playstyle like 6th level feats are.

...should 6th level feats really be held in such regard? Is this a real consequence (or an intention) of the current system? I'm not sure the solution should be to make more "keystone" feats, and further cement 6th-level feats as the "optimal" choice.

**Comment by mlenser** [comment]
> If they want to improve their martial abilities, they don't have a lot of options.

This is one mindset that can be lessened if these feats are removed. Feats shouldn't only be chosen for pure mechanical combat benefit. They could, but the feats shouldn't be so good that other options like Battle Readiness, Calming Presense, Chef, Battle March, Master Tactician, or Rallying Cry are poor options. 

> If weapon style feats are removed, and we exclude weapon/armor proficiency and spell-like feats, I count [...] So, from 6th level options, we have 8 feats

There are so many pure martial options for feats at 6th level or less. Here is the full list:

- Animal: Born to the Saddle, Slip, Mounted Combatant, Primal Agression, Stalker’s Prowess, Thick Hide
- Courage: Battle Readiness, Battle March, Master Tactician, Rallying Cry
- Deceit: Ambusher, Light Weapon Master
- Earth: Stability, Heavy Armor Master, Resilient Warrior
- Fury: Battle Readiness, Heavy Armor Master, Punches in Bunches, Two-Weapon Juggernaut, Savage Attacker
- Guardian: Armored, Heavy Armor Master
- Marksman: Point Blank Shooter, Sniper
- Sentinel: Heavy Armor Master, Sentinel (if not used in a fighting stance), Polearm Master (if not used in a fighting stance)
- Skirmish: Slip, Twin Parry, Fleet of Foot, Fluid Footwork, Light Weapon Master, Punches in Bunches
- General feats: Dungeon Delver, Martial Initiate, Tough

If we're just looking at a "standard" warrior then many of those options still apply. Born to the Saddle, Slip, Mounted Combatant, Stalker’s Prowess, Thick Hide, Battle Readiness, Battle March, Master Tactician, Rallying Cry, Stability, Heavy Armor Master, Resilient Warrior, Two-Weapon Juggernaut (for TWF build), Savage Attacker, Sentinel (if not used in a fighting stance), Polearm Master (if not used in a fighting stance), Twin Parry (for TWF build), Fleet of Foot, Fluid Footwork, Dungeon Delver, Martial Initiate, Tough.

I could 22 feats, though there are a few overlaps and a few for specific fighting styles so probably ~16 for a specific fighting style.

And a few more that aren't pure martial (not including skill feats):

- Animal: Spirit Seeker, Totem Spirit
- Courage: Calming Presense, Chef
- Deceit: Actor

_________

So even without the feats, I don't see any kind of deficiency of options.

**Comment by Marcloure** [comment]
I purposely didn't list 2nd level feats, I thought that was clear. Having to pick a 2nd level feat at the 6th or 8th level because nothing the system offers interests you would be a bummer. Imagine picking a feat that grants you advantage against push and prone, or an additional skill capacity while others are gaining Greater Metamagic, Spell Ward, Spatial Acceleration, Grounded, Vanish, Mantle of Flames, etc. 

Think of it like this: the list I provided lists the strongest feat a "fighter" character can pick at 6th and 8th level. If you aren't picking from this list, you are picking a weaker 2nd level feat. This list contains 8 options, 3 of which are related to a specific style of play (leading your allies).

For that reason, I really believe most people will prefer to pick Sentinel, Heavy Armor Master/Thick Hide, or Savage Attacker than a 2nd level feats. Maybe something like Tough at the 12th level could be an exception.

Also, you listed:

- Punches in Bunches, Two-Weapon Juggernaut
- Sniper
- Armored
- Light Weapon Master
- Primal Agression

This list includes feats that, as I said, either no Paladin, Ranger, or Warrior would take, or that will become a fighting style. Primal Agression and Punches in Bunches for instance, only makes sense if you are following a specific unarmed build. As for Armored, Warriors and Paladins already use plate armor, and I don't even think a STR Ranger works, since they will have a very mediocre Defense.

Lastly, isn't Light Weapon Master becoming a style as well?

---

Now, I am aware that my issue isn't completely related to your issue. Having few 6th level options for pure martial, front line characters isn't completely related to how the existing feats locks their weapon of choice. Just don't think removing these feats will free these characters to be able to pick from a list of dozens.

**Comment by mlenser** [comment]
The main list of feats was for all martials. I included a list of feats for the "standard" warrior:

>If we're just looking at a "standard" warrior then many of those options still apply. Born to the Saddle, Slip, Mounted Combatant, Stalker’s Prowess, Thick Hide, Battle Readiness, Battle March, Master Tactician, Rallying Cry, Stability, Heavy Armor Master, Resilient Warrior, Two-Weapon Juggernaut (for TWF build), Savage Attacker, Sentinel (if not used in a fighting stance), Polearm Master (if not used in a fighting stance), Twin Parry (for TWF build), Fleet of Foot, Fluid Footwork, Dungeon Delver, Martial Initiate, Tough.

The "standard" warrior can use TWF, Polearms, or great weapons which I then narrowed down:

> Without duplicates, I count 22 feats, though there are a few overlaps and a few for specific fighting styles so probably ~16 for a specific fighting style.

~16 is still correct for a specific fighting style like TWF, Polearm, or great weapons.

> the list I provided lists the strongest feat a "fighter" character can pick at 6th and 8th level.

Your list is vary narrow and by no means encompases all the best feats for a martial. You excluded options like +speed which would greatly help any melee martial.

> This list includes feats that, as I said, either no Paladin, Ranger, or Warrior would take, or that will become a fighting style.

Paladin, Ranger, and Warrior can be built in many different ways. They can all be archers, twf, polearm, great weapons, sword and board.

> Just don't think removing these feats will free these characters to be able to pick from a list of dozens.

Why not? They'll have 1-2 extra feats that aren't locked down to their ability to do damage. Inherently that'll make the mmore versatile.

**Comment by Marcloure** [comment]
> Your list is vary narrow and by no means encompases all the best feats for a martial. You excluded options like +speed which would greatly help any melee martial.

I literally picked evey 6th level feat from Animal, Courage, Earth, Fury, Guardian, Sentinel, Skirmish, and General Feats and listed them, excluding the ones that are spell-like or that are weapon-specific, since they'll be coverted to stances. Also, I did list +speed feats such as Stalker Prowess and Fleet of Foot (slashed because it's a duplicate).

> Paladin, Ranger, and Warrior can be built in many different ways. They can all be archers, twf, polearm, great weapons, sword and board.

Yes? I don't see the relation with my issue. Whether a Paladin uses a polearm, greatsword, or a shield won't matter when looking at which feats they can pick. The 6th level feats available to them are still only the 8 I listed.

> Why not? They'll have 1-2 extra feats that aren't locked down to their ability to do damage. Inherently that'll make the mmore versatile.

Because their list of 6th level feats don't have a dozen feats, unless they go out of their way to pick Antimagic, Madness, Luck or Fate just for the feat. Not that doing it is bad, but the cost is also quite high. Ideally we would add some 2 or 3 feats to the more common martial themes, since most of them have only 1 6th level feat (not counting weapon-specific feats, ofc).

**Comment by mlenser** [comment]
We're off topic now. If there is any kind of feat gap after this work is done then please open a new issue.

**Comment by mlenser** [comment]
- Fighting Stances have been updated to have a major benefit at 6th level and higher. [#967](https://github.com/mlenser/kryx-rpg-issues/issues/967)
  - Added a new fighting stance called Polearm Specialism.
  - Dueling fighting stance now provokes an opportunity attack when a creature enter your weapon’s reach.
  - Defense fighting stance removed as the Protection fighting stance absorbs it.
  - Elusive fighting stance removed.
  - Great Weapon Master, Hold the Line, Point Blank Shooter, Polearm Master, Primal Aggression, Punches in Bunches, Sentinel, Sniper, Twin Parry, and Two-Weapon Juggernaut feats have all been removed as they are now incorporated into the fighting stances.
  - Brace maneuver removed.
