### ISSUE TITLE
Consider removing the action cost to maintain spells and companions

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#993]
Perhaps spells should not cost an action if they require concentration. Or perhaps they should not have concentration if they require an action.. 🤔 

https://github.com/mlenser/kryx-rpg-issues/issues/988
> Controlling the companion
> Finally the paragraph talking about controlling your companion ends with the sentence "Once given an order, the creature continues to follow it until its task is complete." This wording implies that you can give a general command to your companion, such as attack all enemies, and they will continue to do so without you needing to use your action on subsequent turns to keep it going. It was mentioned that this was how the feat was originally intended to function, so it may not need to be changed. If this is no longer the case and the character does have to issue a command each turn, the feat's wording will need to be updated to reflect that a companion cannot continue to follow a task.
>
> Similar wording to above exists in both the Homunculus and Eidolon feats, which may also need to be updated should the Animal Companion feat be updated.

**Comment by Marcloure** [comment]
I think it could be a mix. I think removing the repeatable action for summons is the best for several reasons:

1. With most spells taking 2 actions to cast, if you control a spell using an action, you are very limited in what you can do with your other action. I wouldn't say this is a _major_ deal, specially considering that repeatable spells other than summons exist and they are fine in my experience.
2. I think summoning a creature should come with its own perks instead of being just a reflavoring of Spiritual Weapon, so even if Spiritual Weapon and the likes keep the repeatable action, I think the summoned creature should act on its own.
3. It's fictionally dumb that the creature would just stand there if you don't control it. I think this is against the fantasy of the spell, and it would make it even harder to balance controlling the creature vs. using your own stuff.

For spells like minute meteors and crown of stars, I think they shouldn't require concentration. They are kinda like an optional attack you can make, I don't think they would break the game without concentration, since they are neither a buff nor a debuff/control spell and they already have limited uses.

For spells that can deal huge amounts of damage or cause controlling effects, like Force Hand or Spiritual Weapon, I think the concentration and the action to control is fine. Sure, Spiritual Weapon could deal less damage and not require concentration, I think that is a valid option too, specially to make it compete with spells like Force Hand, that do everything Spiritual Weapon does and more.

**Comment by mlenser** [comment]
- **Feats**
  - Summon spells and companion feats no longer require an action for you to command your summon. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
- **Themes**
  - Avascular Mass damage reduced from 3d6 to 2d8.
  - Acid Fog, Cloudkill, Cold Fog, Dust Devil, Fissures, Illusory Dragon, Incendiary Cloud, Kinetic Onslaught, Moonbeam, Rolling Thunder, Sandstorm, and Vile Maws changed from requiring an action (or two in some cases) to move to moving it at the start of your turn with no cost. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Engulfing Acidic Sphere, Gusting Sphere, Maelstrom, Prismatic Vortex, Watery Sphere, and Whirlwind changed from requiring two actions to move to moving it at the start of your turn with no cost. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Acidic Pools, Black Tentacles, Darkness, Daylight, Entangle, Entangling Debris, Grasping Hands, Insect Plague, Spike Growth, and Storm Sphere can now be moved at the start of your turn with no cost. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Call Lightning, Crown of Stars, Enervation, Flaming Sphere, Force Sword, Homing Motes, and Minute Meteors no longer require concentration. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Flaming Sphere reworked to be more similar to spells like Enervation and Spiritual Weapon as it makes more thematic sense and Fire already has Incendiary Cloud. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Shadow Anchor damage increased. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Earthen Grasp, Force Hand, Giant Crawling Claw, and Kinetic Grasp no longer require concentration and have had their damage reworked. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Spells that can move on your turn can optionally be moved further if you spend an action. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
  - Summon spells and companion feats no longer require an action for you to command your summon. [#993](https://github.com/mlenser/kryx-rpg-issues/issues/993)
