### ISSUE TITLE
Bestow Misfortune still grants disadvantage to saving throws

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#994]
https://www.kryxrpg.com/spells/bestow-misfortune

Bestow Curse lost it's disadvantage on saving throws effect, but Bestow Misfortune still has it. Also, about the effect:

> While unlucky, the creature has disadvantage on attacks made against you

Isn't that completely bad for a 2 mana spell? Just use blur or something at that point. I think the disadvantage should apply to any attack roll (valid for both Misfortune and Curse).

**Comment by mlenser** [comment]
- Bestow Curse and Bestow Misfortune now impose disadvantage on all attacks instead of attacks against you. [#994](https://github.com/mlenser/kryx-rpg-issues/issues/994)
  - Bestow Misfortune no longer impose disadvantage on saving throws. [#994](https://github.com/mlenser/kryx-rpg-issues/issues/994)
  
  
Thanks!
